### ISSUE TITLE
Feature Request: Dynamically adjust the Exclude/Priority dropdown lists

### ISSUE THREAD

**Issue by Taizunz** [DevilXD/TwitchDropsMiner#298] opened 2023-09-07 18:30 UTC
Thanks for this app!

I'd love if the list of games in the exclusion and priority dropdown lists automatically get removed once you've added them to the active list of exclusions/priorities. This is to save on having to scroll through all of the same games every time you want to add a new game.

Example:
I want to exclude Fortnite.
I scroll down the list of available games in the Exclude dropdown, and select Fortnite.
Once Fortnite has been added it still appears in the dropdown list among all the other games you can select - this is redundant, and is the part I'd like to see changed.

**Comment by DevilXD** [comment] 2023-09-07 18:35
Hello o/

Hmm, I see where the problem is. I like the idea of it not appearing again if it's already there. This will be added in one of the future updates of the miner. Thank you for the suggestion 🙂

**Comment by DevilXD** [comment] 2024-07-03 15:06
This one can finally be closed via https://github.com/DevilXD/TwitchDropsMiner/commit/17009d7a65efa7c86585330cf94e91fcca86dc3a.

**Closed by DevilXD** 2024-07-03 15:06 UTC
Labels: Enhancement, Solved
