### ISSUE TITLE
Not showing all games

### ISSUE THREAD

**Issue by Nollasko** [DevilXD/TwitchDropsMiner#264] opened 2023-08-05 21:57 UTC
It shows only few games, when there are a lot available
![image](https://github.com/DevilXD/TwitchDropsMiner/assets/67293930/9f777c26-b1e3-47aa-8aee-87b1dc16a79c)
![image](https://github.com/DevilXD/TwitchDropsMiner/assets/67293930/e938a9a5-377a-470a-bb31-187279825f55)

**Comment by thejuves** [comment] 2023-08-05 23:56
Same, it seems that app showing games that are in priority list and no more

**Comment by Diseraph** [comment] 2023-08-06 03:35
I can confim this too. KOTC is an active campaign and when i open Twitch channel for it manually, it states I am receiving drops but this is not showing up in the Inventory or in the games list. 
If it helps, these campaigns were showing last night ~ 12 hours ago from this post.

**Comment by EmiMathesi** [comment] 2023-08-06 07:26
Same problem. 2 games on the list
![image](https://github.com/DevilXD/TwitchDropsMiner/assets/126239039/196421b0-f2af-40c6-b451-b4906f862ad2)

**Comment by DevilXD** [comment] 2023-08-06 08:22
Hello o/

After some simple debugging, it seems that Twitch no longer reports all ongoing campaigns via GQL, if one is using the SmartTV login (like this miner does). The response comes through, but the `"dropCampaigns"` key is empty:

![picture](https://github.com/DevilXD/TwitchDropsMiner/assets/4180725/381b42cd-273f-4173-bf8c-38af7156c955)

This means the miner has lost the ability to discover new, unprogressed campaigns, and thus won't add their games to the UI combobox.

The good news is that the "Game name" entry is just a text entry with a dropdown that lets you pre-select a "known" game name, but otherwise functions as any ordinary text entry. This allows you to just type in the name of a game you'd want to add, and add it to the list that way. Just make sure to not make any spelling mistakes, the comparison is case-sensitive, and requires the exact game name, as displayed on the Twitch campaigns page.

Another good news is that Inventory view seems to still be working, so any campaign that's already started, will continue to be returned, and thus handled by the miner like expected. This means you can login to Twitch on your PC or phone, pick a campaign you want to start, tune into some random stream to start the campaign (get the first minute of progress), and then let the miner handle it from there.

The bad news is that I have no immediate resolution to this problem. There is a chance this issue is only temporary, and campaigns view will return to normal later. Or it's permanent, and I'll need to figure out another way of getting that information later.

**Comment by Diseraph** [comment] 2023-08-06 08:49
Thanks for being so quick to look into this DevilXD you are awesome

**Comment by DevilXD** [comment] 2023-08-06 10:03
I just happened to be off work delegation and home today, so could spare a quick look at least. I'm going back tomorrow though, and it'll be another week before I'll be able to get some more free time.

Still not sure what to do here, the web version returns campaigns, but the miner version doesn't. Web version is protected by the integrity system, so can't use it. For now, all campaigns need to be started manually - after that, they'll appear in the inventory view and everything should work from there as expected.

**Comment by Diseraph** [comment] 2023-08-06 10:43
No problems, not sure if this is related but KOTC aren't being picked up. I'm not linked (but i usually can get the drop anyway). even with manual addition (and the drop started), its not being picked up in the miner main section. It's recognised in the inventory. I have manually added King of the Castle,. Not sure if this is a naming issue or not being linked but I was able to pick up the drop in the past (can't remember if by the miner or on my own)

**Comment by DevilXD** [comment] 2023-08-06 10:59
The miner requires a linked account to consider a drop "worth mining". That's most likely why.

**Comment by MuffinzCat** [comment] 2023-08-07 14:45
would it be possible to have the app skim the webpage for looking at available campaigns or something like that?

**Comment by KevinNovak** [comment] 2023-08-07 17:57
> The miner requires a linked account to consider a drop "worth mining". That's most likely why.

I deleted my current Twitch Drops Miner install and downloaded a fresh version, re-linked my Twitch, and still only seeing 1 option show in the list of games.

**Comment by DevilXD** [comment] 2023-08-07 18:37
@MuffinzCat Viewing https://www.twitch.tv/drops/campaigns requires logging in, and logging in requires an authorization token. The miner already uses one, but it's been locked out of the page contents per this issue. What you see when you open the browser, is the page via your web authorization token, which is protected by the integrity system, which isn't beatable at this time, so using it is not possible. So no, it's not possible to "skim" the website in any way.

@KevinNovak That's expected, as this issue is caused by Twitch itself, not the miner installation or linking status, or anything like that. Note that you can still add games like before, albeit you'll have to type out their names yourself (or just copy-paste them from the website).

**Comment by spuukii** [comment] 2023-08-08 00:54
> > The miner requires a linked account to consider a drop "worth mining". That's most likely why.
> 
> I deleted my current Twitch Drops Miner install and downloaded a fresh version, re-linked my Twitch, and still only seeing 1 option show in the list of games.

This is part of the issue/bug. 

See reply here: https://github.com/DevilXD/TwitchDropsMiner/issues/264#issuecomment-1666771153

There's currently no fix other than manually starting a drop and manually typing it into the list. The dropdown won't be working until there's either a workaround or twitch fixes their API (unless its intentional).

**Comment by Diseraph** [comment] 2023-08-08 06:50
I'm starting to see some games show up in my list without me manually adding them. anyone else?

**Comment by spuukii** [comment] 2023-08-08 13:53
> I'm starting to see some games show up in my list without me manually adding them. anyone else?

The only time I see the list update is if a new drop was started then it'll be added to the list. Assuming it's caching "known" drop campagins/streams/games.

**Comment by Suz1e** [comment] 2023-08-08 18:17
You can watch it on the webpage for 1 minute, activate the treasure drop, and then open the software to continue hanging the treasure drop of this game normally

**Comment by DevilXD** [comment] 2023-08-08 19:22
Since there seem to be some confusion around what exactly happens, so I'll try to explain.

The miner utilizes the "contents" of these two Twitch pages:

- https://www.twitch.tv/drops/inventory
- https://www.twitch.tv/drops/campaigns

These are also known in-short as just "inventory" and "campaigns". The contents are fetched via the underlaying page's GQL request, each of the pages having it's own, different one. The "campaigns" page request has currently been crippled/disabled/god-knows-what-exactly-happened, and as the result, only the "inventory" one remained.

The inventory request contains all information that you can see on the inventory page - this includes primarily the drops your account is currently in the process of earning. Having at least 1 minute or percent of progress on a drop is enough for it to appear on the inventory page, and be recognized by the miner. Thus, you can "manually" force certain drops/campaigns to appear there, by watching an eligible stream for at least one minute (eg. in the browser), enough to gain some progress on the drop - and the miner should pick it up from there, as it's able to still see the inventory like before.

The "campaigns" page was used to let the miner know about all campaigns that have no progress done towards them, and can be started - since that's gone now, that information is missing. This is also the main reason the game picker isn't displaying the games you'd expect - because it can only see those on the "inventory" page instead.

You can open https://www.twitch.tv/drops/inventory at any time, and whatever drops, campaigns and progress you can see there, should appear in the miner as well (may require a reload first).

**Comment by MuffinzCat** [comment] 2023-08-08 19:54
would this mean that previously completed games would appear on the list again if it gets another campaign?

**Comment by DevilXD** [comment] 2023-08-09 18:58
Yes and no. Yes, because normally, that's what usually happens, especially for games that get new weekly campaigns. No, because it's not guaranteed to happen, as not progressing a particular game's campaigns for a while, somehow disables this process and they stop appearing. At least that's how it used to work before, it could've changed now.

**Comment by Larsy93** [comment] 2023-08-11 16:14
would it be possible to manually export/import the https://www.twitch.tv/drops/campaigns list or something along those lines if we are not able to fully automate it anymore

**Comment by DevilXD** [comment] 2023-08-11 19:35
@Larsy93 I've already explained why it's not possible here: https://github.com/DevilXD/TwitchDropsMiner/issues/264#issuecomment-1668400485

**Comment by Luckz** [comment] 2023-08-12 02:12
> @Larsy93 I've already explained why it's not possible here: [#264 (comment)](https://github.com/DevilXD/TwitchDropsMiner/issues/264#issuecomment-1668400485)

"Manually" means that the user DLs the page in some fashion, or runs javascript that exports a JSON/.. of active campaigns to file/clipboard, and TwitchDropsMiner loads this info from file/clipboard.

**Comment by DevilXD** [comment] 2023-08-12 10:34
This is a Python program, I don't want to have to introduce any Javascript or side loading into the application. Definitely won't be developing any browser extensions for this either.

I've remembered that there's an `DropsHighlightService_AvailableDrops` GQL request, one can call on a channel to get a list of drops that could be earned by watching said channel. The thing is, there's zero handling for this in the miner right now. Since campaigns discovery no longer works, I wouldn't be able to get an accurate list of channels that can be watched to progress said campaigns, until after the user manually adds the campaign to the inventory tracker, by watching at least one minute of a stream.

This pretty much calls for a way of manually adding channels to the miner, and the entire logic flow having to be reversed. Instead of the drop campaigns deciding which channels to use for progressing them, the channels themselves would report which drop campaigns they can progress. This also means having to replace the Priority game selector with a channel selector, although I think it can be left as-is and instead only adding a way to add channels would be enough.

I didn't want to do this as the whole thing was supposed to be as automatic as it was possible to do at the time, but now the times have changed, and this sounds like the only option that could work. The problem is, I've recently started the 4th month of my work delegation on a project in a remote location, so I still barely have any time for any actual coding and changes. I really wish this wasn't the case, but I can't help it.

I'll try getting to this in any spare time I will be able to find, but can't make any promises on when this will be added/changed.

**Comment by MuffinzCat** [comment] 2023-08-12 10:56
Yeah that's okay, it'd be selfish of people to demand that you'd work on an issue, let alone one you didn't create yourself

**Comment by DJ4everkill** [comment] 2023-08-12 22:32
Can say so much that only the games that show up in the dropdown is the only games it will mine. i have Overwatch 2 in my prioity list, but it won't gather the new torbjörn skin. so ATM it's only useable for 2 games. at least for me.

**Comment by iFireMonkey** [comment] 2023-08-13 15:21
A very slight workaround is to start getting watch progress by clicking on a stream with drops available to start gaining progress and then letting the bot continue gaining the progress.

**Comment by Alorf** [comment] 2023-08-15 14:16
Changing the client-id of SMARTBOX in the constants file fixed the issue.

I noticed that with the user agent that is provided in the constants.py file, the client-id is not the same when I do request to twitch.tv and m.twitch.tv with the same user agent ( `Mozilla/5.0 (Linux; Android 7.1; Smart Box C1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36` ) and a web browser ( Brave ).

Here is the "new" client-id : `r8s4dac0uhzifbpu9sjdiwzctle17ff`

I also don't know if the client-id used in the app is the same as this one but, for now, it works fine with everything back.

I don't know if it is really important to have an appropriate client-id with the device that the miner tries to "emulate" to have these kinds of information.

**Comment by KevinNovak** [comment] 2023-08-15 16:50
Is someone able to do a PR with the updated client ID?

**Comment by DevilXD** [comment] 2023-08-15 17:09
@Alorf Interesting, but it's not exactly the ultimate solution yet. The integrity system protects only selected endpoints, with the crucial one being the drop claiming one. Fetching a list of campaigns doesn't require integrity authorization, so everything may seem to work at first, but then will end up with an error during the claim operation. Replacing Client ID that's not protected by the integrity system, with a one that is, doesn't lead anyone anywhere.
Have you claimed any drops with it yet?

As a side note, this opens up cross-token data access as a possibility. The mechanics of it will require a #220 level of implementation though, so it'll have to wait for sure, but it may become eventually necessary to keep this project alive.

**Comment by DevilXD** [comment] 2023-08-15 17:16
I have a 15m long drop available to test this on, so I guess we'll find out soon.

**Comment by Danzo51196** [comment] 2023-08-15 17:20
@DevilXD I've done the R6S drops and it's worked as it normally would, however I'm keeping an eye on it. I am only a user, so I can only test to see if things like this work but it's looking promising from a temporary point.

**Comment by Alorf** [comment] 2023-08-15 17:21
Yes, it works, I tried with the Rainbow Six drops

**Comment by DevilXD** [comment] 2023-08-15 18:38
https://github.com/DevilXD/TwitchDropsMiner/commit/70035cde36dc1c225e4ebedfbfc8cec7d0d30994 implements the new Client ID, with some more appropriate user agents to it. The pre-release build already compiled, so you can grab it and give it a shot.

**Don't forget that, as with all Client ID changes, you'll need to reauthenticate the miner - for that, you need to delete the `cookies.jar` file and then login anew.** If you'd like to unlink the old Smart TV token, [go to the Twitch connections page](https://www.twitch.tv/settings/connections) and click on "Unlink" next to "Twitch for TV". Doing this is not required, but encouraged, as the old token never expires, and still gives access to your account to anyone who'd somehow (god forbid) obtain it. Your choice.

Let me know if it works or more needs to be done here.

**Comment by RainOne** [comment] 2023-08-15 18:51
The settings page on the software now show all available games and the inventory page shows all available campaigns, but I'm getting a "cannot connect to Twitch" on the "gathering channels" sequence on the main pane. No other log to speak of.

**Comment by DevilXD** [comment] 2023-08-15 18:55
For that message to appear, Twitch server has to stop responding, or respond with an error. Unless you're a programmer or have programming experience, figuring out which one of the two is it is impossible.

All you can do is verify your internet connection, and try again.

**Comment by Bamboozul** [comment] 2023-08-15 19:43
> The settings page on the software now show all available games and the inventory page shows all available campaigns, but I'm getting a "cannot connect to Twitch" on the "gathering channels" sequence on the main pane. No other log to speak of.

I'm having the same issue.

![Screenshot 2023-08-15 214213](https://github.com/DevilXD/TwitchDropsMiner/assets/101983929/d82ba725-508e-485a-930c-1e3bcb1ccf7e)

**Comment by DevilXD** [comment] 2023-08-15 20:11
Yes, it turns out that new user agents messed up Spade URL extraction. I'm working on a quick patch, while I still have time.

**Comment by Bamboozul** [comment] 2023-08-15 20:43
> Yes, it turns out that new user agents messed up Spade URL extraction. I'm working on a quick patch, while I still have time.
> 
> EDIT: It's done: [29fa220](https://github.com/DevilXD/TwitchDropsMiner/commit/29fa22023852cf1232e2d5794ebef22992628fe3)

Still stuck on "Gathering channels..." and after like 10~15 min you get "Twitch is down, retrying in 1 seconds..."

**Comment by DevilXD** [comment] 2023-08-15 21:02
Yes, the quick patch resolves only the Spade URL extraction step, it does not resolve your connectivity to Twitch. "Twitch is down" message is shown on 5XX errors (Twitch server error), while "Cannot connect..." message is shown on a timeout (connecting took too long), or another error related strictly to connecting to Twitch (even before any response data is transmitted back).

I cannot help you solve this one, it can be anything:

- You have actual, temporary internet connection problems.  
- You're using Wi-Fi connection with a poor signal strength.  
- Your AV (antivirus) is denying the connection because it's coming from an unsigned executable.
- Your firewall is not letting the request through.
- You're using a Proxy that doesn't seem to work like it should.
- Some people need to login to some internal network server, to receive internet access in the first place - all calls redirect to it automatically, but that can break or fool the miner, usually resulting in weird errors.  
- Your ISP is blocking Mobile Twitch on their firewall (for some reason).
- You have a shared IP address and that usually complicates things; Twitch might be confused about how to respond, or has a limit and already responded, but not to your request specifically.  
- Twitch just doesn't like you and your PC very much, and has decided to not respond.

..., and the list just goes on and on. It'd take an eternity to debug every single connectivity issue case, everyone has it different, etc. I can only suggest where to look for a possible fix, but other than that, you're more or less on your own. None of this happens on my PC. I can say that after the change, the requests definitely take a longer time for me, as each loading step executes, but I can only blame Twitch being slow on it, since nothing else besides the client ID has changed.

**Comment by Bamboozul** [comment] 2023-08-15 21:08
Switched back to [137f540](https://github.com/DevilXD/TwitchDropsMiner/commit/137f540d62560524a9a511a7793616e6d4478e68) for now.

**Comment by RainOne** [comment] 2023-08-15 21:13
So, I was having that issue. I was getting multiple "twitch is down" or "twitch stopped responding" messages.  I'm watching twitch on a different computer than TwitchDropsMiner is running, so I was also getting "Earned points for watching" from this other channel I was watching. I can also watch twitch on a browser on the machine that the Miner is running. 

I'm from a different country, so I put on a US IP Address proxy - didn't change anything. Got the same behavior.

I deleted my environment, re-built it, re-downloaded the application, re-did the login and I was getting equally slow and unresponsive behavior - no proxy running. I alt-tabbed from my raspberry pi instance (where Miner is loading) and went to do something else. Came back, it loaded the channels and is currently idling for items. 

![XhVuOnO](https://github.com/DevilXD/TwitchDropsMiner/assets/7484546/a870f2d0-a5d0-4fde-b1dd-f558ccd39ce6)

I have no issues watching twitch on the raspberry pi instance or on any other computer on my network. I don't really know how to debug a python application, so I can't really help much more than this :D

**Comment by Diseraph** [comment] 2023-08-16 00:29
Dev, my twitch is currently working with none of the changes poeple are giving a go. so if you need a test subject, I can volunteer :)

**Comment by DJ4everkill** [comment] 2023-08-16 09:07
so far claimed R6 siege drop with only 5 min of gathering channels. no lost connection. 
seems i don't have any trouble with latest dev build. Only when it goes idle, then it comes with this. 

09:15:34: Claimed drop: Tom Clancy's Rainbow Six Siege Reveal Y8S3 Charm (1/1)
09:15:54: No active campaigns to mine drops for. Waiting for an active campaign...
09:15:56: ERROR: Exception in Websocket[6]
09:15:56: Traceback (most recent call last):
09:15:56:   File "websocket.py", line 166, in _handle
09:15:56:   File "websocket.py", line 214, in _handle_topics
09:15:56:   File "websocket.py", line 324, in send
09:15:56:   File "aiohttp\client_ws.py", line 165, in send_json
09:15:56:   File "aiohttp\client_ws.py", line 151, in send_str
09:15:56:   File "aiohttp\http_websocket.py", line 690, in send
09:15:56:   File "aiohttp\http_websocket.py", line 601, in _send_frame
09:15:56: ConnectionResetError: Cannot write to closing transport
09:17:24: Watching: Wookie_Legend

**Comment by DevilXD** [comment] 2023-08-16 19:26
I've put the latest pre-release on my work PC (used the Github version, didn't build myself), and startup took roughly 2m and 30s:
![obraz](https://github.com/DevilXD/TwitchDropsMiner/assets/4180725/71ecddae-76b0-4823-9b55-90d5c680ac4e)
I'm using my mobile phone as a router/hotspot, so the signal quality ain't that great, but still.

This whole "Mobile Web" Client ID seems to just be slow in general, for some reason. I wonder if Twitch is intentionally throttling it's speed, to push people into downloading the app instead. I guess only Twitch knows.

There isn't much I can do about this. The current request timeout is set to 10 seconds, which should be plenty to get a response already, but with Twitch being this slow, it may just not be enough. Increasing the timeout may reduce overall app performance in situations where the connection is unstable, leading to slower operation, but it may also improve overall reliability.

@DJ4everkill Please file a separate issue with that error, seems like something that needs to be worked on some more.

**Comment by Bamboozul** [comment] 2023-08-16 23:19
Can anyone confirm if the new release with the MOBILE_WEB Client ID uses more bandwidth than the previous one?

**Comment by JourneyOver** [comment] 2023-08-17 01:00
I've just been stuck on "gathering channels" for like the past 2 hours.. running commit version d5410b2

**Comment by stijndp** [comment] 2023-08-17 15:01
> Can anyone confirm if the new release with the MOBILE_WEB Client ID uses more bandwidth than the previous one?

"Slight" difference :)

![image](https://github.com/DevilXD/TwitchDropsMiner/assets/29801608/6213ad9a-9156-4817-82cf-9596c5eb4cb4)

But at least the functionality is working again. Each rose has it's thorns.

**Comment by DevilXD** [comment] 2023-08-17 17:18
Wait, that's the difference? That shouldn't be happening, unless Twitch sends a bunch of random shit in addition to the expected data. This would also explain why it's so slow all of the sudden.

I'll try looking into it in some free time.

**Comment by guihkx** [comment] 2023-08-17 18:32
On commit 137f540d62560524a9a511a7793616e6d4478e68 (i.e. before the recent mobile-related changes), HTTP requests the app make looked like this:

![image](https://github.com/DevilXD/TwitchDropsMiner/assets/626206/abaf3353-3633-4dd4-8e3a-ed5aedddeadc)

On commit d5410b2aa5ee6148ca3e01e04addd29a1ff4db91, they look like this:

![image](https://github.com/DevilXD/TwitchDropsMiner/assets/626206/8d1e3f38-8199-45a4-9b42-8dbabf5f35ba)

A few observations:

- Responses from `m.twitch.tv` can be up to four times slower than responses from `twitch.tv`
- In `constants.py`, `BASE_URL` is set to `https://twitch.tv`, which causes an extra HTTP redirect. I propose changing it to `https://www.twitch.tv` instead
- Since the app now uses mobile User-Agents, every request to `twitch.tv` also causes an extra HTTP redirect to `m.twitch.tv`. Perhaps something like this would be an improvement:

    ```diff
    diff --git a/twitch.py b/twitch.py
    index d940a26..6d36e1a 100644
    --- a/twitch.py
    +++ b/twitch.py
    @@ -522,7 +522,7 @@ class _AuthState:
                 jar = cast(aiohttp.CookieJar, session.cookie_jar)
             if not self._hasattrs("client_version", "device_id"):
                 async with self._twitch.request(
    -                "GET", BASE_URL, headers=self.headers()
    +                "GET", "https://m.twitch.tv/", headers=self.headers()
                 ) as response:
                     page_html = await response.text("utf8")
                     assert page_html is not None
    ```

After adding the changes I proposed, the list of HTTP requests should look like this:

![image](https://github.com/DevilXD/TwitchDropsMiner/assets/626206/cea3d0b7-6c9a-4b15-b79d-8a48d8136866)

Which is not as good as before, but a tiny bit better. There are still a bunch of requests being made to Twitch's main page, which I don't understand why since I'm not too familiar with how the app works internally.

**Comment by guihkx** [comment] 2023-08-17 18:49
I think I got it. [This change](https://github.com/DevilXD/TwitchDropsMiner/commit/70035cde36dc1c225e4ebedfbfc8cec7d0d30994#diff-4769eb01c0ca13db2bd1e0325dc16afaa30a5d607ce1cf9a499696e4a60644a6R532) removed the ability to extract `client_version` from Twitch's page, however, we still have two places where the app checks for their existence:

https://github.com/DevilXD/TwitchDropsMiner/blob/d5410b2aa5ee6148ca3e01e04addd29a1ff4db91/twitch.py#L520

And, most importantly, here:

https://github.com/DevilXD/TwitchDropsMiner/blob/d5410b2aa5ee6148ca3e01e04addd29a1ff4db91/twitch.py#L523

This second check is what is triggering the extra requests to Twitch's main page. Removing those `client_version` checks reduces the total list of HTTP requests greatly:

![image](https://github.com/DevilXD/TwitchDropsMiner/assets/626206/a6bb375e-51ff-476c-a76f-66f8cef5069d)

If someone wants my changes to test for themselves:

```diff
diff --git a/constants.py b/constants.py
index a40ca71..79023a8 100644
--- a/constants.py
+++ b/constants.py
@@ -80,7 +80,7 @@ MAX_TOPICS = (MAX_WEBSOCKETS * WS_TOPICS_LIMIT) - BASE_TOPICS
 MAX_CHANNELS = MAX_TOPICS // TOPICS_PER_CHANNEL
 # Misc
 DEFAULT_LANG = "English"
-BASE_URL = URL("https://twitch.tv")
+BASE_URL = URL("https://www.twitch.tv")
 # Intervals and Delays
 PING_INTERVAL = timedelta(minutes=3)
 PING_TIMEOUT = timedelta(seconds=10)
diff --git a/twitch.py b/twitch.py
index d940a26..7ea2c27 100644
--- a/twitch.py
+++ b/twitch.py
@@ -517,12 +517,12 @@ class _AuthState:
     async def _validate(self):
         if not hasattr(self, "session_id"):
             self.session_id = create_nonce(CHARS_HEX_LOWER, 16)
-        if not self._hasattrs("client_version", "device_id", "access_token", "user_id"):
+        if not self._hasattrs("device_id", "access_token", "user_id"):
             session = await self._twitch.get_session()
             jar = cast(aiohttp.CookieJar, session.cookie_jar)
-        if not self._hasattrs("client_version", "device_id"):
+        if not self._hasattrs("device_id"):
             async with self._twitch.request(
-                "GET", BASE_URL, headers=self.headers()
+                "GET", "https://m.twitch.tv/", headers=self.headers()
             ) as response:
                 page_html = await response.text("utf8")
                 assert page_html is not None
```

**Comment by stijndp** [comment] 2023-08-17 18:51
> EDIT: I took a quick look, and there's nothing that could cause such an increase, the usual set of data is returned. Are you sure this chart doesn't include a bunch of other things you've downloaded along the miner running?

It's filtered by app that's why I can easily get a graph for either versions.

I attached a file of 5/08 which was a high traffic date on the old version. Also 17/08 which is today so far on the 29fa220 version.
Files show very quick that almost all the extra traffic is coming from m.twitch.tv while that hostname was never used before.

[CnnHist-2023-08-17T20-39-57.csv](https://github.com/DevilXD/TwitchDropsMiner/files/12372697/CnnHist-2023-08-17T20-39-57.csv)
[CnnHist-2023-08-17T20-40-45.csv](https://github.com/DevilXD/TwitchDropsMiner/files/12372699/CnnHist-2023-08-17T20-40-45.csv)

**Comment by knuthen** [comment] 2023-08-18 08:17
@guihkx i tried your "fix" and it seems to work. Ran through the whole night and ahvent encountered any problems so far.
Also it seems that the miner picks up "not yet started" campaigns again. Don't know if its a twitch-side change or not tho.

**Comment by JourneyOver** [comment] 2023-08-18 13:40
Can confiurm that the changes that @guihkx did in the patch file does make everything start up so much quicker and it doesn't seem to get stuck on `gathering channels` at all like d5410b2 does for me at least.

**Comment by matarife123** [comment] 2023-08-18 16:20
someone could send the compiled bot pls :P

**Comment by DevilXD** [comment] 2023-08-18 18:51
I guess that's what I get for having too little time to do some proper testing. Thank you for figuring this out @guihkx.

https://github.com/DevilXD/TwitchDropsMiner/commit/e16ddeaa7b7b7c0a267590b801710dc958919959 implements these changes, hopefully. Please give the latest dev build a go and let me know if it's better now.

**Comment by JourneyOver** [comment] 2023-08-18 19:46
@DevilXD Testing the latest dev build as of right now and looks like everything is working perfectly! Starts up quickly, doesn't have the issue of getting stuck on the `gathering channels` bit and all around just seems like everything is better at the moment.

**Comment by stijndp** [comment] 2023-08-19 20:01
![image](https://github.com/DevilXD/TwitchDropsMiner/assets/29801608/6b611a22-789d-445e-9598-33d6c53b50e5)

After 20 hours of running e16ddea and mining drops it also seems to be back at normal bandwidth. No longer m.twitch.net connections transferring gibs of data every day.

**Comment by guihkx** [comment] 2023-08-24 18:55
>Would it be possible to create a "Chromium"-based cookie via headless browser and feed the miner that cookie?

Okay, but how would you login on Twitch using a headless browser (or any other remotely-controlled browser, for that matter)?

As far as I know, Twitch's integrity system (which @DevilXD literally spoke about in your quotation of his message) is currently undefeated.

In any case, right now I'd consider this issue to be fixed.

**Comment by DevilXD** [comment] 2023-08-24 19:21
@Coldblackice This was already a part of this project at some point. Here's a short history summary:

- [Chrome login flow is added to the application (Nov 1, 2022)](https://github.com/DevilXD/TwitchDropsMiner/commit/73a2a6145f83d04e268ead502dd40ce7d76f8b27)  
- [Chrome login has some issues from time to time, but standard login works again, so normal login method is reintroduced - Chrome login kept as backup (Nov 19, 2022)](https://github.com/DevilXD/TwitchDropsMiner/commit/504c6b06c0fea91bd67cd042706d18b420bd8b6f)  
- [Chrome login stopped working a few days earlier, so it's disabled to not use it anymore (Dec 7, 2022)](https://github.com/DevilXD/TwitchDropsMiner/commit/57baa4fc1eb4abae515b8c8c44d5873019e656f7)  
- [Unused Chrome dependencies are removed to slim down on the application size (Apr 23, 2023)](https://github.com/DevilXD/TwitchDropsMiner/commit/330eb4f18435730fe00f9c438d75d51937fd1095)

The gist of it is that, Chrome login/access tends to work for a while, then not work for a while, then again work for a while, then not work, and so on. Every time it stops working, someone from the Selenium project sits down, makes it work again, and pushes out an update. Updating Selenium as a dependency in a pre-compiled project is impossible, without rebuilding and re-releasing the entire thing, a way I really do not like to go with. The new mobile login option works, so lets stick to this - I can try going back to Chrome flow later, once there will be no other option.

**Comment by DevilXD** [comment] 2023-08-24 19:22
As @guihkx said, this issue is closed now. If a new issue arises, please open a new one.

**Closed by DevilXD** 2023-08-24 19:22 UTC
Labels: Bug
