### ISSUE TITLE
Fatal error encountered

### ISSUE THREAD

**Issue by skapytek** [DevilXD/TwitchDropsMiner#589] opened 2024-10-24 19:08 UTC
Hi,
im getting always this error, no matter what mode and what settings im using:

21:03:24: Fatal error encountered:
21:03:24: 
21:03:24: Traceback (most recent call last):
21:03:24:   File "main.py", line 155, in main
21:03:24:   File "twitch.py", line 587, in run
21:03:24:   File "twitch.py", line 747, in _run
21:03:24:   File "twitch.py", line 1656, in bulk_check_online
21:03:24:   File "asyncio\tasks.py", line 571, in _wait_for_one
21:03:24:   File "twitch.py", line 1387, in gql_request
21:03:24: exceptions.GQLException: [{'message': 'service error', 'path': ['channel', 'viewerDropCampaigns']}]
21:03:24: 
21:03:24: Exiting...
21:03:24: 
21:03:24: Application Terminated.
21:03:24: Close the window to exit the application.

**Comment by DevilXD** [comment] 2024-10-25 06:24
Hello,

I need to close this one as a duplicate of #590, even though it was submitted later - this is because it contains more information about the issue. You can post your traceback there if you want to, but since it's the same, you don't need to, as I'm already aware of the issue.

**Closed by DevilXD** 2024-10-25 06:24 UTC
Labels: Bug, Duplicate
