### ISSUE TITLE
Foreign language channels issue

### ISSUE THREAD

**Issue by DHowel** [DevilXD/TwitchDropsMiner#247] opened 2023-07-11 23:50 UTC
I noticed this with another game, Eternal Return, where the majority of drops are non-English letter channel based. Spanish and other languages that still have English named channels do not have this issue, only what I assume is Chinese, Taiwanese, Japanese? based where the name of the channel is in their native language but the URL is English the miner does not make the distinction that there is a difference and will lock on the drop because there's technically no channel URL named "枢木リツ" and you manually have to select an English name based channel if this occurs. By Googling this example name, their Twitch URL is https://www.twitch.tv/kururugi_ritsu but the miner I assume tries to idle https://www.twitch.tv/枢木リツ

Screenshot for a better understanding.

![image](https://github.com/DevilXD/TwitchDropsMiner/assets/62032820/243b5816-4b8b-4478-8a67-c6063d6df083)

**Comment by DevilXD** [comment] 2023-07-12 18:50
Hello o/

That's incorrect. There already is an internal distinction between "channel login" and "channel name" implemented. What you see on the channel list is the `name`` property of a channel, that's it's "display name" if one is present, "login" otherwise. "login" of a channel is a unique channel name, from which you can access the channel's page as a URL. Both of those functions are already there:

https://github.com/DevilXD/TwitchDropsMiner/blob/c2a5db8a6a22f3f7d74f45d75d78f031aa453a5d/channel.py#L146-L154

Furthermore, to progress the drop, neither the name nor login of a channel matters - the watching payload is constructed using the "channel ID" and "broadcast ID", both of which are integers. L344-345:

https://github.com/DevilXD/TwitchDropsMiner/blob/c2a5db8a6a22f3f7d74f45d75d78f031aa453a5d/channel.py#L337-L351

In places where the channels are processed and deduplicated, their comparison function only checks their unique ID:

https://github.com/DevilXD/TwitchDropsMiner/blob/c2a5db8a6a22f3f7d74f45d75d78f031aa453a5d/channel.py#L138-L144

Thus, there is no possible way to end up with two of "the same" channels on the list. What you're referring to, has to be two entirely different channels.

**Comment by DHowel** [comment] 2023-07-13 00:02
My assumption about the issue cause may be wrong, but there's still an issue. The issue is not two of the same channels on the list. The issue is drops not progressing with non-English listed channels. A few examples of channels currently in my list that will not award progress through the idler but will if I Google the names and watch their stream on Twitch are... 

루시멜로
한우비_()

Both of those are for Lost Ark

The one example above in the previous post, 枢木リツ, is another that I experienced it on. The Taiwan Sea of Thieves drops that mainly feature non-English character named streamers was another. Naraka is also a very Eastern game that features them. The idler shows progress but it does not actually progress on Twitch's side. The moment you swap to an English name it will progress either from start if you hadn't had progress yet or the point in which you were at prior. This is what I did step by step.

Googled the Overwatch 2 name in the first post(枢木リツ) to find their actual Twitch channel(https://www.twitch.tv/kururugi_ritsu)
Closed out the idler
Watched it on Twitch(https://www.twitch.tv/kururugi_ritsu)
It progresses normally on Twitch
Closed the stream
Opened the idler
Clicked Emongg
Verified new progress on Twitch matched idler progress for a few minutes
Switched back to the non-English channel(枢木リツ) in idler
Waited 30 minutes to make sure no delay between website and progress in idler(Idler showed 30 minutes of progress)
No progress on Twitch
Switched back to Emongg in idler
Progress restarted from the last progress Twitch showed
Progressed normally on Twitch as well as idler

Even while writing all of this since switching to the second Lost Ark streamer in this post so I could copy and paste the channel name, the idler shows progress, but Twitch does not.

https://seaofthieves.wiki.gg/wiki/Twitch_Drops#Taiwan_Tournament_Week_1_(June_28-July_1,_2023)

This is the first campaign I noticed it on since I woke up and it was stuck at 100% about 2 weeks ago. It did the same for the week 2 as well.

Hope this clears up confusion with wording in the first post. If not I can make a short video and post the link.

**Comment by DevilXD** [comment] 2023-07-13 20:45
> Idler showed 30 minutes of progress  
> No progress on Twitch

This is most likely due to the "progress masking" implemented in the miner, that can "pretend" to mine a drop, even though it's not actually being mined. I never implemented any limitation to the amount of time it can mask, because no practical value for it could be determined. I've explained the exact details of what's happening in #15.

The source of a drop progress update information, is caused by one of the three things: a websocket event (expected, most reliable progress info source), current drop GQL query (backup option in case no websocket event has been received), or by virtually incrementing the progress by 1 minute and restarting the timer, on a drop that's the most likely to be mined right now (progress masking). This 3rd option, called an "active drop search" in the code, is able to lie to the user about progress being made, if neither of the previous two methods were able to respond with valid data. There is a way to see which one of those three methods was used for a progress update, by running the miner in CALL verbosity mode via a `-vvv` startup option. This is an example of what you should see in the Output log afterwards: 
![obraz](https://github.com/DevilXD/TwitchDropsMiner/assets/4180725/f0822eda-df08-4220-90b1-fd7375fac5b3)

Other than the miner lying about making progress, another cause of "not being able to mine drops from specific channels", is those channels having the "drops enabled" option disabled, although we can rule that out as you said you can earn progress for the channels when watched via the browser, but not via the miner.

As far as determining what can be the cause of what you're seeing, please run the miner on your side with the `-vvv` option enabled, until the issue happens, and then post the resulting log here.

**Comment by DevilXD** [comment] 2023-09-06 19:02
Since no log was posted, I'm assuming this problem turned out not to be a problem after all. Closing.

**Closed by DevilXD** 2023-09-06 19:02 UTC
Labels: Invalid
