### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by cevlar678** [DevilXD/TwitchDropsMiner#184] opened 2023-05-06 13:47 UTC
>            Fatal error encountered:
> 
>          Traceback (most recent call last):
>             File "main.py", line 175, in <module>
>             File "asyncio\base_events.py", line 616, in run_until_complete
>             File "twitch.py", line 759, in run
>             File "twitch.py", line 812, in _run
>             File "inventory.py", line 202, in claim
>             File "inventory.py", line 120, in claim
>             File "inventory.py", line 136, in _claim
>             File "twitch.py", line 1534, in gql_request
>             exceptions.MinerException: GQL error: [{'message': 'PersistedQueryNotFound'}]
>  
>             Exiting...
>  
>             Application Terminated.
>             Close the window to exit the application.

**Comment by DevilXD** [comment] 2023-05-06 14:15
This is a duplicate of #138.

**Closed by DevilXD** 2023-05-06 14:15 UTC
Labels: Bug, Duplicate
