### ISSUE TITLE
windows defender

### ISSUE THREAD

**Issue by NaniDaFuck** [DevilXD/TwitchDropsMiner#284] opened 2023-08-23 14:18 UTC
windows defender detects the new exe as trojan 
![image](https://github.com/DevilXD/TwitchDropsMiner/assets/70827970/b9a197bf-34c2-4573-a7dd-e0165042485c)

**Comment by DevilXD** [comment] 2023-08-23 17:15
This is a duplicate of #270, #249, #217, #209 and #13. I should put out a note in the README for this.

**Closed by DevilXD** 2023-08-23 17:15 UTC
Labels: Duplicate, Help / Issue

**Comment by NaniDaFuck** [comment] 2023-08-23 17:52
got u 
i know that would happen sometimes
