### ISSUE TITLE
Everytime i run it now, used to work perfectly

### ISSUE THREAD

**Issue by xboxisdead** [DevilXD/TwitchDropsMiner#344] opened 2023-10-31 23:38 UTC
18:29:26: Fatal error encountered:
18:29:26: 
18:29:26: Traceback (most recent call last):
18:29:26:   File "main.py", line 158, in main
18:29:26:   File "twitch.py", line 764, in run
18:29:26:   File "twitch.py", line 783, in _run
18:29:26:   File "twitch.py", line 1454, in get_auth
18:29:26:   File "twitch.py", line 515, in validate
18:29:26:   File "twitch.py", line 524, in _validate
18:29:26:   File "contextlib.py", line 181, in __aenter__
18:29:26:   File "twitch.py", line 1479, in request
18:29:26:   File "gui.py", line 2050, in coro_unless_closed
18:29:26:   File "aiohttp\client.py", line 1151, in send
18:29:26:   File "aiohttp\client.py", line 562, in _request
18:29:26:   File "aiohttp\connector.py", line 540, in connect
18:29:26:   File "aiohttp\connector.py", line 901, in _create_connection
18:29:26:   File "aiohttp\connector.py", line 1178, in _create_direct_connection
18:29:26:   File "aiohttp\connector.py", line 980, in _wrap_create_connection
18:29:26:   File "asyncio\base_events.py", line 1050, in create_connection
18:29:26:   File "asyncio\base_events.py", line 961, in _connect_sock
18:29:26:   File "asyncio\proactor_events.py", line 703, in sock_connect
18:29:26: RuntimeError: await wasn't used with future
18:29:26: 
18:29:26: Exiting...
18:29:27: 
18:29:27: Application Terminated.
18:29:27: Close the window to exit the application.

**Comment by Suz1e** [comment] 2023-11-01 02:25
This is a problem with aiohttp and asyncio itself. This will happen if your Internet becomes unstable. You can try restarting it.

**Comment by DevilXD** [comment] 2023-11-01 09:33
This is a duplicate of #80.

**Closed by DevilXD** 2023-11-01 09:33 UTC
Labels: Bug, Duplicate
