### ISSUE TITLE
Windows Defender flagging this as a bitcoin miner 

### ISSUE THREAD

**Issue by VeloxAzo** [DevilXD/TwitchDropsMiner#503] opened 2024-06-28 00:29 UTC
Trojan:Win64/CoinMiner!MTB

**Comment by VeloxAzo** [comment] 2024-06-28 00:30
This is different from the other false positives I used to get so I figured it was at least worth opening a post here for discussion's sake.

**Comment by automatic-gaming** [comment] 2024-06-28 00:35
Can confirm. Windows Defender asked me to submit it as a sample a few days ago as well.

Was previously labeled as 'Trojan:Win32/Wacatac.B!ml', now 'Trojan:Win64/CoinMiner!MTB'.

**Comment by guihkx** [comment] 2024-06-28 00:41
That's just another false positive.

People concerned about this will always have the option to install the Python interpreter and run the app from source...

**Comment by matarife123** [comment] 2024-06-28 10:13
Trojan:Win32/Sabsik.FL.A!ml

**Comment by DevilXD** [comment] 2024-06-28 20:20
> This is different from the other false positives

There is literally zero difference. Someone used PyInstaller to pack up a Bitcoin miner, someone else reported it, Windows Defender got an update where it flags yet another PyInstaller binary as something it entirely isn't. Again, this is just how it works. PyInstaller is the most common, popular, and simple to use Python binary builder, which you get as first result from searching. It's just how it always been, and always will be, until this project moves to a different binary builder. I tried looking for other ones, but everything else looks too complicated for me to even begin understanding where to start with.

This miner can be flagged as anything other people use PyInstaller for. Bitcoin miner, Trojan, Worm, Adware, Ransomware, anything nasty you can imagine. If you're using a poor man's AV engine, you're gonna get just as poor results. For reference, I'm using ESET, which has never flagged PyInstaller itself or the built binary. Meanwhile, I've had to report a false positive to Bitdefender twice already, because that's what my work laptop has installed, and it's impossible to turn off there, which makes it impossible to do dev work while I'm in a delegation and after work. At least they resolve the false positives and it stops removing test binaries for a while, but it's just a matter of time before another nasty thing crops up, gets reported, and PyInstaller will once again "become a trojan" or "adware".

This is thus a duplicate of #420, #384, #335, #333, #315, #284, #270, #249, #217, #209 and #13. If anyone sees this and thinks again that it's worth bringing my attention to it - please don't, it's just a waste of time. I'd rather change the binary packaging method instead.

**Closed by DevilXD** 2024-06-28 20:20 UTC
