### ISSUE TITLE
MinerException: GQL error

### ISSUE THREAD

**Issue by Mo18flash** [DevilXD/TwitchDropsMiner#163] opened 2023-03-17 14:23 UTC
15:15:55: Fatal error encountered:
15:15:55: 
15:15:55: Traceback (most recent call last):
15:15:55:   File "main.py", line 175, in <module>
15:15:55:   File "asyncio\base_events.py", line 616, in run_until_complete
15:15:55:   File "twitch.py", line 759, in run
15:15:55:   File "twitch.py", line 812, in _run
15:15:55:   File "inventory.py", line 202, in claim
15:15:55:   File "inventory.py", line 120, in claim
15:15:55:   File "inventory.py", line 136, in _claim
15:15:55:   File "twitch.py", line 1534, in gql_request
15:15:55: exceptions.MinerException: GQL error: [{'message': 'PersistedQueryNotFound'}]

 
![Unbenannt](https://user-images.githubusercontent.com/128160515/225931958-c51d3ce4-31c6-4cfb-9f0b-fb6bb61c0eda.PNG)

**Comment by Zhanyee** [comment] 2023-03-17 16:29
Same here

**Comment by DevilXD** [comment] 2023-03-17 16:32
This is a duplicate of #138.

**Closed by DevilXD** 2023-03-17 16:32 UTC
