### ISSUE TITLE
ERROR:	Active drop search failed

### ISSUE THREAD

**Issue by maclanegamer** [DevilXD/TwitchDropsMiner#3] opened 2022-01-11 01:26 UTC
2022-01-11 00:22:11.722.707986831665:	  ERROR:	Active drop search failed
2022-01-11 00:23:09.780.9984683990479:	  ERROR:	Active drop search failed

I can't tell if it just stops working after finishing a task before starting another.
The bar stays at 100% always, Campaign Progress doesn't change.
After restarting the application, it corrects itself.

![image](https://user-images.githubusercontent.com/76525522/148864976-c39211d8-36f9-430a-9893-d2b0575f23fd.png)

**Comment by DevilXD** [comment] 2022-01-11 10:17
Hmm, that's unusual. I'll try to debug this on my end during this week, to see if I can narrow down the cause.

"Active drop search" is used when the application tries to progress the drop, but doesn't receive back an updated progress. Normally, Twitch sends back a progress update notification over the websocket, but sometimes it sends it for an incorrect drop, or doesn't send it at all (especially after switching channels), which is when the application has to "improvise" by trying to figure out which drop can be earned, and just bumping up it's `minutes_watched` by +1. This error message is shown only when this process fails to figure out said drop.

Hmm, just wondering... Did you let it run for 8+ hours straight? Cos if so, I may know why it happened.

**Comment by DevilXD** [comment] 2022-01-11 19:31
I think I found the problem. This will be fixed in `v7`, which will most likely be ready around tomorrow.

**Comment by maclanegamer** [comment] 2022-01-11 23:30
Yes I did leave it for 16 hours.

**Comment by DevilXD** [comment] 2022-01-12 18:15
This is now fixed in `v7`, available on the releases page: https://github.com/DevilXD/TwitchDropsMiner/releases

**Closed by DevilXD** 2022-01-12 18:15 UTC
