### ISSUE TITLE
Miner fatal error

### ISSUE THREAD

**Issue by BrentMifsud** [DevilXD/TwitchDropsMiner#436] opened 2024-02-13 01:39 UTC
Been seeing these fatal errors occur after running the app for a few hours.

```
12:12:02: Earned points for watching:  50, total: 640
12:13:00: Fatal error encountered:
12:13:00: 
12:13:00: Traceback (most recent call last):
12:13:00:   File "main.py", line 158, in main
12:13:00:   File "twitch.py", line 764, in run
12:13:00:   File "twitch.py", line 908, in _run
12:13:00:   File "channel.py", line 277, in update_stream
12:13:00:   File "channel.py", line 259, in get_stream
12:13:00:   File "twitch.py", line 1566, in gql_request
12:13:00: exceptions.MinerException: GQL error: [{'message': 'service error', 'path': ['channel', 'viewerDropCampaigns']}]
12:13:00: 
12:13:00: Exiting...
12:13:00: 
12:13:00: Application Terminated.
12:13:00: Close the window to exit the application.
```

**Comment by DevilXD** [comment] 2024-02-13 06:39
Duplicate of #435.

**Closed by DevilXD** 2024-02-13 06:39 UTC
Labels: Bug, Duplicate

**Comment by zelda0079** [comment] 2024-02-13 15:07
Not working today
