### ISSUE TITLE
Drops dont advance

### ISSUE THREAD

**Issue by Ruzzki** [DevilXD/TwitchDropsMiner#482] opened 2024-05-26 00:02 UTC
Self explanatory, using the program the bar in the GUI advances as if the drop is being farmed but when checked on the twitch drops inventry page, the percentage hasnt gone up.
![Screenshot 2024-05-26 030109](https://github.com/DevilXD/TwitchDropsMiner/assets/53378056/bccf57de-0896-45b0-bd7c-7ba18d76d02c)
![Screenshot 2024-05-26 030145](https://github.com/DevilXD/TwitchDropsMiner/assets/53378056/4275cab7-1e5d-424d-b80f-52349c383e9f)

**Comment by Ruzzki** [comment] 2024-05-26 00:02
(The 8% ive gotten is from me actually having the stream open)

**Comment by tngs0** [comment] 2024-05-26 00:40
the dev isn't updating anymore here's a update from a community member: https://github.com/Windows200000/TwitchDropsMiner-updated/releases/tag/v15.5.0

**Comment by Kimarnic** [comment] 2024-05-26 02:03
> the dev isn't updating anymore here's a update from a community member: https://github.com/Windows200000/TwitchDropsMiner-updated/releases/tag/v15.5.0

But the dev replied 3 hours ago, meaning that this program still gets looked at?
That one program works, thanks, but weird

**Comment by Demadig** [comment] 2024-05-26 21:26
> the dev isn't updating anymore here's a update from a community member: https://github.com/Windows200000/TwitchDropsMiner-updated/releases/tag/v15.5.0

I have the same problem with the latest Development build and Linux PyInstaller.
This updated version doesn't work as well for me (atleast the Linux PyInstaller one).
Still the same problem as OP.

**Comment by DevilXD** [comment] 2024-05-27 11:21
> this program still gets looked at?

Replying to messages, and having enough free time to do any actual development, are two completely different things.

@Ruzzki This is a duplicate of #462.

**Closed by DevilXD** 2024-05-27 11:21 UTC
Labels: Bug, Duplicate
