### ISSUE TITLE
fatal error

### ISSUE THREAD

**Issue by skapytek** [DevilXD/TwitchDropsMiner#601] opened 2024-11-03 19:13 UTC
Its the newest appimage for debian 12:

```
08:12:51 PM: Fatal error encountered:
08:12:51 PM: 
08:12:51 PM: Traceback (most recent call last):
08:12:51 PM:   File "/tmp/.mount_TwitchXpz8nH/usr/src/main.py", line 155, in main
08:12:51 PM:     await client.run()
08:12:51 PM:   File "/tmp/.mount_TwitchXpz8nH/usr/src/twitch.py", line 587, in run
08:12:51 PM:     await self._run()
08:12:51 PM:   File "/tmp/.mount_TwitchXpz8nH/usr/src/twitch.py", line 747, in _run
08:12:51 PM:     await self.bulk_check_online(acl_channels)
08:12:51 PM:   File "/tmp/.mount_TwitchXpz8nH/usr/src/twitch.py", line 1657, in bulk_check_online
08:12:51 PM:     response_list = await coro
08:12:51 PM:   File "/tmp/.mount_TwitchXpz8nH/usr/lib/python3.10/asyncio/tasks.py", line 571, in _wait_for_one
08:12:51 PM:     return f.result()  # May raise f.exception().
08:12:51 PM:   File "/tmp/.mount_TwitchXpz8nH/usr/src/twitch.py", line 1387, in gql_request
08:12:51 PM:     raise GQLException(response_json['errors'])
08:12:51 PM: exceptions.GQLException: [{'message': 'service error', 'path': ['channel', 'viewerDropCampaigns']}]
08:12:51 PM: 
08:12:51 PM: Exiting...
08:12:51 PM: 
08:12:51 PM: Application Terminated.
08:12:51 PM: Close the window to exit the application.
```

**Comment by DevilXD** [comment] 2024-11-03 21:18
Duplicate of #590.

**Closed by DevilXD** 2024-11-03 21:18 UTC
Labels: Bug, Duplicate
