### ISSUE TITLE
exceptions.MinerException: GQL error

### ISSUE THREAD

**Issue by mohcow** [DevilXD/TwitchDropsMiner#444] opened 2024-02-22 18:52 UTC
19:52:18: Fatal error encountered:
19:52:18: 
19:52:18: Traceback (most recent call last):
19:52:18:   File "main.py", line 158, in main
19:52:18:   File "twitch.py", line 768, in run
19:52:18:   File "twitch.py", line 824, in _run
19:52:18:   File "inventory.py", line 232, in claim
19:52:18:   File "inventory.py", line 138, in claim
19:52:18:   File "inventory.py", line 154, in _claim
19:52:18:   File "twitch.py", line 1570, in gql_request
19:52:18: exceptions.MinerException: GQL error: [{'message': 'service error', 'path': ['claimDropRewards']}]
19:52:18: 
19:52:18: Exiting...
19:52:19: 
19:52:19: Application Terminated.
19:52:19: Close the window to exit the application.

**Comment by DevilXD** [comment] 2024-02-22 19:50
This one has been brought up many times, just use the search engine.

Duplicate of #337 (and other "service error" cousins), tracked by #417.

**Closed by DevilXD** 2024-02-22 19:50 UTC
Labels: Bug, Duplicate
