### ISSUE TITLE
Can't find open campaigns/live channels, despite showing many campaigns/live channels.

### ISSUE THREAD

**Issue by legalcormorant** [DevilXD/TwitchDropsMiner#191] opened 2023-05-17 06:07 UTC
Plenty to pick from, can't find them or a live channel?

![11](https://github.com/DevilXD/TwitchDropsMiner/assets/133845463/b1dd1bdf-b910-4ab8-9f86-1e94dbe37e32)

![22](https://github.com/DevilXD/TwitchDropsMiner/assets/133845463/a117aac2-d2d5-4c91-a29b-4bc4e0d2b573)

**Comment by Stiphr** [comment] 2023-05-17 06:14
This is a duplicate of #189

**Closed** 2023-05-17 06:25 UTC
Labels: Bug, Duplicate
