### ISSUE TITLE
Fatal error encountered

### ISSUE THREAD

**Issue by dishophoiba** [DevilXD/TwitchDropsMiner#495] opened 2024-06-08 03:32 UTC
![image_2024-06-07_233218220](https://github.com/DevilXD/TwitchDropsMiner/assets/18474401/704e6639-680f-4036-9a32-1e74e6bf805a)

**Comment by UniqueSaltedFish** [comment] 2024-06-08 07:14
Hey guys。I have the same problem. Have you solved it？

**Comment by DealsBeam** [comment] 2024-06-08 15:32
https://github.com/DevilXD/TwitchDropsMiner/issues/493

**Comment by DevilXD** [comment] 2024-06-08 21:46
Duplicate of #493.

**Closed by DevilXD** 2024-06-08 21:46 UTC
Labels: Bug, Duplicate
