### ISSUE TITLE
Fatal Error on Startup

### ISSUE THREAD

**Issue by Skay100** [DevilXD/TwitchDropsMiner#567] opened 2024-09-25 17:28 UTC
Newest dev build form 8 hours ago, it just started popping like 20 minutes ago and doesnt work. anymore

19:26:19: Fatal error encountered:
19:26:19: 
19:26:19: Traceback (most recent call last):
19:26:19:   File "main.py", line 155, in main
19:26:19:   File "twitch.py", line 587, in run
19:26:19:   File "twitch.py", line 747, in _run
19:26:19:   File "twitch.py", line 1656, in bulk_check_online
19:26:19:   File "asyncio\tasks.py", line 571, in _wait_for_one
19:26:19:   File "twitch.py", line 1387, in gql_request
19:26:19: exceptions.GQLException: [{'message': 'service error', 'path': ['channel', 'viewerDropCampaigns']}]
19:26:19: 
19:26:19: Exiting...
19:26:19: 
19:26:19: Application Terminated.
19:26:19: Close the window to exit the application.

Did full reinstall just in case, didn't help.

**Comment by Skay100** [comment] 2024-09-25 17:36
It starts working for few minutes and then stops again fully

**Comment by vexxic** [comment] 2024-09-25 19:36
Having the same issue
![image](https://github.com/user-attachments/assets/60a4133c-1331-4f27-9627-965aa15902d6)
![image](https://github.com/user-attachments/assets/bd9d1f80-f939-43af-ab8f-50a18e1d0b74)

**Comment by DevilXD** [comment] 2024-09-25 21:51
Duplicate of #415. Also see: #417.

**Closed by DevilXD** 2024-09-25 21:51 UTC
Labels: Bug, Duplicate
