### ISSUE TITLE
Fatal error encountered

### ISSUE THREAD

**Issue by yunmgr** [DevilXD/TwitchDropsMiner#272] opened 2023-08-13 08:19 UTC
16:15:52: Fatal error encountered:
16:15:52: 
16:15:52: Traceback (most recent call last):
16:15:52:   File "main.py", line 175, in <module>
16:15:52:   File "asyncio\base_events.py", line 616, in run_until_complete
16:15:52:   File "twitch.py", line 759, in run
16:15:52:   File "twitch.py", line 778, in _run
16:15:52:   File "twitch.py", line 1449, in get_auth
16:15:52:   File "twitch.py", line 512, in validate
16:15:52:   File "twitch.py", line 521, in _validate
16:15:52:   File "contextlib.py", line 171, in __aenter__
16:15:52:   File "twitch.py", line 1474, in request
16:15:52:   File "gui.py", line 1946, in coro_unless_closed
16:15:52:   File "aiohttp\client.py", line 1125, in send
16:15:52:   File "aiohttp\client.py", line 536, in _request
16:15:52:   File "aiohttp\connector.py", line 540, in connect
16:15:52:   File "aiohttp\connector.py", line 901, in _create_connection
16:15:52:   File "aiohttp\connector.py", line 1175, in _create_direct_connection
16:15:52:   File "aiohttp\connector.py", line 980, in _wrap_create_connection
16:15:52:   File "asyncio\base_events.py", line 1010, in create_connection
16:15:52:   File "asyncio\base_events.py", line 924, in _connect_sock
16:15:52:   File "asyncio\proactor_events.py", line 702, in sock_connect
16:15:52: RuntimeError: await wasn't used with future
16:15:52: 
16:15:52: Exiting...
16:15:53: 
16:15:53: Application Terminated.
16:15:53: Close the window to exit the application.
how to fix it？

**Comment by DevilXD** [comment] 2023-08-13 12:48
This is a duplicate of #80.

**Closed by DevilXD** 2023-08-13 12:48 UTC
Labels: Bug, Duplicate
