### ISSUE TITLE
Want to add auto refresh drop list

### ISSUE THREAD

**Issue by coolingziyu** [DevilXD/TwitchDropsMiner#353] opened 2023-11-04 16:21 UTC
Hope to increase the function of automatically or regularly refresh the treasure list, hang treasure for a long time, can not update the treasure link, some treasure can not be obtained

**Comment by DevilXD** [comment] 2023-11-04 21:42
Hello.

I'm trying to determine what are you trying to say, but it all sounds like a part of #301, so this is probably a duplicate of an already existing issue, that is being worked on. If I'm mistaken, please reply what you had in mind here, and I'll reopen the issue.

**Closed by DevilXD** 2023-11-04 21:42 UTC
Labels: Bug, Duplicate

**Comment by coolingziyu** [comment] 2023-11-05 13:46
Seems to be different, what I want is a regular refresh of the treasure list function, not a fake viewing issue

**Comment by DevilXD** [comment] 2023-11-06 18:57
This feature already exists, and does what it's supposed to, by refreshing the inventory when needed, or every up to 60 minutes. If it fails to refresh the campains at the correct time, it is because Twitch has decided to change the entire drops system recently, and most of the cases that worked previously, don't work anymore. That's constantly being taken care of under the #301 critical issue, so there's no need to create additional ones.
