### ISSUE TITLE
Fatal error Traceback 

### ISSUE THREAD

**Issue by maclanegamer** [DevilXD/TwitchDropsMiner#1] opened 2022-01-09 21:40 UTC
**This happens after login in.**

Fatal error encountered:

Traceback (most recent call last):
  File "twitch.py", line 102, in start
  File "asyncio\base_events.py", line 616, in run_until_complete
  File "twitch.py", line 173, in _run
  File "twitch.py", line 653, in fetch_inventory
TypeError: 'NoneType' object is not iterable

Exiting...

Application Terminated.
Close the window to exit the application.

**Comment by DevilXD** [comment] 2022-01-10 09:22
Hello =)

I see. I expect the cause of it is related to there being no available campaigns when the inventory is fetched, and the code expects an empty list while `None` is returned instead. This should be now fixed in `v6`, available now on the releases page: https://github.com/DevilXD/TwitchDropsMiner/releases

Please note that you'll need to activate the campaign manually, before the application can begin mining. I've added a "Troubleshooting" section to the README to aid you in this process: https://github.com/DevilXD/TwitchDropsMiner/blob/master/README.md

**Closed by DevilXD** 2022-01-10 09:22 UTC
