### ISSUE TITLE
App not work

### ISSUE THREAD

**Issue by dungtranhoang** [DevilXD/TwitchDropsMiner#258] opened 2023-07-24 04:07 UTC
Hi
Seem like app not work correctly
Or maybe twitch got some problems on this one?
![image](https://github.com/DevilXD/TwitchDropsMiner/assets/124852753/43d0b8e2-ac02-4097-b303-aaea47bd87cb)

App said that progress is 51% 
But on https://www.twitch.tv/drops/inventory
Remain only 13%
![image](https://github.com/DevilXD/TwitchDropsMiner/assets/124852753/fca031d5-7409-40bd-ae73-4f543baa7b4c)

**Comment by DevilXD** [comment] 2023-07-24 17:32
This is a duplicate of #247. Please refer to instructions there, and reply there as well, to resolve your issue,

**Closed by DevilXD** 2023-07-24 17:32 UTC
Labels: Bug, Duplicate

**Comment by dungtranhoang** [comment] 2023-07-25 02:18
> This is a duplicate of #247. Please refer to instructions there, and reply there as well, to resolve your issue,

#247 is about language, what I mention here is the progress bar not the same as the progress bar in app
Check again the image @DevilXD

**Comment by DevilXD** [comment] 2023-07-25 18:01
@dungtranhoang No, this is the exact same issue - the miner reporting one progress while the website says something else, "Foreign language" actually has nothing to do with #247, this was what OP of that issue thinks is happening, while my first response there is literally proving them wrong on it. I think this issue being a duplicate is clear now.

With the above being clear, I'm still asking you to refer to the exact steps listed in #247, as well as continuing this discussion there. This issue is already closed as a duplicate.
