### ISSUE TITLE
error multiversus build 3b4923a

### ISSUE THREAD

**Issue by matarife123** [DevilXD/TwitchDropsMiner#594] opened 2024-10-28 16:36 UTC
17:36:06: Mirando el canal: MultiVersus
17:36:06: ERROR: Exception in _watch_loop task
17:36:06: Traceback (most recent call last):
17:36:06:   File "utils.py", line 132, in wrapper
17:36:06:   File "twitch.py", line 888, in _watch_loop
17:36:06:   File "channel.py", line 380, in send_watch
17:36:06:   File "contextlib.py", line 199, in __aenter__
17:36:06:   File "twitch.py", line 1313, in request
17:36:06:   File "gui.py", line 2203, in coro_unless_closed
17:36:06:   File "aiohttp\client.py", line 1343, in send
17:36:06:   File "aiohttp\client.py", line 592, in _request
17:36:06: aiohttp.client_exceptions.InvalidUrlClientError: %5B%7B%22url%22:%22/api/channel/hls/multiversus.m3u8?sig=7e645729f0d4e8fc0c2383e6b0ac620cf31545e2%5Cu0026token=%7B%22adblock%22:false,%22authorization%22:%7B%22forbidden%22:false,%22reason%22:%22%22%7D,%22blackout_enabled%22:false,%22channel%22:%22multiversus%22,%22channel_id%22:735931830,%22chansub%22:%7B%22restricted_bitrates%22:%5B%5D,%22view_until%22:1924905600%7D,%22ci_gb%22:true,%22geoblock_reason%22:%22content_geoblocked%22,%22device_id%22:%22tJPdnv8zKC1HrhZUfloLFuEecrxZWe9o%22,%22expires%22:1730134563,%22extended_history_allowed%22:false,%22game%22:%22%22,%22hide_ads%22:false,%22https_required%22:true,%22mature%22:false,%22partner%22:false,%22platform%22:%22web%22,%22player_type%22:%22site%22,%22private%22:%7B%22allowed_to_view%22:true%7D,%22privileged%22:false,%22role%22:%22%22,%22server_ads%22:true,%22show_ads%22:true,%22subscriber%22:false,%22turbo%22:false,%22user_id%22:233324811,%22user_ip%22:%2237.134.0.208%22,%22version%22:2%7D%22,%22error%22:%22Content+Restricted+In+Region%22,%22error_code%22:%22content_geoblocked%22,%22type%22:%22error%22%7D%5D
17:36:06: Saliendo...

**Comment by DevilXD** [comment] 2024-10-28 16:49
Duplicate of #586.

**Closed by DevilXD** 2024-10-28 16:49 UTC
