### ISSUE TITLE
App Quit Working - No longer getting credit for time watched

### ISSUE THREAD

**Issue by Maligmus** [DevilXD/TwitchDropsMiner#479] opened 2024-05-24 23:36 UTC
The app thinks that it is working, but the time is not registering on twitch. It is only going up if i actually log in on the browser and watch.

<img width="341" alt="image" src="https://github.com/DevilXD/TwitchDropsMiner/assets/170773291/223a64ca-4c0a-407e-b49b-0f08d9940292">

<img width="1072" alt="image" src="https://github.com/DevilXD/TwitchDropsMiner/assets/170773291/e953410a-e9b9-403a-a733-2c26267bce01">

It has been working flawlessly for 6+ months. last worked 16 days ago for me.

Troubleshooting steps:
Logged out & back in on twitch
downloaded newest Dev build and did a clean install. (deleted all old files cache, json, setting, etc)
Installed on a different PC
Tried with & w/o VPN

**Comment by dgnzls77** [comment] 2024-05-24 23:47
Unfortunately, this is happening to me as well. The watch time will get to 100% and instead of claiming, the time restarts.

**Comment by Maligmus** [comment] 2024-05-24 23:52
> Unfortunately, this is happening to me as well. The watch time will get to 100% and instead of claiming, the time restarts.

It's looking like Twitch found a way to block it.

**Comment by Sodaly1318** [comment] 2024-05-25 04:58
#462

**Comment by DevilXD** [comment] 2024-05-25 21:26
This is a duplicate of #462.

**Closed by DevilXD** 2024-05-25 21:26 UTC
