### ISSUE TITLE
GQLException ERROR on Start

### ISSUE THREAD

**Issue by jabibamman** [DevilXD/TwitchDropsMiner#649] opened 2024-12-30 13:06 UTC
When loading the app 
```log
14:05:38: Fatal error encountered:
14:05:38: 
14:05:38: Traceback (most recent call last):
14:05:38:   File "main.py", line 155, in main
14:05:38:   File "twitch.py", line 587, in run
14:05:38:   File "twitch.py", line 747, in _run
14:05:38:   File "twitch.py", line 1660, in bulk_check_online
14:05:38:   File "asyncio\tasks.py", line 571, in _wait_for_one
14:05:38:   File "twitch.py", line 1390, in gql_request
14:05:38: exceptions.GQLException: [{'message': 'service error', 'path': ['channel', 'viewerDropCampaigns']}]
14:05:38: 
14:05:38: Exiting...
14:05:38: 
14:05:38: Application Terminated.
14:05:38: Close the window to exit the application.
```

**Comment by Evgencheg** [comment] 2024-12-30 13:23
same error

**Comment by NorskNoobing** [comment] 2024-12-30 13:36
+1

**Comment by DevilXD** [comment] 2024-12-30 13:50
This is a duplicate of #590.

**Closed by DevilXD** 2024-12-30 13:50 UTC
Labels: Bug, Duplicate
