### ISSUE TITLE
"Waiting for an ONLINE Channel" despite channels being online

### ISSUE THREAD

**Issue by christianb4** [DevilXD/TwitchDropsMiner#242] opened 2023-07-01 06:13 UTC
![twitchdrops](https://github.com/DevilXD/TwitchDropsMiner/assets/60160063/ecfc4980-8439-43f3-9917-59d594760c7f)
I have all the games added to the priority list that I would want to farm drops for. My twitch account is logged into and is connected to wargaming which would be for the world of tanks drops. Despite all that, it doesn't seem to show that those channels have drops enabled (what I assume the gift icon is for) and that they are not online (says offline in output). I've reloaded and restarted the application to no avail so I'm a bit lost on what the problem is.

**Comment by DevilXD** [comment] 2023-07-01 18:09
This is most likely a duplicate of #189. Please refer to there for more information and a solution.

**Closed by DevilXD** 2023-07-01 18:09 UTC
Labels: Bug, Duplicate
