### ISSUE TITLE
Watching Stream But not counting

### ISSUE THREAD

**Issue by MehmetCanWT** [DevilXD/TwitchDropsMiner#327] opened 2023-10-19 12:27 UTC
i run program on windows server its watching streams but when i check later its stuck on 0 0 0 time remaining and no drop

**Comment by zelda0079** [comment] 2023-10-19 12:36
https://github.com/DevilXD/TwitchDropsMiner/issues/326
I think it is same issue.

**Comment by MehmetCanWT** [comment] 2023-10-19 12:38
yeah same

**Comment by MehmetCanWT** [comment] 2023-10-19 12:38
i tried v15 but it's not even shows the games just rainbow 6 and smite and v16 is not count progress

**Comment by MehmetCanWT** [comment] 2023-10-19 15:02
![Screenshot_20231019-180032_Microsoft Remote Desktop](https://github.com/DevilXD/TwitchDropsMiner/assets/52177084/56fce248-6d89-4182-af8e-b4e88142b66c)

stuck like this

**Comment by zelda0079** [comment] 2023-10-19 15:27
> ![Screenshot_20231019-180032_Microsoft Remote Desktop](https://user-images.githubusercontent.com/52177084/276660147-56fce248-6d89-4182-af8e-b4e88142b66c.png)
> 
> stuck like this

wait to fix
I am using https://chrome.google.com/webstore/detail/automatic-twitch-drops-mo/kfhgpagdjjoieckminnmigmpeclkdmjm and idle twitch drop in broswer.

**Comment by DevilXD** [comment] 2023-10-19 18:20
This is a duplicate of #301.

**Closed by DevilXD** 2023-10-19 18:20 UTC
Labels: Bug, Duplicate
