### ISSUE TITLE
exceptions.GQLException: [{'message': 'service error', 'path': ['claimDropRewards']}]

### ISSUE THREAD

**Issue by m7zr** [DevilXD/TwitchDropsMiner#604] opened 2024-11-09 03:58 UTC
05:15:17: Fatal error encountered:
05:15:17: 
05:15:17: Traceback (most recent call last):
05:15:17:   File "main.py", line 155, in main
05:15:17:   File "twitch.py", line 587, in run
05:15:17:   File "twitch.py", line 648, in _run
05:15:17:   File "inventory.py", line 259, in claim
05:15:17:   File "inventory.py", line 142, in claim
05:15:17:   File "inventory.py", line 158, in _claim
05:15:17:   File "twitch.py", line 1387, in gql_request
05:15:17: exceptions.GQLException: [{'message': 'service error', 'path': ['claimDropRewards']}]
05:15:17: 
05:15:17: Exiting...
05:15:18: 
05:15:18: Application Terminated.
05:15:18: Close the window to exit the application.

**Comment by DevilXD** [comment] 2024-11-09 08:04
Duplicate of #590.

**Closed by DevilXD** 2024-11-09 08:04 UTC
Labels: Bug, Duplicate
