### ISSUE TITLE
If the cookies.jar file is 0bytes the application crashes.

### ISSUE THREAD

**Issue by xrtxn** [DevilXD/TwitchDropsMiner#204] opened 2023-05-20 10:23 UTC
I'm not sure how but the cookies.jar file became corrupted and the application crashes in this case. A very simple solution could be that we just delete/ignore the file.

<details>
<summary>Crash log</summary>

12:19:57: Fatal error encountered:
12:19:57: 
12:19:57: Traceback (most recent call last):
12:19:57:   File "/hdd/twitch_drops_miner/main.py", line 170, in <module>
12:19:57:     loop.run_until_complete(client.run())
12:19:57:   File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
12:19:57:     return future.result()
12:19:57:            ^^^^^^^^^^^^^^^
12:19:57:   File "/hdd/twitch_drops_miner/twitch.py", line 764, in run
12:19:57:     await self._run()
12:19:57:   File "/hdd/twitch_drops_miner/twitch.py", line 783, in _run
12:19:57:     auth_state = await self.get_auth()
12:19:57:                  ^^^^^^^^^^^^^^^^^^^^^
12:19:57:   File "/hdd/twitch_drops_miner/twitch.py", line 1454, in get_auth
12:19:57:     await self._auth_state.validate()
12:19:57:   File "/hdd/twitch_drops_miner/twitch.py", line 517, in validate
12:19:57:     await self._validate()
12:19:57:   File "/hdd/twitch_drops_miner/twitch.py", line 523, in _validate
12:19:57:     session = await self._twitch.get_session()
12:19:57:               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
12:19:57:   File "/hdd/twitch_drops_miner/twitch.py", line 661, in get_session
12:19:57:     cookie_jar.load(COOKIES_PATH)
12:19:57:   File "/hdd/twitch_drops_miner/env/lib/python3.11/site-packages/aiohttp/cookiejar.py", line 103, in load
12:19:57:     self._cookies = pickle.load(f)
12:19:57:                     ^^^^^^^^^^^^^^
12:19:57: EOFError: Ran out of input
12:19:57: 
12:19:57: Exiting...
12:19:58: 
12:19:58: Application Terminated.
12:19:58: Close the window to exit the application.

</details>

**Comment by DevilXD** [comment] 2023-05-20 10:54
Hello o/

This is a duplicate of #187. The original report includes only the image cache mapping file corruption, but the following comment also mentions cookie file corruption, so this is already known. Just delete and recreate the cookie file to solve this for now.

**Closed by DevilXD** 2023-05-20 10:54 UTC
Labels: Bug, Duplicate
