### ISSUE TITLE
ERROR: Exception in task

### ISSUE THREAD

**Issue by IRhoAias** [DevilXD/TwitchDropsMiner#457] opened 2024-04-27 07:39 UTC
`04:38:35: Watching: EXTREMEBREAKER1
04:38:35: ERROR: Exception in task
04:38:35: Traceback (most recent call last):
04:38:35:   File "utils.py", line 139, in wrapper
04:38:35:   File "twitch.py", line 1046, in _watch_loop
04:38:35:   File "channel.py", line 387, in send_watch
04:38:35:   File "channel.py", line 237, in get_spade_url
04:38:35: exceptions.MinerException: Error while spade_url extraction: step #1`

this happened to me on thursday and i ignored it but i realized that i didn't farm anything. now i am worried because i can't do it manually due to work i leave the error and a picture of the same error in case it is necessary.
![image](https://github.com/DevilXD/TwitchDropsMiner/assets/88462069/a2d23b37-f03d-4f89-b193-1f69695a43ee)

**Comment by IRhoAias** [comment] 2024-04-27 07:50
04:38:35: Watching: EXTREMEBREAKER1
04:38:35: ERROR: Exception in task
04:38:35: Traceback (most recent call last):
04:38:35:   File "utils.py", line 139, in wrapper
04:38:35:   File "twitch.py", line 1046, in _watch_loop
04:38:35:   File "channel.py", line 387, in send_watch
04:38:35:   File "channel.py", line 237, in get_spade_url
04:38:35: exceptions.MinerException: Error while spade_url extraction: step #1
Sri This is the error

**Comment by DevilXD** [comment] 2024-04-27 09:58
Hello o/

The error signifies the internal watch loop dying on a spade URL extraction step. Without a functional watch loop, no watch events will be sent to Twitch to advance the drops, and the only way to recover from this is to restart the application.

The error itself could be a one-off occurrence, so I'm more or less waiting for more reports first. For now, just restart to get it fixed.

**Comment by EmiMathesi** [comment] 2024-04-27 12:32
Hi. Since last night, I also have this error with a 1 in 20 chance. Only the re-creation of cookies.json helps

**Comment by EmiMathesi** [comment] 2024-04-27 12:32
Hi. Since last night, I also have this error with a 1 in 20 chance. Only the re-creation of cookies.json helps

**Comment by EmiMathesi** [comment] 2024-04-27 12:57
![image](https://github.com/DevilXD/TwitchDropsMiner/assets/126239039/037c4bd9-6504-4d5a-9ede-ac50464e342e)

**Comment by EmiMathesi** [comment] 2024-04-27 13:06
![image](https://github.com/DevilXD/TwitchDropsMiner/assets/126239039/d6452021-005b-4094-8d46-0ea4f3c32091)

18:06:15: Watching: w0n23
18:06:15: ERROR: Exception in task
18:06:15: Traceback (most recent call last):
18:06:15:   File "C:\Users\MATHESI\Desktop\TwitchDropsMiner-master\utils.py", line 139, in wrapper
18:06:15:     await afunc(*args, **kwargs)
18:06:15:   File "C:\Users\MATHESI\Desktop\TwitchDropsMiner-master\twitch.py", line 1046, in _watch_loop
18:06:15:     succeeded: bool = await channel.send_watch()
18:06:15:                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
18:06:15:   File "C:\Users\MATHESI\Desktop\TwitchDropsMiner-master\channel.py", line 387, in send_watch
18:06:15:     self._spade_url = await self.get_spade_url()
18:06:15:                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
18:06:15:   File "C:\Users\MATHESI\Desktop\TwitchDropsMiner-master\channel.py", line 237, in get_spade_url
18:06:15:     raise MinerException("Error while spade_url extraction: step #1")
18:06:15: exceptions.MinerException: Error while spade_url extraction: step #1

**Comment by EmiMathesi** [comment] 2024-04-27 13:16
Restarting doesn't help, changing the game doesn't help either
![image](https://github.com/DevilXD/TwitchDropsMiner/assets/126239039/ded6b430-a02e-42bd-9271-688d41a9a09e)

**Comment by IRhoAias** [comment] 2024-04-27 22:12
in my particular case I always get the same error and deleting cookies.jar does not fix the error.
![image](https://github.com/DevilXD/TwitchDropsMiner/assets/88462069/19693f26-f9d8-4805-9998-b125f4c90a40)

**Comment by DevilXD** [comment] 2024-04-27 22:31
Alright, well, I'll look into the potential cause of this further.

**Comment by DevilXD** [comment] 2024-04-28 11:13
I've looked into it, and I'm unable to reproduce this on my end. I've checked these three affected channels: "EXTREMEBREAKER1", "w0n23" and "LVTHalo", all of them resolving properly.

This may or may not be something Twitch is currently testing, and only a limited subset of users will be affected by. Either way, I'm unable to diagnose the issue for now.

**Comment by EmiMathesi** [comment] 2024-04-28 11:24
@DevilXD  Hi, maybe I should send you cookies.jar of the problematic account for diagnosis?

**Comment by DevilXD** [comment] 2024-04-28 19:38
@EmiMathesi Putting your cookies file into public internet gives anyone who takes it unlimited access to your Twitch account. Your account may have already been compromised, so I'd suggest you to quickly change your password, hopefully while you still can. I've removed the file link from your comment.

I've never asked, nor will use, anyone else's cookies file to diagnose the issue, because I definitely don't want to access somebody else's account, specifically from my own IP address and location. If I can't diagnose this issue now, then we all just need to wait until I'm able to. That's all.

**Comment by EmiMathesi** [comment] 2024-04-28 20:03
Of course, I thought it would speed up the process. Don't worry about the account, I don't need it and it's completely empty.

**Comment by mgbeck002** [comment] 2024-04-29 19:28
I had a similar issue. I was able to work around it by changing the regex
`r'src="(https://static\.twitchcdn\.net/config/settings\.[0-9a-f]{32}\.js)"'
to 
` r'src="(https://assets\.twitch\.tv/config/settings\.[0-9a-f]{32}\.js)"'`

in channel.py since it seems the link changed at least for some users.

**Comment by DevilXD** [comment] 2024-04-30 08:08
Interesting. I've implemented this finding in https://github.com/DevilXD/TwitchDropsMiner/commit/ab76491ecc26c6527da3aa5ccaefdc9a563fdfd8, please give it a try and see if it helped resolve this issue.

**Comment by mgbeck002** [comment] 2024-05-13 03:01
> Interesting. I've implemented this finding in [ab76491](https://github.com/DevilXD/TwitchDropsMiner/commit/ab76491ecc26c6527da3aa5ccaefdc9a563fdfd8), please give it a try and see if it helped resolve this issue.

That worked for me.

**Comment by DevilXD** [comment] 2024-05-13 17:50
I'm assuming this is fixed now then.

**Closed by DevilXD** 2024-05-13 17:50 UTC
Labels: Bug
