### ISSUE TITLE
Constantly switches channels

### ISSUE THREAD

**Issue by chillzxcss** [DevilXD/TwitchDropsMiner#537] opened 2024-08-09 08:44 UTC
![Screenshot_15](https://github.com/user-attachments/assets/d8b47a04-86cc-4f5b-b0bd-8810516da996)

Constantly switches channels, in 10 hours not even 1/4 of the drops are counted, why is that

**Comment by Br1ghtqq** [comment] 2024-08-09 10:56
i have the same problem with this version 
![Screenshot 2024-08-09 125549](https://github.com/user-attachments/assets/55f3929f-0f64-45c3-badb-a79c0687bffb)

**Comment by DevilXD** [comment] 2024-08-09 11:17
Do these channels stream different games from the priority list, or it's all the same game?

**Comment by Br1ghtqq** [comment] 2024-08-09 11:28
same game

**Comment by DevilXD** [comment] 2024-08-09 15:29
I am unable to reproduce the issue. When I let the miner set several channels ONLINE at once for the same game, only the first channel causes a switch, rest of them doesn't do so:
![picture1](https://github.com/user-attachments/assets/59451f2f-17f8-4baa-8deb-fed2178eaf4a)

Some deeper analysis of the initial report suggests this is intended behavior:
![picture2](https://github.com/user-attachments/assets/71d89a2e-6fe0-4907-a743-e92cebf2f627)

This happens because now, ACL channels are not set online immediately, before being added to the channels list. Instead, we let the websocket viewers count update trigger the channel going ONLINE. To reduce the possibility of an error, there's an additional channel state between being triggered to set ONLINE, and actually being set ONLINE, called "pending ONLINE" - this is signified by an hourglass emoji and "still OFFLINE" description on the channel status: `⏳ OFFLINE`. This state lasts for 2 minutes, that the miner has to wait through first, and only then it queries the actual channel status, and either reverts back to proper `❌ OFFLINE`, or proper `✓ ONLINE`.

So what happens is: 

- There's a game that has at least two campaigns - one that has an ACL list specified, so only the ACL channels can progress it, and another that has no ACL specified, meaning that any channel playing the game can progress it.
- The campaign with ACL can only be progress by one of the ACL channels, but the other campaign can be progressed by any channel, so the miner tries to watch the ACL channels, because they can progress both campaigns - any other channel can only progress one of the campaigns, so if both are ONLINE, the miner will try to switch to the ACL one.
- Due to recent changes, all ACL channels start as OFFLINE after a reload, then gradually come ONLINE 2m later.
- A reload happens and the channels list is loaded. In case none of the ACL channels would ever come ONLINE (and the first campaign wouldn't be progressed), the miner adds up to 30 live channels to be able to progress the other campaign - these channels always start as ONLINE, so one of them is immediately selected when reload finishes.
- 2m later, one of the ACL channels turns out to actually be ONLINE, and since those can progress both campaigns, a switch happens.
- This cycle of "reload -> watching live channel -> watching ACL channel" will repeat every hour, for every reload.
- This is intended behavior, and shouldn't cause the miner to stop mining.

If you are not getting any mining progress, the issue lays elsewhere. Restarting the miner might help.

**Comment by Br1ghtqq** [comment] 2024-08-09 15:54
idk but it keeps switching from one channel to another was finished dropping qaixx switched to oilrats and out of nowhere its switched to another channel  
![Screenshot 2024-08-09 175123](https://github.com/user-attachments/assets/ff26faaa-838c-4a8a-8d12-ec10a8ec2c81)
![Screenshot 2024-08-09 175158](https://github.com/user-attachments/assets/1dcd6475-cf1c-45b7-97d2-3b6e40199e8c)

**Comment by DevilXD** [comment] 2024-08-09 16:20
> out of nowhere its switched to another channel

That's where the reload happens. Reloads happened at these times from your picture:

- 15:48
- 16:48
- 17:48

Please notice that there's exactly one hour between them, confirming they're indeed the reloads in question, since they happen every up to 1 hour. At the end of each reload, the miner will pick a channel to watch, one from the available ones at the time - and since ACL channels start OFFLINE, none of them will be picked. Instead the miner will pick one of the live channels for another campaign at first. Then, 2 minutes later (after each reload), an ACL channel goes ONLINE and gets switched to. Again, everything is working as intended, and as I've described in my previous message.

This pattern will repeat for each reload:

```py
# reload happens here
Time+0m: Watching ABC.
Time+2m: XYZ goes ONLINE, switching...
Time+2m: Watching XYZ.

```

![picture](https://github.com/user-attachments/assets/51df6207-a9da-426b-b9f8-f34af504c4fd)

I'm closing this issue, since this is not a bug. Once the GQL query that sets ACL channels ONLINE is fixed (per https://github.com/DevilXD/TwitchDropsMiner/pull/531#issuecomment-2274283697), this will stop happening and go back to how it was before.

**Closed by DevilXD** 2024-08-09 16:20 UTC
Labels: Bug

**Comment by Br1ghtqq** [comment] 2024-08-09 16:31
alright thanks for the explanation didnt know it was intended cuz the previous version didnt do it
