### ISSUE TITLE
Fatal error encountered

### ISSUE THREAD

**Issue by MrPryor** [DevilXD/TwitchDropsMiner#368] opened 2023-11-21 00:49 UTC
19:47:59: Fatal error encountered:
19:47:59: 
19:47:59: Traceback (most recent call last):
19:47:59:   File "main.py", line 174, in <module>
19:47:59:   File "asyncio\base_events.py", line 647, in run_until_complete
19:47:59:   File "twitch.py", line 768, in run
19:47:59:   File "twitch.py", line 810, in _run
19:47:59:   File "twitch.py", line 1601, in fetch_inventory
19:47:59:   File "twitch.py", line 1602, in <dictcomp>
19:47:59:   File "utils.py", line 88, in timestamp
19:47:59:   File "_strptime.py", line 568, in _strptime_datetime
19:47:59:   File "_strptime.py", line 349, in _strptime
19:47:59: ValueError: time data '2023-11-20T23:42:43.148Z' does not match format '%Y-%m-%dT%H:%M:%SZ'
19:47:59: 
19:47:59: Exiting...
19:47:59: 
19:47:59: Application Terminated.
19:47:59: Close the window to exit the application.

**Comment by DevilXD** [comment] 2023-11-21 19:08
Duplicate of #345. Please use search before reporting anything.

**Closed by DevilXD** 2023-11-21 19:08 UTC
Labels: Bug, Duplicate
