### ISSUE TITLE
Option to choose channel

### ISSUE THREAD

**Issue by psyalemao** [DevilXD/TwitchDropsMiner#114] opened 2023-01-07 04:37 UTC
Hello, first of all I would like to say that I appreciate your work and effort on this project and I really mean that, as I know that it takes a lot of patience and dedication to maintain a project.

I wonder if it would be possible to select a certain channel to farm twitch points. The reason is that some channels allows to exchange twitch points and use in streamelements.

I'm not making a request or demanding anything, it's just an idea or suggestion.

Best regards!

**Comment by DevilXD** [comment] 2023-01-07 08:44
This is a duplicate of #70. Please also see #105 for more context if you'd want to.

**Closed by DevilXD** 2023-01-07 08:44 UTC
Labels: Duplicate, Enhancement
