### ISSUE TITLE
Crash/Termination after drop claim

### ISSUE THREAD

**Issue by scryptio** [DevilXD/TwitchDropsMiner#16] opened 2022-05-13 21:10 UTC
Hey there, got this error today. 

```
Claimed drop: Tiger Blood Nameplate (1/1)
2022-05-13 21:36:34.212:	  ERROR:	Fatal error encountered:
Traceback (most recent call last):
  File "main.py", line 157, in <module>
  File "asyncio\base_events.py", line 616, in run_until_complete
  File "twitch.py", line 292, in run
  File "channel.py", line 249, in check_online
  File "channel.py", line 233, in get_stream
  File "twitch.py", line 857, in gql_request
  File "aiohttp\client_reqrep.py", line 1103, in json
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://gql.twitch.tv/gql')
Fatal error encountered:

Traceback (most recent call last):
  File "main.py", line 157, in <module>
  File "asyncio\base_events.py", line 616, in run_until_complete
  File "twitch.py", line 292, in run
  File "channel.py", line 249, in check_online
  File "channel.py", line 233, in get_stream
  File "twitch.py", line 857, in gql_request
  File "aiohttp\client_reqrep.py", line 1103, in json
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://gql.twitch.tv/gql')

Exiting...

Application Terminated.
Close the window to exit the application.
```

**Comment by DevilXD** [comment] 2022-05-14 13:55
Hello o/

Hmm, I see. It seems like Twitch has returned an HTML payload from an endpoint that normally returns JSON only. My suspicion is that this could be caused by the Twitch's webpage temporarily becoming unavailable, causing cloudflare to return one of their "destination website is not available" error pages, that are returned as normal HTML.

The resolution for this is quite easy, as all I have to do is treat this condition as a connection problem, that'll trigger the retry code instead of crashing. This issue should be resolved in `v12`, and this issue will remain open until that happens.

**Comment by DevilXD** [comment] 2022-09-03 17:05
This should be now fixed as of `v12`: https://github.com/DevilXD/TwitchDropsMiner/releases

**Closed by DevilXD** 2022-09-03 17:05 UTC
Labels: Bug, Solved for the next release
