### ISSUE TITLE
Missing Campaign for Final Fantasy XIV Dawntrail

### ISSUE THREAD

**Issue by Artanisx** [DevilXD/TwitchDropsMiner#512] opened 2024-07-05 07:42 UTC
Hey,
First of all love your program, thank you very much!
Now onto the problem.
It seems the currently active campaigns for Final Fantasy XIV Dawntrail are not picked up by the miner.
![image](https://github.com/DevilXD/TwitchDropsMiner/assets/7050265/af77e44a-f1f4-4e9d-88ed-4d7b572784de)

They do not show up in the Settings / Priority page, nor in the Inventory (with any checkboxes). I tried already to re-login and close and reopen the app. 

Any chance you can look into this problem?

Thanks :-)

**Comment by Artanisx** [comment] 2024-07-05 08:51
It might be Square's enix fault as they might have done something weird. If you do watch the streams on a browser, you don't see any progress in the Inventory (it doesn't even show up), but if you do watch enough you'll get a notification with a code.

**Comment by DevilXD** [comment] 2024-07-05 14:51
Reward Campaigns are currently not supported, and I won't be supporting them. It's a new system from Twitch, their progress cannot be tracked as nothing shows up in your inventory nor campaigns page, and the rewards are awarded manually by the game developer.

Reward Campaigns have their own section on the campaigns page. Only Drop Campaigns and Timed Drops are supported.

This is also a duplicate of #475 and #468.

**Closed by DevilXD** 2024-07-05 14:51 UTC
Labels: Duplicate, Wont Fix

**Comment by Artanisx** [comment] 2024-07-05 15:07
Understood! I suspected it was something weird about this specific drop, thanks for the explanation :)
