### ISSUE TITLE
Empty channel list when using "priority only" mode

### ISSUE THREAD

**Issue by snwefly** [DevilXD/TwitchDropsMiner#213] opened 2023-06-05 14:37 UTC
When using wild mode miner able to mine the drops but in priority only mode miner unable to fetch any channels. not sure its a bug in the application or issues with games with special characters in their title.

![image](https://github.com/DevilXD/TwitchDropsMiner/assets/88805679/bbd318f6-003c-48a9-b45a-44b2c193c7a2)
![image](https://github.com/DevilXD/TwitchDropsMiner/assets/88805679/6ba46c20-1ec4-47fa-9f92-e19cfcc7c5c0)
![image](https://github.com/DevilXD/TwitchDropsMiner/assets/88805679/1e03ac33-7142-431d-b2d6-9213edf0dbcf)

**Comment by DevilXD** [comment] 2023-06-05 19:13
Hello there o/

It's hard to say anything specific here. The channels from the first of your pictures, could've came from an entirely different campaign than you have added to your priority list. Channels aren't tied to any particular campaign. Imagine a situation like this:

Campaign #​1 with game X, with an ACL that includes channel A, B and C  
Campaign #​2 with game Y, with no ACL  
Priority list is set only to game Y.

With the "Priority only" option disabled, both campaigns would be considered. Channels A, B and C would be added to the list for tracking purposes. If any of those channels would end up streaming game Y, it'd be used to mine the 2nd campaign.  
With the "Priority only" option enabled, only the 2nd campaign would be considered. The automatic channel search can fail (due to #212), leaving you with no channels on the list and no mining happening.

Given the 1st picture has a full house on the websocket topics, and the 3rd one has none, it's quite simple to say that, among those 398 channels that are tracked on the 1st picture, there can easily be some channels found that will end up playing games from the priority list. This is pure coincidence though, hence the difference.

This is most likely a duplicate of #212, so I'm closing it. You can disable the "Priority only" option until it's fixed.

**Closed** 2023-06-05 19:13 UTC
Labels: Bug, Duplicate
