### ISSUE TITLE
Chinese Localization Issue

### ISSUE THREAD

**Issue by wwj010** [DevilXD/TwitchDropsMiner#42] opened 2022-09-15 02:31 UTC
Hello! Thank you for adding Chinese Localization support for the application.
I do notice there are some translation error and would like to help it out.

In Main Tab:
"Channels" should be translated to "直播频道"
![image](https://user-images.githubusercontent.com/13106792/190298653-816d11f0-0fdc-4121-8833-4dd054655398.png)

In Inventory Tab:
In current version, when the drop is claimed, the status shows "声明". The correct term should be "已领取".
![image](https://user-images.githubusercontent.com/13106792/190296394-934168c4-97e4-4d2d-bdea-87aea78fba70.png)

The "直播中√" appeared next to the game is "Linked" in English. I'm not sure if this mean that my account for this game is linked to twitch account. In that case, this should be "已连接账号".
“Allowed Channels” is "允许掉宝的频道"
![image](https://user-images.githubusercontent.com/13106792/190296558-c6442fe9-29c0-4cef-8c28-e619ee6e1be3.png)
"Linked Only" Option is "仅已连接游戏" 
![image](https://user-images.githubusercontent.com/13106792/190298371-64118e6c-42c2-4cbd-9524-62b69436df18.png)

In setting Tab:
"Prority" should be translated to "优先游戏列表" or "优先掉宝游戏"
“Exclude” should be "排除游戏列表" or "不参与掉宝游戏"
"Prority Only" is "仅参与优先列表内的游戏"

Help Tab has more translation error. If you can provide the original text, I can correct it for you.

**Comment by DevilXD** [comment] 2022-09-15 05:03
Hello o/

I see. Would you be interested in making a PR with these changes (which will attribute them to you), or should I just implement it myself according to your description?

**Comment by DevilXD** [comment] 2022-09-15 18:02
Okay, I see there's some debate over which translation can be considered the "proper" one. As far as I could tell, the current translation is based on Simplified Chinese (by design), to make it easy to understand to the end user - it's fine as long as it can make sense. If it can't make any sense though, it'd be better to change it.

@wwj010 Would you be able to create a PR incorporating these changes? If you don't know what I'm talking about, please let me know as well, and we'll figure something out.

**Comment by wwj010** [comment] 2022-09-15 21:00
Thank you @Suz1e for translating it. I will try to create a PR that keep your work but only correct those few words that not make sense.

**Comment by Suz1e** [comment] 2022-09-16 04:14
"声明" “已领取”can indeed be modified, but although the other contents are different from the English translation, the meaning is similar and easier to understand

**Comment by Suz1e** [comment] 2022-09-16 04:17
Some translations are translations of the previous version and were updated later, but the translations are not updated, but it does not affect understanding, but you can try to modify the tutorial text of the help page

**Comment by Suz1e** [comment] 2022-09-16 04:32
I have sent the latest version of the optimized translation

**Comment by DevilXD** [comment] 2022-09-16 05:31
> I have sent the latest version of the optimized translation

Cool, but there is a PR for theses changes in place now. If you have any notes you'd like to make to it, please leave a review under the PR here: #43

**Comment by DevilXD** [comment] 2022-09-20 18:48
This is now closed via #43

**Closed by DevilXD** 2022-09-20 18:48 UTC
Labels: Enhancement
