### ISSUE TITLE
fatal error

### ISSUE THREAD

**Issue by dragongrafdiscord** [DevilXD/TwitchDropsMiner#624] opened 2024-11-17 18:39 UTC
`19:37:20: Fatal error encountered:
19:37:20: 
19:37:20: Traceback (most recent call last):
19:37:20:   File "main.py", line 155, in main
19:37:20:   File "twitch.py", line 587, in run
19:37:20:   File "twitch.py", line 747, in _run
19:37:20:   File "twitch.py", line 1656, in bulk_check_online
19:37:20:   File "asyncio\tasks.py", line 571, in _wait_for_one
19:37:20:   File "twitch.py", line 1387, in gql_request
19:37:20: exceptions.GQLException: [{'message': 'service error', 'path': ['channel', 'viewerDropCampaigns']}]
19:37:20: 
19:37:20: Exiting...
19:37:20: 
19:37:20: Application Terminated.
19:37:20: Close the window to exit the application.
`
tried restarting it a few times, its just trapped in this loop

**Comment by dragongrafdiscord** [comment] 2024-11-17 18:50
testing dev build rn but it doesnt seem to work at all
same result tho
`19:47:49: Fatal error encountered:
19:47:49: 
19:47:49: Traceback (most recent call last):
19:47:49:   File "main.py", line 155, in main
19:47:49:   File "twitch.py", line 587, in run
19:47:49:   File "twitch.py", line 747, in _run
19:47:49:   File "twitch.py", line 1657, in bulk_check_online
19:47:49:   File "asyncio\tasks.py", line 571, in _wait_for_one
19:47:49:   File "twitch.py", line 1387, in gql_request
19:47:49: exceptions.GQLException: [{'message': 'service error', 'path': ['channel', 'viewerDropCampaigns']}]
19:47:49: 
19:47:49: Exiting...
19:47:50: 
19:47:50: Application Terminated.
19:47:50: Close the window to exit the application.
`

**Comment by DevilXD** [comment] 2024-11-17 18:53
Duplicate of #590.

**Closed by DevilXD** 2024-11-17 18:53 UTC
