### ISSUE TITLE
get_stream data error

### ISSUE THREAD

**Issue by rakosi2** [DevilXD/TwitchDropsMiner#527] opened 2024-08-02 18:12 UTC
It fails to start mining. I made sure that I am using the latest version of v16.dev.59de7a7. I tried to delete cache and cookies and relog in but still errors.

```11:01:37: Fatal error encountered:
11:01:37: 
11:01:37: Traceback (most recent call last):
11:01:37:   File "main.py", line 153, in main
11:01:37:   File "twitch.py", line 570, in run
11:01:37:   File "twitch.py", line 719, in _run
11:01:37:   File "channel.py", line 287, in update_stream
11:01:37:   File "channel.py", line 255, in get_stream
11:01:37: KeyError: 'data'
11:01:37: 
11:01:37: Exiting...
11:01:37: 
11:01:37: Application Terminated.
11:01:37: Close the window to exit the application.

**Comment by DevilXD** [comment] 2024-08-02 18:35
Duplicate of #526.

**Closed by DevilXD** 2024-08-02 18:35 UTC
Labels: Bug, Duplicate
