### ISSUE TITLE
Feature Requests: Prioritize based on end time + Don't progress if there isn't enough time left

### ISSUE THREAD

**Issue by Taizunz** [DevilXD/TwitchDropsMiner#330] opened 2023-10-20 19:58 UTC
I frequently find myself realizing that I've missed a bunch of drops because I've just let the miner do its thing for days without verifying that it's progressing on the things I'd like for it to progress on first.
That's why I'd love to see a feature that would allow us to enable prioritization based on when a campaign ends/deadline, so the app will attempt to progress on campaigns that end soon first.
Furthermore, this feature would also be great for times when extremely short drops campaigns happen - i.e. a campaign that only lasts for 1 hour, and isn't announced anywhere or submitted as an upcoming campaign. My "FOMO" is really to blame for wanting this. I hate missing out on these quick campaigns.

An additional feature request that would go along well with this is for the app to not attempt to progress a campaign if that campaign ends before it would be possible to finish a drop, as that would just be a waste of time. 
Example: Campaign ends in 25 minutes. You need 45 minutes of watch time to get the drop. Progressing on this campaign would not make sense. (My bad if this kind of check already exists in the app)

**Comment by DevilXD** [comment] 2023-10-20 20:35
Hello. Please see the discussion under #255, as this was already suggested before. The solution is to just utilize the Priority list to achieve what you're describing. The existing functionality should be sufficient to let you prioritize games with short and frequent campaigns, over games with longer, "filler" campaigns.

Regarding the end time check, that's not really feasible to implement in an error-free way. Some campaigns can have all of their drops progressed at the same time, but the miner only gets updates for one of the drops at a time, and it's always the one with the shortest remaining time left - without knowing the actual progress of all drops, no good decision can be made. Campaigns can be extended at any time, that gives more time for mining drops, that'd otherwise be forfeited due to "not having enough time left". There's several other edge cases where it'd simply either fail to do it's job, or do it too eagerly and prevent you from getting the drop you'd normally be able to get. I had it on my TODO list at some point, but then when I realized it'd not only be a yet another thing to implement and support, but it'd also most likely break often, I pretty much scratched out the idea.

**Comment by Taizunz** [comment] 2023-10-20 20:41
Ah, sorry, I should've searched for similar requests first.

About using the priority list: I already do. This doesn't eliminate the risk of missing out on drops that have short campaigns though. My (and #255 's) feature request would, as it would be a supplement to it.

**Comment by DevilXD** [comment] 2023-10-21 19:27
> This doesn't eliminate the risk of missing out on drops that have short campaigns though.

It does, if you give enough priority to the game the campaign is for. If you can't get the campaign after giving it's game the top place on the priority list, then your miner uptime is the cause for not being able to finish it, not the priority system.

**Comment by Taizunz** [comment] 2023-10-21 20:01
You would have to be on top of managing the priority list all of the time to make sure you adjust according to campaign changes. It would be micro-managing, and I'm trying to macro-manage instead.

Let's look at my current priority list as an example: 
![image](https://github.com/DevilXD/TwitchDropsMiner/assets/15648000/f9c5ff25-db5d-4c4e-a0b6-12c608aafb55)

Now let's bring in some fake drop campaigns to create an example situation:
New World of Warcraft campaign starts now, ends in a week, requires 12 hours of watch time.
New Diablo campaign starts in an hour, ends in 6 hours, requires 1 hour of watch time.
According to the current priority list and with how the miner currently works the miner would start watching a WoW stream to progress the new WoW campaign. An hour later, the Diablo campaign starts but the miner is preoccupied with the WoW campaign until it has finished watching for 12 hours, so it will be missing out on the Diablo campaign entirely.
If there was a deadline/end time prioritization option it would switch to the campaign that ends the soonest, first according to the entries in the priority list, then according to overall campaigns (unless the miner is in "Priority Only"-mode of course).
I hope that makes my thought process a bit clearer.

I will respect your decision to reject or accept it equally as this is your project, and I'm just a humble user trying to bring up some ideas for improvements based on my personal use-cases. I am incredibly thankful for this app no matter what.

**Comment by DevilXD** [comment] 2023-10-21 22:03
> Now let's bring in some fake drop campaigns to create an example situation:
New World of Warcraft campaign starts now, ends in a week, requires 12 hours of watch time.
New Diablo campaign starts in an hour, ends in 6 hours, requires 1 hour of watch time.
According to the current priority list and with how the miner currently works the miner would start watching a WoW stream to progress the new WoW campaign. An hour later, the Diablo campaign starts but the miner is preoccupied with the WoW campaign until it has finished watching for 12 hours, so it will be missing out on the Diablo campaign entirely.
Meanwhile I'm occupied with playing my own game and don't notice that the Diablo campaign happened, so I won't get around to manually change the priority list (the micro-manage part).

I think you didn't understand my explanation, and can't fully grasp what the priority list is and how it works. To solve your theoretical situation, all it takes is to put Diablo above WoW on the priority list. That's it. The Diablo campaign won't be active, so your miner will be watching WoW instead. When it becomes active, it'll switch to the Diablo campaign automatically, since it's higher priority. Once it's done, it'll switch back to WoW. That's all there is to it. You don't need to micro-manage it.

Again, put games with long, "filler" campaigns near the bottom, and ones with short, more important campaigns near the top. The priority list isn't only about "the games you want to get the drops of first". You can use it that way, if you want to. If you're interested in getting "short campaigns you'd normally miss on", reorder the list so that they're prioritized over other games that have filler campaigns.

**Comment by Taizunz** [comment] 2023-10-21 22:10
> To solve your theoretical situation, all it takes is to put Diablo above WoW on the priority list. That's it. The Diablo campaign won't be active, so your miner will be watching WoW instead.

That's literally micro-managing. I can't "set it and forget it".

> Again, put games with long, "filler" campaigns near the bottom, and ones with short, more important campaigns near the top.

This assumes campaigns for a game will always work in a specific way.


We both appear to have very different approaches to this.

**Comment by DevilXD** [comment] 2023-10-22 15:04
> This assumes campaigns for a game will always work in a specific way - i.e., WoW always has filler campaigns, D4 always has short campaigns. You'll never truly know what types of campaigns are launched.

You will, if you're paying a minimum amount of attention and set it appropriately beforehand.

> We both appear to have very different approaches and mindsets to this.

Indeed, because this isn't a "set and forget" miner you're probably thinking it is. Please see [the project goals,](https://github.com/DevilXD/TwitchDropsMiner#project-goals) specifically:

> Underlying service friendly - the amount of interactions done with the Twitch site is kept to the minimum required for reliable operation, at a level achievable by a **diligent site user.**

With that in mind, this is a Wont Fix from me. If you're looking something you can setup on a server and forget about it, there are other projects that might be more worthy for you.

**Closed by DevilXD** 2023-10-22 15:04 UTC
Labels: Enhancement, Wont Fix
