### ISSUE TITLE
Helldivers 2 "Not Linked" status.

### ISSUE THREAD

**Issue by MarioRPGGeno** [DevilXD/TwitchDropsMiner#441] opened 2024-02-18 10:14 UTC
Attempting to link an account for Helldivers 2 drop seems to only function if you've already claimed the drop if I understand correctly. Twitch Drops Miner refuses to mine the drop unless it sees the account status as "Linked" however- is there any way to force the bot to mine for the drop despite not being seen as linked?

**Comment by DevilXD** [comment] 2024-02-18 14:40
Hello.

No, there's no way to enable mining campaigns you don't have the account linked to. This makes the Helldivers 2 game unsupported by this miner.

This is also a duplicate of #439 and #432.

**Closed** 2024-02-18 14:40 UTC
Labels: Bug, Duplicate
