### ISSUE TITLE
No progress

### ISSUE THREAD

**Issue by zelda0079** [DevilXD/TwitchDropsMiner#326] opened 2023-10-19 11:19 UTC
I am trying to idle the EVE online drop
No progress shows in my twitch
and then I try to refresh the inventory page after 2 minutes,
it is still 31% (the 31% is idled by broswer)
https://i.imgur.com/MjbMnP9.png

However, the twitch does not show the progress even I idle the twitch drop by broswer...
But the twitch drop progress is increased.

**Comment by zelda0079** [comment] 2023-10-19 13:06
latest version

**Comment by DevilXD** [comment] 2023-10-19 18:20
This is a duplicate of #301.

**Closed by DevilXD** 2023-10-19 18:20 UTC
Labels: Bug, Duplicate
