### ISSUE TITLE
Error on open 11/october/22 

### ISSUE THREAD

**Issue by IRhoAias** [DevilXD/TwitchDropsMiner#575] opened 2024-10-11 16:47 UTC
13:44:09: Fatal error encountered:
13:44:09: 
13:44:09: Traceback (most recent call last):
13:44:09:   File "main.py", line 155, in main
13:44:09:   File "twitch.py", line 587, in run
13:44:09:   File "twitch.py", line 747, in _run
13:44:09:   File "twitch.py", line 1656, in bulk_check_online
13:44:09:   File "asyncio\tasks.py", line 571, in _wait_for_one
13:44:09:   File "twitch.py", line 1387, in gql_request
13:44:09: exceptions.GQLException: [{'message': 'service error', 'path': ['channel', 'viewerDropCampaigns']}]
13:44:09: 
13:44:09: Exiting...
13:44:10: 
13:44:10: Application Terminated.
13:44:10: Close the window to exit the application.

has been happening since morning and I have the latest version available.

**Comment by hotspotter** [comment] 2024-10-11 17:10
Hab den gleichen Fehler bekommen bei jedem Neustart bekommen. Nachdem ich Destiny 2 gesperrt habe war der Fehler weg.

**Comment by TheLovinator1** [comment] 2024-10-11 17:31
> Hab den gleichen Fehler bei jedem Neustart bekommen. Nachdem ich Destiny 2 gesperrt habe war der Fehler weg.

"I kept getting the same error after every restart. After I excluded Destiny 2, the error was gone."

**Comment by DevilXD** [comment] 2024-10-11 18:44
This is a duplicate of #415.

**Closed by DevilXD** 2024-10-11 18:44 UTC
