### ISSUE TITLE
Script doesn't collect the drop

### ISSUE THREAD

**Issue by ezbooz** [DevilXD/TwitchDropsMiner#195] opened 2023-05-17 17:41 UTC
20:25:02: Traceback (most recent call last):
20:25:02:   File "utils.py", line 96, in wrapper
20:25:02:   File "twitch.py", line 1332, in process_drops
20:25:02:   File "inventory.py", line 202, in claim
20:25:02:   File "inventory.py", line 120, in claim
20:25:02:   File "inventory.py", line 136, in _claim
20:25:02:   File "twitch.py", line 1534, in gql_request
20:25:02: exceptions.MinerException: GQL error: [{'message': 'PersistedQueryNotFound'}]

**Comment by DevilXD** [comment] 2023-05-17 19:33
This is a duplicate of #138.

**Closed by DevilXD** 2023-05-17 19:33 UTC
Labels: Bug, Duplicate
