### ISSUE TITLE
unsupport Diablo IV Twitch Drop

### ISSUE THREAD

**Issue by luyurun** [DevilXD/TwitchDropsMiner#238] opened 2023-06-25 03:34 UTC
Release v15 Version NOT support Diablo IV/WarThunder/World of Tank Twitch Drop.
It can provide a list of Twitch live that ENABLED drop, but displays X on gift icon column.
-----
Development build version resolved the problem, but errors are frequently reported in the log.

**Comment by DevilXD** [comment] 2023-06-25 07:00
The release version does not work anymore, yes. The development version is waiting for #234 to complete before I can declare the next stable version. For now, you can use the development one.

What errors are you experiencing? I'll need the tracebacks to be able to help you in any way.

**Comment by luyurun** [comment] 2023-06-25 07:25
Thanks for your reply!
I have closed the DropMiner before, the log window has been emptied.
When I see the error code again, I will paste it in this post.

_The software is very easy to use, thank you for keep maintenance!_

**Comment by luyurun** [comment] 2023-06-26 13:34
@DevilXD Error in the log window:
`21:32:59: Fatal error encountered:
21:32:59: 
21:33:00: Traceback (most recent call last):
21:33:00:   File "main.py", line 174, in <module>
21:33:00:   File "asyncio\base_events.py", line 647, in run_until_complete
21:33:00:   File "twitch.py", line 768, in run
21:33:00:   File "twitch.py", line 787, in _run
21:33:00:   File "twitch.py", line 1458, in get_auth
21:33:00:   File "twitch.py", line 516, in validate
21:33:00:   File "twitch.py", line 544, in _validate
21:33:00:   File "twitch.py", line 299, in _oauth_login
21:33:00:   File "contextlib.py", line 181, in __aenter__
21:33:00:   File "twitch.py", line 1483, in request
21:33:00:   File "gui.py", line 2054, in coro_unless_closed
21:33:00:   File "aiohttp\client.py", line 1125, in send
21:33:00:   File "aiohttp\client.py", line 536, in _request
21:33:00:   File "aiohttp\connector.py", line 540, in connect
21:33:00:   File "aiohttp\connector.py", line 901, in _create_connection
21:33:00:   File "aiohttp\connector.py", line 1175, in _create_direct_connection
21:33:00:   File "aiohttp\connector.py", line 980, in _wrap_create_connection
21:33:00:   File "asyncio\base_events.py", line 1050, in create_connection
21:33:00:   File "asyncio\base_events.py", line 961, in _connect_sock
21:33:00:   File "asyncio\proactor_events.py", line 703, in sock_connect
21:33:00: RuntimeError: await wasn't used with future
21:33:00: 
21:33:00: Exiting...
21:33:00: 
21:33:00: Application Terminated.
21:33:00: Close the window to exit the application.`

**Comment by luyurun** [comment] 2023-06-26 13:34
@DevilXD Error code in the log window:
`21:32:59: Fatal error encountered:

21:32:59: 
21:33:00: Traceback (most recent call last):
21:33:00:   File "main.py", line 174, in <module>
21:33:00:   File "asyncio\base_events.py", line 647, in run_until_complete
21:33:00:   File "twitch.py", line 768, in run
21:33:00:   File "twitch.py", line 787, in _run
21:33:00:   File "twitch.py", line 1458, in get_auth
21:33:00:   File "twitch.py", line 516, in validate
21:33:00:   File "twitch.py", line 544, in _validate
21:33:00:   File "twitch.py", line 299, in _oauth_login
21:33:00:   File "contextlib.py", line 181, in __aenter__
21:33:00:   File "twitch.py", line 1483, in request
21:33:00:   File "gui.py", line 2054, in coro_unless_closed
21:33:00:   File "aiohttp\client.py", line 1125, in send
21:33:00:   File "aiohttp\client.py", line 536, in _request
21:33:00:   File "aiohttp\connector.py", line 540, in connect
21:33:00:   File "aiohttp\connector.py", line 901, in _create_connection
21:33:00:   File "aiohttp\connector.py", line 1175, in _create_direct_connection
21:33:00:   File "aiohttp\connector.py", line 980, in _wrap_create_connection
21:33:00:   File "asyncio\base_events.py", line 1050, in create_connection
21:33:00:   File "asyncio\base_events.py", line 961, in _connect_sock
21:33:00:   File "asyncio\proactor_events.py", line 703, in sock_connect
21:33:00: RuntimeError: await wasn't used with future
21:33:00: 
21:33:00: Exiting...
21:33:00: 
21:33:00: Application Terminated.
21:33:00: Close the window to exit the application.`

**Comment by DevilXD** [comment] 2023-06-26 17:15
That error is a duplicate of #80. Please refer to that issue instead. Closing this one.

**Closed by DevilXD** 2023-06-26 17:15 UTC
Labels: Bug, Duplicate
