### ISSUE TITLE
DEV Versions are flagged as Trojan by Microsoft Defender

### ISSUE THREAD

**Issue by Shazgul** [DevilXD/TwitchDropsMiner#217] opened 2023-06-11 12:01 UTC
Microsoft Defender flags the new DEV Builds as "Trojan:Win32/Wacatac.B!ml".
Anyone implemented anything bad?

**Comment by DevilXD** [comment] 2023-06-11 12:12
Nothing's changed. This is a duplicate of #13 and #209. You can also check out this soon-to-be-added portion of the README file that explains more: https://github.com/DevilXD/TwitchDropsMiner/commit/5bdd1a4ebc76a9c7dabf8ab21188334becfcf044

Current VirusTotal scan: https://www.virustotal.com/gui/file/947705e5960b91e5de7d4ea71aaaad7eef56b4d66977212767a4f7b0b52aa18e

I have no plans to replace PyInstaller with something else, so you can just ignore what your AV says. Alternatively, consider using something better for an AV engine, like NOD32, Kaspersky or even BitDefender.

**Closed by DevilXD** 2023-06-11 12:12 UTC
Labels: Question
