### ISSUE TITLE
TypeError("Passing coroutines is forbidden, use tasks explicitly.")

### ISSUE THREAD

**Issue by Kumariz0** [DevilXD/TwitchDropsMiner#72] opened 2022-11-05 19:24 UTC
When i try to run the master branch using `python main.py` it starts the GUI but then returns me this error in the GUI console:
`Fatal error encountered:

Traceback (most recent call last):
  File "C:\Users\kumariz\Desktop\TwitchDropsMiner\main.py", line 177, in <module>
    loop.run_until_complete(client.run())
  File "C:\Users\kumariz\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\kumariz\Desktop\TwitchDropsMiner\twitch.py", line 351, in run
    await self._run()
  File "C:\Users\kumariz\Desktop\TwitchDropsMiner\twitch.py", line 370, in _run
    auth_state = await self.get_auth()
                 ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kumariz\Desktop\TwitchDropsMiner\twitch.py", line 913, in get_auth
    await self._auth_state.validate()
  File "C:\Users\kumariz\Desktop\TwitchDropsMiner\twitch.py", line 136, in validate
    await self._validate()
  File "C:\Users\kumariz\Desktop\TwitchDropsMiner\twitch.py", line 145, in _validate
    async with self._twitch.request("GET", BASE_URL) as response:
  File "C:\Users\kumariz\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 204, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kumariz\Desktop\TwitchDropsMiner\twitch.py", line 937, in request
    response = await self.gui.coro_unless_closed(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kumariz\Desktop\TwitchDropsMiner\gui.py", line 1929, in coro_unless_closed
    done, pending = await asyncio.wait(
                    ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kumariz\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 415, in wait
    raise TypeError("Passing coroutines is forbidden, use tasks explicitly.")
TypeError: Passing coroutines is forbidden, use tasks explicitly.

Exiting...
`
The same thing happens as well when i run the pyinstaller build i made using `pyinstaller build.spec`

This doens't happen when i run the v14 build but then i have the issue #68 when i try to login.

Any help?

**Comment by DevilXD** [comment] 2022-11-05 20:24
Hello o/

This is a duplicate of #71, please comment under that issue instead.

**Closed by DevilXD** 2022-11-05 20:24 UTC
Labels: Bug, Duplicate, Dev
