### ISSUE TITLE
ERROR: Exception in task

### ISSUE THREAD

**Issue by fraizzo** [DevilXD/TwitchDropsMiner#192] opened 2023-05-17 06:42 UTC
After a drop is finished i receive this errors:

08:40:25: ERROR: Exception in task
08:40:25: Traceback (most recent call last):
08:40:25:   File "utils.py", line 96, in wrapper
08:40:25:   File "twitch.py", line 1332, in process_drops
08:40:25:   File "inventory.py", line 202, in claim
08:40:25:   File "inventory.py", line 120, in claim
08:40:25:   File "inventory.py", line 136, in _claim
08:40:25:   File "twitch.py", line 1534, in gql_request
08:40:25: exceptions.MinerException: GQL error: [{'message': 'PersistedQueryNotFound'}]

I tried to reinstall, with new login but same error

**Comment by DevilXD** [comment] 2023-05-17 06:53
This is a duplicate of #138 and will be fixed in the next release. Please use the latest master branch version in the mean time.

**Closed by DevilXD** 2023-05-17 06:53 UTC
Labels: Bug, Duplicate

**Comment by legalcormorant** [comment] 2023-05-17 06:54
> This is a duplicate of #138 and will be fixed in the next release. Please use the latest master branch version in the mean time.

which you have to compile from source so don't even bother as if you are doing the Rust campaign it doesn't even work for it
