### ISSUE TITLE
error dev a428c72

### ISSUE THREAD

**Issue by matarife123** [DevilXD/TwitchDropsMiner#599] opened 2024-11-01 19:09 UTC
20:08:21: Fatal error encountered:
20:08:21: 
20:08:21: Traceback (most recent call last):
20:08:21:   File "main.py", line 155, in main
20:08:21:   File "twitch.py", line 587, in run
20:08:21:   File "twitch.py", line 747, in _run
20:08:21:   File "twitch.py", line 1657, in bulk_check_online
20:08:21:   File "asyncio\tasks.py", line 571, in _wait_for_one
20:08:21:   File "twitch.py", line 1387, in gql_request
20:08:21: exceptions.GQLException: [{'message': 'service error', 'path': ['channel', 'viewerDropCampaigns']}]
20:08:21: 
20:08:21: Saliendo...
20:08:22: 
20:08:22: La aplicación se ha detenido.
20:08:22: Por favor, cierre la aplicación.

**Comment by DevilXD** [comment] 2024-11-01 21:01
I know this doesn't really count as a duplicate, but #590 was closed 4 days ago, and it has most of the discussion about this. It seems that the issue is not yet resolved after all.

I'll reopen #590 and close this one as duplicate.

**Closed by DevilXD** 2024-11-01 21:01 UTC
Labels: Bug, Duplicate
