### ISSUE TITLE
Fatal error encountered: ValueError: time data does not match format

### ISSUE THREAD

**Issue by vascopaulo** [DevilXD/TwitchDropsMiner#360] opened 2023-11-09 19:26 UTC
18:46:59: Fatal error encountered:
18:46:59: 
18:46:59: Traceback (most recent call last):
18:46:59:   File "main.py", line 158, in main
18:46:59:   File "twitch.py", line 765, in run
18:46:59:   File "twitch.py", line 807, in _run
18:46:59:   File "twitch.py", line 1604, in fetch_inventory
18:46:59:   File "twitch.py", line 1605, in <dictcomp>
18:46:59:   File "utils.py", line 112, in timestamp
18:46:59:   File "_strptime.py", line 568, in _strptime_datetime
18:46:59:   File "_strptime.py", line 349, in _strptime
18:46:59: ValueError: time data '2023-10-31T21:06:46.324Z' does not match format '%Y-%m-%dT%H:%M:%SZ'
18:46:59: 
18:46:59: Exiting...
18:46:59: 
18:46:59: Application Terminated.
18:46:59: Close the window to exit the application.

**Comment by DevilXD** [comment] 2023-11-09 21:19
Duplicate of #345.

**Closed by DevilXD** 2023-11-09 21:19 UTC
Labels: Bug, Duplicate
