### ISSUE TITLE
Waiting for an ONLINE channel...even tho they're online

### ISSUE THREAD

**Issue by SirSuperDeath** [DevilXD/TwitchDropsMiner#212] opened 2023-06-04 10:22 UTC
No available channels to watch. Waiting for an ONLINE channel...
even tho one of the drops I could farm is category wide for the Elite: Dangerous category. I do have Priority only on due to it showing a bunch of other games and not just the ones i want. 

![Twitch_Drops_Miner_(by_DevilXD)_xX6avh97pJ](https://github.com/DevilXD/TwitchDropsMiner/assets/6559285/0eef8664-1bb3-4efb-81bc-9620121eccc0)
(Screenshots were from the 11hr update) but also just updated and its the same

![rqzjwCQm3g](https://github.com/DevilXD/TwitchDropsMiner/assets/6559285/cf368dfb-9f8f-4461-beee-621d328c31d5)
![Twitch_Drops_Miner_(by_DevilXD)_QKwUpwde5y](https://github.com/DevilXD/TwitchDropsMiner/assets/6559285/8766a229-87fa-4ccf-a57d-6f8a27e21488)

Im also running the newest updated that i got from [https://github.com/DevilXD/TwitchDropsMiner/releases/tag/dev-build](url) (the dev build)

**Comment by DevilXD** [comment] 2023-06-04 10:31
Hello o/

This is most likely cause by the recent channel tags changes Twitch has introduced, that made it impossible to search for ONLINE channels which have the "drops enabled" tag added to them. Please check out #189 for a reference issue.

Regardless, the cause is similar to #189's cause, but the problem exists in an entirely different portion of the application: channel aggregation instead of channel selection logic. Because of this, I'm leaving this as a separate issue and not a duplicate, for better tracking purposes. Once #189 gets fixed properly, this issue will be fixed along with it.

**Comment by kyleshrader** [comment] 2023-06-05 04:07
If the application's core functionality is broken due to this, can we get a feature to force-watch a channel regardless of "drops-enabled" status?

**Comment by Duckiestiowa7** [comment] 2023-06-05 12:06
The latest experimental build (the one from June 4) seems to have fixed the issue for me. I tested it with WoT; mines flawlessly now.

@DevilXD love your work, my dude.

**Comment by kyleshrader** [comment] 2023-06-05 15:28
I decided to run off master, and yeah it's working as of [4664a9d](https://github.com/DevilXD/TwitchDropsMiner/commit/4664a9d7dac44c5daa8fa2349d43cd7080a08f78). Thanks.

**Comment by DevilXD** [comment] 2023-06-18 09:01
It turns out that this issue can receive a temporary fix too, just like #189 did.

https://github.com/DevilXD/TwitchDropsMiner/commit/a7c3925e53f211fc032dde169220b01b1e55d89a makes the channel search ignore the tag as well. The resulting channel list contains channels that seem to contain the tag anyway. It almost seems like the Twitch search broke, or Twitch disabled searching with the tag on purpose.

A proper fix is still waiting for #189 to resolve together with this issue. The temporary fix is now available in the latest dev build.

**Comment by ProCasual** [comment] 2023-08-28 07:46
Seems to be happening again, clicking 'Switch' on an online channel just triggers another 'No available channels to watch. Waiting for an ONLINE channel...'

![image](https://github.com/DevilXD/TwitchDropsMiner/assets/127465731/77768bcd-a332-4ab0-ac0f-3aec7a1d4c44)

**Comment by ProCasual** [comment] 2023-08-28 20:48
@DevilXD 

What the heck?! Sorry! I've been using the dev builds for ages now, I have no idea how I managed to go back to v15. I must have downloaded it accidentally when trying to update.

Thank you for replying, and thank you for the excellent app.

**Comment by Yeetov** [comment] 2023-09-22 10:11
Fixed if you use the [development build](https://github.com/DevilXD/TwitchDropsMiner/releases/tag/dev-build)

**Closed** 2024-09-15 12:29 UTC
Labels: Bug
