### ISSUE TITLE
VirusTotal - Backdoor?

### ISSUE THREAD

**Issue by KubiszDeny** [DevilXD/TwitchDropsMiner#315] opened 2023-10-10 05:46 UTC
For DevBuild 
https://www.virustotal.com/gui/file/0e739342057bf323d103b8725ce9298cd6780ac0228e07fb3b010f6c24a34f20?nocache=1

**Comment by spuukii** [comment] 2023-10-10 11:43
This is due to Pyinstaller. It's in the README.

To achieve a portable-executable format, the application is packaged with PyInstaller into an EXE. Some non-mainstream antivirus engines might report the packaged executable as a trojan, because PyInstaller has been used by others to package malicious Python code in the past. These reports can be safely ignored. If you absolutely do not trust the executable, you'll have to install Python yourself and run everything from source.

Per the README, if you want to avoid the issue then install Python and run everything from source.

This is a duplicate of https://github.com/DevilXD/TwitchDropsMiner/issues/284, https://github.com/DevilXD/TwitchDropsMiner/issues/270, https://github.com/DevilXD/TwitchDropsMiner/issues/249, https://github.com/DevilXD/TwitchDropsMiner/issues/217, https://github.com/DevilXD/TwitchDropsMiner/issues/209 and https://github.com/DevilXD/TwitchDropsMiner/issues/13.

**Comment by DevilXD** [comment] 2023-10-10 18:58
As said in the previous comment. Use a smarter AV engine.

**Closed by DevilXD** 2023-10-10 18:58 UTC
Labels: Bug, Duplicate
