### ISSUE TITLE
detected virus

### ISSUE THREAD

**Issue by Honorrr** [DevilXD/TwitchDropsMiner#641] opened 2024-12-11 16:28 UTC
I downloeded last version(3 weeks ago) its detected trojan I am using malwarebytes is it not safe to use anymore????

**Comment by JourneyOver** [comment] 2024-12-11 16:57
This is a duplicate of #616, #517, #508, #503, #420, #384, #335, #333, #315, #284, #270, #249, #217, #209, #137 and #13. Please search the existing issues (even closed ones) before submitting an issue yourself.

**Comment by Honorrr** [comment] 2024-12-11 17:02
What can I do for the solution?

**Comment by JourneyOver** [comment] 2024-12-11 17:05
There is nothing really to do short of

1. Closing this issue
2. ignoring the virus message as it's a false positive (You can put it under exclusions so it no longer comes up as a virus/trojan if you want)

**Comment by Honorrr** [comment] 2024-12-11 17:08
Can't the person who designed this do something?

**Comment by JourneyOver** [comment] 2024-12-11 17:09
As explained in #420 


> If the ignore/exclusion list isn't enough, then I can't really help you. "Fixing" this would require switching the entire project to use a different packaging method, other than PyInstaller. If you'd still have no luck, you can always run the whole application from source, or build an executable yourself - some instructions for that can be found here: [Wiki: Setting up the environment, building and running](https://github.com/DevilXD/TwitchDropsMiner/wiki/Setting-up-the-environment,-building-and-running)

**Comment by DevilXD** [comment] 2024-12-11 18:20
Well, that's pretty much everything what I'd have said here 🙃 Although there was also #620. That makes it 18 issues in total, together with this one.

*sigh*

Cheers @JourneyOver for handling this 👍

Closing as a duplicate.

**Closed by DevilXD** 2024-12-11 18:20 UTC
Labels: Bug, Duplicate

**Comment by Honorrr** [comment] 2024-12-11 19:42
@DevilXD are you gonna planning fix soon?
