### ISSUE TITLE
Not enough data for satisfy transfer length header

### ISSUE THREAD

**Issue by jordyamc** [DevilXD/TwitchDropsMiner#515] opened 2024-07-14 05:56 UTC
I have not seen this error before, its the second time in 2 days that this happens randomly

```
15:21:13: ERROR: Exception in _watch_loop task
15:21:13: Traceback (most recent call last):
15:21:13:   File "aiohttp\client_proto.py", line 83, in connection_lost
15:21:13:   File "aiohttp\\_http_parser.pyx", line 507, in aiohttp._http_parser.HttpParser.feed_eof
15:21:13: aiohttp.http_exceptions.TransferEncodingError: 400, message:
15:21:13:   Not enough data for satisfy transfer length header.
15:21:13: 
15:21:13: The above exception was the direct cause of the following exception:
15:21:13: 
15:21:13: Traceback (most recent call last):
15:21:13:   File "utils.py", line 139, in wrapper
15:21:13:   File "twitch.py", line 878, in _watch_loop
15:21:13:   File "channel.py", line 361, in send_watch
15:21:13:   File "contextlib.py", line 199, in __aenter__
15:21:13:   File "twitch.py", line 1306, in request
15:21:13:   File "aiohttp\client_reqrep.py", line 1101, in read
15:21:13:   File "aiohttp\streams.py", line 373, in read
15:21:13:   File "aiohttp\streams.py", line 395, in readany
15:21:13:   File "aiohttp\streams.py", line 302, in _wait
15:21:13: aiohttp.client_exceptions.ClientPayloadError: Response payload is not completed
16:00:01: ERROR: Stream state change for a non-existing channel: 106423240
16:00:05: ERROR: Broadcast settings update for a non-existing channel: 106423240
```

**Comment by DevilXD** [comment] 2024-07-14 09:08
Hello,

This is quite a strange error. It's hard to say whether this is a miner issue, or Twitch issue that they've temporarily introduced, but the cause is the server not sending the correct headers in response to a request. If this is a server issue, I'm pretty sure that the miner can't handle this in any graceful way, as repeating the request has pretty much a 100% of running into the same error again, and that'd just make it end up in an error-driven loop it's not going to get out of.

Based on the last two lines of that output, you seem to be having all kinds of connection issues. The miner should never end up printing out these two messages there. That could also be the cause here.

**Comment by Kigendor** [comment] 2024-07-26 10:23
I was roughly able to reproduce this error.
If we visit Twitch and perform any actions (such as accessing the inventory, watching streams, etc.) while the program is running, this error occurs before receiving Twitch drops.
The issue can be resolved by either not accessing Twitch from this account in the browser or restarting the program after visiting Twitch.

**Comment by DevilXD** [comment] 2024-07-26 13:14
Hmm, interesting. I'll try to reproduce it on my end using these instructions. Thank you for letting me know =)

**Comment by DevilXD** [comment] 2024-08-01 05:41
Unfortunately, I wasn't able to reproduce this issue. No matter what I do during mining, I can't cause the miner to crash like that. The only thing that happens, is the drop progress stops being accurate, if I'm watching another stream in the browser during mining.

You can try increasing the `connection_quality` value in your `settings.json` to 2 or 3 (or more, up to 6), if your connection is unstable like that. Other than that, there's no other remedy for this issue.

Is this still happening?

**Comment by jordyamc** [comment] 2024-08-02 18:37
No, after I sent this report I have not seen this error again

**Comment by DevilXD** [comment] 2024-08-03 08:56
I'd say it's a one-time occurrence then, and this issue can be closed. I can reopen it if needed later.

**Closed by DevilXD** 2024-08-03 08:56 UTC
Labels: Bug, Solved

**Comment by 97hr** [comment] 2024-09-02 04:10
Using the development release but not sure when I pulled it down, sorry.

18:39:04: ERROR: Exception in _watch_loop task
18:39:04: Traceback (most recent call last):
18:39:04:   File "aiohttp\client_proto.py", line 94, in connection_lost
18:39:04:   File "aiohttp\\_http_parser.pyx", line 513, in aiohttp._http_parser.HttpParser.feed_eof
18:39:04: aiohttp.http_exceptions.TransferEncodingError: 400, message:
18:39:04:   Not enough data for satisfy transfer length header.
18:39:04: 
18:39:04: The above exception was the direct cause of the following exception:
18:39:04: 
18:39:04: Traceback (most recent call last):
18:39:04:   File "utils.py", line 142, in wrapper
18:39:04:   File "twitch.py", line 860, in _watch_loop
18:39:04:   File "channel.py", line 371, in send_watch
18:39:04:   File "contextlib.py", line 199, in __aenter__
18:39:04:   File "twitch.py", line 1292, in request
18:39:04:   File "aiohttp\client_reqrep.py", line 1134, in read
18:39:04:   File "aiohttp\streams.py", line 383, in read
18:39:04:   File "aiohttp\streams.py", line 405, in readany
18:39:04:   File "aiohttp\streams.py", line 312, in _wait
18:39:04: aiohttp.client_exceptions.ClientPayloadError: Response payload is not completed: <TransferEncodingError: 400, message='Not enough data for satisfy transfer length header.'>. ConnectionResetError(22, 'The specified network name is no longer available', None, 64, None)
18:39:04: Exiting...
18:39:04: 
18:39:04: Application Terminated.
18:39:04: Close the window to exit the application.

**Comment by DevilXD** [comment] 2024-09-02 07:47
So basically, it just so happens that the PC was disconnected from the internet, at the very moment a request was being made, and that cuts off a multi-part response, without a way for it to continue?

If that's so, I can just add a handler for this particular case.
