### ISSUE TITLE
Occasional errors

### ISSUE THREAD

**Issue by wlk3773208** [DevilXD/TwitchDropsMiner#219] opened 2023-06-12 11:21 UTC
version:3fa9568
game:rust
The error log looks like this:
19:00:32: ERROR: Exception in task
19:00:32: Traceback (most recent call last):
19:00:32:   File "utils.py", line 110, in wrapper
19:00:32:   File "twitch.py", line 1044, in _watch_loop
19:00:32:   File "channel.py", line 364, in send_watch
19:00:32:   File "contextlib.py", line 181, in __aenter__
19:00:32:   File "twitch.py", line 1484, in request
19:00:32:   File "gui.py", line 2054, in coro_unless_closed
19:00:32:   File "aiohttp\client.py", line 1125, in send
19:00:32:   File "aiohttp\client.py", line 536, in _request
19:00:32:   File "aiohttp\connector.py", line 540, in connect
19:00:32:   File "aiohttp\connector.py", line 901, in _create_connection
19:00:32:   File "aiohttp\connector.py", line 1175, in _create_direct_connection
19:00:32:   File "aiohttp\connector.py", line 980, in _wrap_create_connection
19:00:32:   File "asyncio\base_events.py", line 1050, in create_connection
19:00:32:   File "asyncio\base_events.py", line 961, in _connect_sock
19:00:32:   File "asyncio\proactor_events.py", line 703, in sock_connect
19:00:32: RuntimeError: await wasn't used with future

At this point, I have to reload the program to continue working normally

**Comment by DevilXD** [comment] 2023-06-12 12:09
This is a duplicate of #80.

**Closed by DevilXD** 2023-06-12 12:09 UTC
Labels: Bug, Duplicate
