### ISSUE TITLE
issue with watching progress

### ISSUE THREAD

**Issue by NaniDaFuck** [DevilXD/TwitchDropsMiner#492] opened 2024-06-04 17:37 UTC
i have an issue with watching progress 
the program showing that it's working fine

but it's actually not doing any progress with Campaigns

when i restart it starts from the beginning  

is this issue with me only ?

**Comment by Chi6iC** [comment] 2024-06-04 19:14
I have the same problem. The latest version is v16 dev

**Comment by DevilXD** [comment] 2024-06-05 05:08
Duplicate of #462.

**Closed by DevilXD** 2024-06-05 05:08 UTC
Labels: Bug, Duplicate
