### ISSUE TITLE
TwitchDropsMiner Error

### ISSUE THREAD

**Issue by NikolaJyun** [DevilXD/TwitchDropsMiner#648] opened 2024-12-30 11:57 UTC
19:56:42: Fatal error encountered:
19:56:42: 
19:56:42: Traceback (most recent call last):
19:56:42:   File "main.py", line 155, in main
19:56:42:   File "twitch.py", line 587, in run
19:56:42:   File "twitch.py", line 648, in _run
19:56:42:   File "inventory.py", line 259, in claim
19:56:42:   File "inventory.py", line 142, in claim
19:56:42:   File "inventory.py", line 158, in _claim
19:56:42:   File "twitch.py", line 1390, in gql_request
19:56:42: exceptions.GQLException: [{'message': 'service error', 'path': ['claimDropRewards']}]
19:56:42: 
19:56:42: Exiting...
19:56:42: 
19:56:42: Application Terminated.
19:56:42: Close the window to exit the application.

**Comment by DevilXD** [comment] 2024-12-30 13:54
This is a duplicate of #590.

**Closed by DevilXD** 2024-12-30 13:54 UTC
Labels: Bug, Duplicate
