### ISSUE TITLE
Not switching campaign when it's done

### ISSUE THREAD

**Issue by biast12** [DevilXD/TwitchDropsMiner#378] opened 2023-12-06 20:44 UTC
Hey, i'm not sure if this already are reported but better save then sorry i guess

I noticed that it didn't switch channel/campaign when the progress was done, is that supposed to happen or? would be really nice if it reloaded when the campaign progress is fully done

**Comment by DevilXD** [comment] 2023-12-06 20:47
This is a duplicate of #301. There's no solution to it yet.

**Closed by DevilXD** 2023-12-06 20:47 UTC
Labels: Bug, Duplicate

**Comment by biast12** [comment] 2023-12-06 20:50
good, just wanted to make sure it wasn't missed
