### ISSUE TITLE
App stop working

### ISSUE THREAD

**Issue by Zhanyee** [DevilXD/TwitchDropsMiner#573] opened 2024-10-06 14:15 UTC
Every few hours this error is occourring and the bot stops farming, what should I do?
I've tryied the release version, the Development build version, I've tried to delete and make a new file again, execute with administrator rights, anything worked.

> `00:09:48: Fatal error encountered:
> 00:09:48: 
> 00:09:48: Traceback (most recent call last):
> 00:09:48:   File "main.py", line 155, in main
> 00:09:48:   File "twitch.py", line 587, in run
> 00:09:48:   File "twitch.py", line 648, in _run
> 00:09:48:   File "inventory.py", line 259, in claim
> 00:09:48:   File "inventory.py", line 142, in claim
> 00:09:48:   File "inventory.py", line 158, in _claim
> 00:09:48:   File "twitch.py", line 1387, in gql_request
> 00:09:48: exceptions.GQLException: [{'message': 'service error', 'path': ['claimDropRewards']}]
> 00:09:48: 
> 00:09:48: Exiting...
> 00:09:48: 
> 00:09:48: Application Terminated.
> 00:09:48: Close the window to exit the application.`

**Comment by DevilXD** [comment] 2024-10-06 14:27
Duplicate of #415.

**Closed by DevilXD** 2024-10-06 14:27 UTC
Labels: Bug, Duplicate
