### ISSUE TITLE
What is the reason for this and how can I fix it?

### ISSUE THREAD

**Issue by qzrsa** [DevilXD/TwitchDropsMiner#206] opened 2023-05-28 03:28 UTC
19:27:26: Fatal error encountered:
19:27:26: 
19:27:26: Traceback (most recent call last):
19:27:26:   File "main.py", line 170, in <module>
19:27:26:   File "asyncio\base_events.py", line 647, in run_until_complete
19:27:26:   File "twitch.py", line 764, in run
19:27:26:   File "twitch.py", line 783, in _run
19:27:26:   File "twitch.py", line 1454, in get_auth
19:27:26:   File "twitch.py", line 517, in validate
19:27:26:   File "twitch.py", line 526, in _validate
19:27:26:   File "contextlib.py", line 181, in __aenter__
19:27:26:   File "twitch.py", line 1479, in request
19:27:26:   File "gui.py", line 1955, in coro_unless_closed
19:27:26:   File "aiohttp\client.py", line 1125, in send
19:27:26:   File "aiohttp\client.py", line 536, in _request
19:27:26:   File "aiohttp\connector.py", line 540, in connect
19:27:26:   File "aiohttp\connector.py", line 901, in _create_connection
19:27:26:   File "aiohttp\connector.py", line 1175, in _create_direct_connection
19:27:26:   File "aiohttp\connector.py", line 980, in _wrap_create_connection
19:27:26:   File "asyncio\base_events.py", line 1050, in create_connection
19:27:26:   File "asyncio\base_events.py", line 961, in _connect_sock
19:27:26:   File "asyncio\proactor_events.py", line 703, in sock_connect
19:27:26: RuntimeError: await wasn't used with future
19:27:26: 
19:27:26: 正在退出...
19:27:27: 
19:27:27: 应用程序已终止，请关闭窗口以退出应用程序。

**Comment by DevilXD** [comment] 2023-05-28 07:47
This is a duplicate of #80.

**Closed by DevilXD** 2023-05-28 07:47 UTC
Labels: Bug, Duplicate
