### ISSUE TITLE
Report BUG

### ISSUE THREAD

**Issue by lls8475** [DevilXD/TwitchDropsMiner#158] opened 2023-03-10 10:50 UTC
07:17:34: 正在观看: Call of Duty
07:20:38: 观看直播获得积分:  10, 总积分: 21390
07:25:37: 观看直播获得积分:  10, 总积分: 21400
07:30:34: 观看直播获得积分:  10, 总积分: 21410
07:30:35: 领取的积分奖励: 50
07:30:36: 观看直播获得积分:  50, 总积分: 21460
07:35:34: 观看直播获得积分:  10, 总积分: 21470
07:40:31: 观看直播获得积分:  10, 总积分: 21480
07:45:30: 观看直播获得积分:  10, 总积分: 21490
07:45:31: 领取的积分奖励: 50
07:45:31: 观看直播获得积分:  50, 总积分: 21540
07:46:31: ERROR: Exception in task
07:46:31: Traceback (most recent call last):
07:46:31:   File "utils.py", line 96, in wrapper
07:46:31:   File "twitch.py", line 1332, in process_drops
07:46:31:   File "inventory.py", line 202, in claim
07:46:31:   File "inventory.py", line 120, in claim
07:46:31:   File "inventory.py", line 136, in _claim
07:46:31:   File "twitch.py", line 1534, in gql_request
07:46:31: exceptions.MinerException: GQL error: [{'message': 'PersistedQueryNotFound'}]
07:50:29: 观看直播获得积分:  10, 总积分: 21550
07:55:27: 观看直播获得积分:  10, 总积分: 21560
08:00:26: 观看直播获得积分:  10, 总积分: 21570
08:00:26: 领取的积分奖励: 50
08:00:27: 观看直播获得积分:  50, 总积分: 21620
08:05:26: 观看直播获得积分:  10, 总积分: 21630
08:10:22: 观看直播获得积分:  10, 总积分: 21640
08:15:22: 观看直播获得积分:  10, 总积分: 21650
08:15:23: 领取的积分奖励: 50
08:15:23: 观看直播获得积分:  50, 总积分: 21700
08:17:38: Fatal error encountered:
08:17:38: 
08:17:38: Traceback (most recent call last):
08:17:38:   File "main.py", line 175, in <module>
08:17:38:   File "asyncio\base_events.py", line 616, in run_until_complete
08:17:38:   File "twitch.py", line 759, in run
08:17:38:   File "twitch.py", line 812, in _run
08:17:38:   File "inventory.py", line 202, in claim
08:17:38:   File "inventory.py", line 120, in claim
08:17:38:   File "inventory.py", line 136, in _claim
08:17:38:   File "twitch.py", line 1534, in gql_request
08:17:38: exceptions.MinerException: GQL error: [{'message': 'PersistedQueryNotFound'}]
08:17:38: 
08:17:38: 正在退出...
08:17:39: 
08:17:39: 应用程序已终止，请关闭窗口以退出应用程序。

program stop
![QQ截图20230310185007](https://user-images.githubusercontent.com/31964733/224297239-7d7b05a1-6824-4c94-8e1c-f0fecc4cae68.jpg)

**Comment by lls8475** [comment] 2023-03-10 11:04
i see this bug has been fixed
but I don't understand Python to exe

**Comment by matarife123** [comment] 2023-03-10 13:35
> Veo que este error se ha solucionado pero no entiendo Python to exe

x2 :/ 
can someone upload the exe?

**Comment by DevilXD** [comment] 2023-03-10 14:58
This is a duplicate of #138.

**Closed by DevilXD** 2023-03-10 14:58 UTC
Labels: Bug, Duplicate
