### ISSUE TITLE
Campaign Selector | Campaign progress desync

### ISSUE THREAD

**Issue by Hadimhz** [DevilXD/TwitchDropsMiner#389] opened 2023-12-12 19:21 UTC
Is it possible to add a selector to pick the campaign being farmed, or a priority list for the campaigns to pick the ones you like the most first?

\+ I've noticed some weird behavior with it picking a streamer and grinding for a campaign but since that streamer has his own campaign it'd count the time to the wrong one and it causes it to de-sync. The refresh button does nothing to fix it, so perhaps a check to see which campaign gets affected after a few minutes to show the proper one. 

Loving the app so far, amazing work!

**Comment by Hadimhz** [comment] 2023-12-12 19:24
You can see on the app it shows that the trophy is at 53% progress
![21_22_22+137_12_12_2023_Twitch_Drops_Miner_(by_DevilXD)](https://github.com/DevilXD/TwitchDropsMiner/assets/40409775/8659a076-84c7-477b-8462-d08be38dddeb)

But in reality since TwitchRivals Has their own campaign the progress goes to that rather than the generic one
![21_22_40+925_12_12_2023_chrome](https://github.com/DevilXD/TwitchDropsMiner/assets/40409775/c10f0b42-0fa5-4024-950d-31cc0d6fdbaa)
![21_23_05+748_12_12_2023_chrome](https://github.com/DevilXD/TwitchDropsMiner/assets/40409775/82598666-07c2-4352-9e35-1e91b5339a24)

**Comment by DevilXD** [comment] 2023-12-12 21:57
I'm not sure what to make out of this issue. Is this an enhancement suggestion, or a bug report? It looks like a bug report, so I'm treating it as one. If you'd like to suggest anything, please do so in a separate issue.

**Comment by DevilXD** [comment] 2023-12-12 21:58
The progress can differ between the miner and website, per #301. This makes it a duplicate of that issue.

**Closed** 2023-12-12 21:58 UTC
Labels: Bug, Duplicate
