### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by ZoloftCSGO** [DevilXD/TwitchDropsMiner#115] opened 2023-01-07 14:08 UTC
Idk how to mark this as a feature request.
However would it be possible with this program to make it "mine" points whilst no drops are avalible through a list of channels or your current followers?

**Comment by ManInDark** [comment] 2023-01-07 14:30
I'd appreciate that feature too.

**Comment by DevilXD** [comment] 2023-01-07 18:28
This is a duplicate of an issue I literally just closed this morning. The answer is "no", and you can read about why in #114.

This is a drops-focused application and I intend for it to stay that way. If you're looking for something of a broader scope, try searching for a different twitch miner project.

**Closed by DevilXD** 2023-01-07 18:28 UTC
Labels: Duplicate, Enhancement
