### ISSUE TITLE
Time data does not match format

### ISSUE THREAD

**Issue by SPRINKILL** [DevilXD/TwitchDropsMiner#345] opened 2023-11-01 02:35 UTC
Hi.
When starting TDM from run_dev.bat I see this error:
![Скриншот 01-11-2023 053337](https://github.com/DevilXD/TwitchDropsMiner/assets/149550641/c0b77fc6-c337-49d0-ac84-2e6c15ed0290)

I am using Windows 10 Pro on Proxmox VM

**Comment by SPRINKILL** [comment] 2023-11-01 06:17
Yes. 
Also in version [v15](https://github.com/DevilXD/TwitchDropsMiner/releases/tag/v15)

**Comment by DevilXD** [comment] 2023-11-01 09:32
@SPRINKILL v15 isn't supported anymore, and won't work - don't use it. This issue was already fixed by #314 a month ago. This is a duplicate of #340.

**Closed by DevilXD** 2023-11-01 09:32 UTC
Labels: Bug, Duplicate
