### ISSUE TITLE
Can you support linux

### ISSUE THREAD

**Issue by Wyatt323** [DevilXD/TwitchDropsMiner#121] opened 2023-01-22 11:21 UTC
Windows will not be turned on for a long time, but I have a linux server that is turned on 24H. I believe many people are like me. Can you support it?

**Comment by DevilXD** [comment] 2023-01-22 14:28
Linux is already supported, I just don't release a binary for it because I don't have the environment to do so. You'd need to build one yourself. See #113 and #35 for more details.

Also, this is technically a duplicate of #113, so it's getting closed.

**Closed by DevilXD** 2023-01-22 14:28 UTC
Labels: Duplicate, Enhancement
