### ISSUE TITLE
Fatal Error Issue 

### ISSUE THREAD

**Issue by Stiphr** [DevilXD/TwitchDropsMiner#143] opened 2023-02-21 00:44 UTC
![image](https://user-images.githubusercontent.com/68784883/220220033-fddccbd0-a6b2-4c31-842f-c3f8463b1399.png)

Giving this error (Random timing)

System:
AWS RDP
Windows Server 2022

**Comment by GreenFox66** [comment] 2023-02-21 03:27
I had the same problem on windows 10

**Comment by DevilXD** [comment] 2023-02-21 06:16
This is a duplicate of #138.

**Closed by DevilXD** 2023-02-21 06:16 UTC
Labels: Bug, Duplicate

**Comment by ZeorymerX** [comment] 2023-02-22 14:48
the same problem
