### ISSUE TITLE
ERROR: Exception in _watch_loop task

### ISSUE THREAD

**Issue by 997133091** [DevilXD/TwitchDropsMiner#550] opened 2024-09-01 04:27 UTC
I'm using the release Reference commit: v16.dev.5456986

It seems that the Miner can work for a while about 10mins, then this error message poped up:

12:23:50: ERROR: Exception in _watch_loop task
12:23:50: Traceback (most recent call last):
12:23:50:   File "utils.py", line 132, in wrapper
12:23:50:   File "twitch.py", line 860, in _watch_loop
12:23:50:   File "channel.py", line 385, in send_watch
12:23:50:   File "contextlib.py", line 199, in __aenter__
12:23:50:   File "twitch.py", line 1285, in request
12:23:50:   File "gui.py", line 2147, in coro_unless_closed
12:23:50:   File "aiohttp\client.py", line 1337, in send
12:23:50:   File "aiohttp\client.py", line 586, in _request
12:23:50: aiohttp.client_exceptions.InvalidUrlClientError
12:23:50: Exiting...
12:23:50: 
12:23:50: Application Terminated.
12:23:50: Close the window to exit the application.

**Comment by DevilXD** [comment] 2024-09-01 07:38
Hello,

First of, this is a duplicate of #504. The error isn't the same, but the cause is.

Second of, there was a temporary debug code added, that will print the offending response to the output window - it would show up right above the line that starts with "ERROR". You haven't included it, and I'm assuming that it's no longer possible for you to include it either, so this report is pretty much useless. If you happen to run into it again, please use #504 to report the entire contents of your output window, including the part right before the error.

**Closed by DevilXD** 2024-09-01 07:38 UTC
