### ISSUE TITLE
Fatal error encountered

### ISSUE THREAD

**Issue by wsaddede** [DevilXD/TwitchDropsMiner#372] opened 2023-11-26 11:31 UTC
19:29:29: Fatal error encountered:
19:29:29: 
19:29:29: Traceback (most recent call last):
19:29:29:   File "main.py", line 175, in <module>
19:29:29:   File "asyncio\base_events.py", line 616, in run_until_complete
19:29:29:   File "twitch.py", line 759, in run
19:29:29:   File "twitch.py", line 801, in _run
19:29:29:   File "twitch.py", line 1589, in fetch_inventory
19:29:29:   File "twitch.py", line 1590, in <dictcomp>
19:29:29:   File "utils.py", line 74, in timestamp
19:29:29:   File "_strptime.py", line 568, in _strptime_datetime
19:29:29:   File "_strptime.py", line 349, in _strptime
19:29:29: ValueError: time data '2023-11-24T20:29:59.756Z' does not match format '%Y-%m-%dT%H:%M:%SZ'
19:29:29:  
then ，end

**Comment by DevilXD** [comment] 2023-11-26 12:49
Duplicate of #345.

**Closed by DevilXD** 2023-11-26 12:49 UTC
Labels: Bug, Duplicate
