### ISSUE TITLE
Program:Win32/Wacapew.C!ml

### ISSUE THREAD

**Issue by rrichard24** [DevilXD/TwitchDropsMiner#335] opened 2023-10-24 14:38 UTC
The latest development build from 2023-10-21 21:23:24+00:00; Reference commit: https://github.com/DevilXD/TwitchDropsMiner/commit/bb51bf740070d867d7973fbe6c014b347b349064

Windows 11 Security reported:

<img width="460" alt="image" src="https://github.com/DevilXD/TwitchDropsMiner/assets/148883810/330d674a-2ca8-4318-92de-8b5b5143d3cf">
<img width="463" alt="image" src="https://github.com/DevilXD/TwitchDropsMiner/assets/148883810/3fd0d841-0fef-4a0d-be45-60e58d0ee6d6">

Also after reinstalling:

<img width="458" alt="image" src="https://github.com/DevilXD/TwitchDropsMiner/assets/148883810/ae07f779-07e0-4627-9c3f-f68e1e8f3486">
<img width="458" alt="image" src="https://github.com/DevilXD/TwitchDropsMiner/assets/148883810/11b9ad24-1521-447f-b5bd-a3a4a27fbcde">

**Comment by DevilXD** [comment] 2023-10-24 19:23
This is a duplicate of $333, #315, #284, #270, #249, #217, #209 and #13. Please, I just closed one yesterday. Why can't people do the very minimum of research first is beyond me, really.

**Closed by DevilXD** 2023-10-24 19:23 UTC
Labels: Duplicate, Help / Issue

**Comment by rrichard24** [comment] 2023-10-24 19:34
> This is a duplicate of #333, #315, #284, #270, #249, #217, #209 and #13. Please, I just closed one yesterday. Why can't people do the very minimum of research first is beyond me, really.

Thank you for the reply. Not very smart of me, but googled it actually everywhere except in the issues archive. Guess you should better put it in readme, would spare you some nerves.

**Comment by spuukii** [comment] 2023-10-24 19:50
> > This is a duplicate of #333, #315, #284, #270, #249, #217, #209 and #13. Please, I just closed one yesterday. Why can't people do the very minimum of research first is beyond me, really.
> 
> Thank you for the reply. Not very smart of me, but googled it actually everywhere except in the issues archive. Guess you should better put it in readme, would spare you some nerves.

It is in the README.

![image](https://github.com/DevilXD/TwitchDropsMiner/assets/17623860/2b7df810-d15b-43e0-9fdd-4b65fcc14669)
