### ISSUE TITLE
PersistedQueryNotFound GQL error

### ISSUE THREAD

**Issue by matarife123** [DevilXD/TwitchDropsMiner#138] opened 2023-02-16 19:50 UTC
![Sin título](https://user-images.githubusercontent.com/110930030/219471838-63b78c17-4de5-44fa-be92-b07254701fab.png)

**Comment by allanf181** [comment] 2023-02-17 15:49
Same here 
```
12:49:17: Fatal error encountered:
12:49:17: 
12:49:17: Traceback (most recent call last):
12:49:17:   File "main.py", line 175, in <module>
12:49:17:   File "asyncio\base_events.py", line 616, in run_until_complete
12:49:17:   File "twitch.py", line 759, in run
12:49:17:   File "twitch.py", line 801, in _run
12:49:17:   File "twitch.py", line 1594, in fetch_inventory
12:49:17:   File "twitch.py", line 1534, in gql_request
12:49:17: exceptions.MinerException: GQL error: [{'message': 'PersistedQueryNotFound'}]
12:49:17: 
12:49:17: Exiting...
12:49:18: 
12:49:18: Application Terminated.
12:49:18: Close the window to exit the application.
```

**Comment by notNSANE** [comment] 2023-02-17 15:57
same here.

**Comment by xeddmc** [comment] 2023-02-17 21:27
Same. I think twitch might have found a way to block the app. Could need an update

**Comment by Tristar7** [comment] 2023-02-17 21:59
Randomly random GQL requests fail or Twitch sends garbage. The tool needs to be much more error resilient and not crash on the faintest of error.

**Comment by MingY00** [comment] 2023-02-18 01:47
same here

**Comment by allanf181** [comment] 2023-02-18 03:06
Log with log level CALL
```
...
00:02:29: INFO: sure_ goes OFFLINE
00:02:30: CALL: Channel update from websocket: sure_
00:02:41: CALL: Drop update from websocket: Holy Flare (Halo Infinite, 59/60)
00:03:42: Earned points for watching:  10, total: 370
00:03:42: CALL: Drop update from websocket: Holy Flare (Halo Infinite, 60/60)
00:03:43: Claimed drop: Halo Infinite "Holy Flare" Charm (1/1)
00:03:43: Claimed bonus points: 50
00:03:43: Earned points for watching:  50, total: 420
00:03:53: CALL: Maintenance task waiting until: 00:33:53 (Points)
00:03:53: INFO: Websocket[7] stopped.
00:03:53: INFO: Websocket[6] stopped.
00:03:53: INFO: Websocket[5] stopped.
00:03:53: INFO: Websocket[4] stopped.
00:03:53: INFO: Websocket[3] stopped.
00:03:53: INFO: Websocket[2] stopped.
00:03:53: INFO: Websocket[1] stopped.
00:03:55: Fatal error encountered:
00:03:55: 
00:03:55: Traceback (most recent call last):
00:03:55:   File "main.py", line 175, in <module>
00:03:55:   File "asyncio\base_events.py", line 616, in run_until_complete
00:03:55:   File "twitch.py", line 759, in run
00:03:55:   File "twitch.py", line 908, in _run
00:03:55:   File "twitch.py", line 1677, in get_live_streams
00:03:55:   File "twitch.py", line 1534, in gql_request
00:03:55: exceptions.MinerException: GQL error: [{'message': 'PersistedQueryNotFound'}]
00:03:55: 
00:03:55: Exiting...
00:03:55: INFO: Websocket[0] stopped.
00:03:55: 
00:03:55: Application Terminated.
00:03:55: Close the window to exit the application.
```

**Comment by emaf94** [comment] 2023-02-18 07:00
Same problem

**Comment by Nana7mi12** [comment] 2023-02-18 10:18
me too

**Comment by dethmourne** [comment] 2023-02-18 12:43
Yup.

**Comment by kartax4** [comment] 2023-02-18 12:52
Same problem after reinstall
`13:51:56: Fatal error encountered:
13:51:56: 
13:51:56: Traceback (most recent call last):
13:51:56:   File "main.py", line 175, in <module>
13:51:56:   File "asyncio\base_events.py", line 616, in run_until_complete
13:51:56:   File "twitch.py", line 759, in run
13:51:56:   File "twitch.py", line 908, in _run
13:51:56:   File "twitch.py", line 1677, in get_live_streams
13:51:56:   File "twitch.py", line 1534, in gql_request
13:51:56: exceptions.MinerException: GQL error: [{'message': 'PersistedQueryNotFound'}]
13:51:56: 
13:51:56: Exiting...
13:51:56: 
13:51:56: Application Terminated.
13:51:56: Close the window to exit the application.`

**Comment by hifocus** [comment] 2023-02-18 14:57
Can reproduce

**Comment by lvg3618** [comment] 2023-02-18 16:57
same

**Comment by Jokerverse** [comment] 2023-02-18 21:11
Im facing the same problem here and temporarily fixing it by restarting the app after every claim

**Comment by DevilXD** [comment] 2023-02-19 10:14
Hi. Hmm, this just looks like the GQL queries the miner is using have became really old, so old that Twitch moved onto new ones in the mean time. This shouldn't be too hard to fix, assuming the new queries didn't remove crucial info I was using before.

**Comment by DevilXD** [comment] 2023-02-19 10:41
As I said, simply putting in new hashes worked: https://github.com/DevilXD/TwitchDropsMiner/commit/bfd389392127488a963fc696583fc140745494b8

This is already fixed in dev, but it's gonna take a while to make it to official release. In the mean time, one can rebuild the application on their side by following the building process: https://github.com/DevilXD/TwitchDropsMiner/wiki/Setting-up-the-environment,-building-and-running

**Comment by matarife123** [comment] 2023-02-19 10:53
thanks you for all :D

**Comment by aalbouy** [comment] 2023-02-19 11:03
Hi,

Thanks for the quick fix ! 
I just rebuild the project using new hashes, yet I face another error : 

```
11:57:09: Fatal error encountered:
11:57:09: 
11:57:09: Traceback (most recent call last):
11:57:09:   File "E:\Documents\Documents\PythonScripts\TwitchDropMiner_main\main.py", line 175, in <module>
11:57:09:     loop.run_until_complete(client.run())
11:57:09:   File "C:\Users\adri8\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 650, in run_until_complete
11:57:09:     return future.result()
11:57:09:            ^^^^^^^^^^^^^^^
11:57:09:   File "E:\Documents\Documents\PythonScripts\TwitchDropMiner_main\twitch.py", line 759, in run
11:57:09:     await self._run()
11:57:09:   File "E:\Documents\Documents\PythonScripts\TwitchDropMiner_main\twitch.py", line 908, in _run
11:57:09:     new_channels.update(await self.get_live_streams(game))
11:57:09:                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
11:57:09:   File "E:\Documents\Documents\PythonScripts\TwitchDropMiner_main\twitch.py", line 1687, in get_live_streams
11:57:09:     return [
11:57:09:            ^
11:57:09:   File "E:\Documents\Documents\PythonScripts\TwitchDropMiner_main\twitch.py", line 1688, in <listcomp>
11:57:09:     Channel.from_directory(self, stream_channel_data["node"])
11:57:09:   File "E:\Documents\Documents\PythonScripts\TwitchDropMiner_main\channel.py", line 114, in from_directory
11:57:09:     self._stream = Stream.from_directory(self, data)
11:57:09:                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
11:57:09:   File "E:\Documents\Documents\PythonScripts\TwitchDropMiner_main\channel.py", line 64, in from_directory
11:57:09:     tags=data["tags"],
11:57:09:          ~~~~^^^^^^^^
11:57:09: KeyError: 'tags'
11:57:09: 
11:57:09: Exiting...
11:57:09: 
11:57:09: Application Terminated.
11:57:09: Close the window to exit the application.
```

I tried deleting the cookies.jar just in case, same issue.. 

I'm not sure if it should be a new issue, let my know !

**Comment by DevilXD** [comment] 2023-02-19 13:49
Yeah, I worried that might be an issue - it's the result of Twitch updating their queries. Now there are only "freeFormTags" available on that data object there, meaning the miner can't determine if there is a drops tag available or not. I'll try searching for a solution, but that'll take longer than a simple hashes update like this.

**Comment by aalbouy** [comment] 2023-02-19 14:01
I hacked a thing using the "freeFormTags" and some translation of "DropsEnabled" value that I found, but I guess that's up to the streamer to add these tags ? So it's not perfect...

**Comment by DevilXD** [comment] 2023-02-19 14:17
The point isn't extracting the tag, but more about the tag's meaning. It doesn't look like that tag means what you think it does anymore, and the actual information telling others whether or not the drops are enabled on a channel or not, isn't available anymore. Streamers add these because that's how it used to function before, that others are used to seeing, for increased views.

**Comment by DevilXD** [comment] 2023-02-19 15:24
This is far from ideal, but it works: https://github.com/DevilXD/TwitchDropsMiner/commit/793fb5ccaf579c99cf3cc75d816362060697b639

**Comment by Walter-o** [comment] 2023-02-19 16:52
Isn't it a good idea to generate the GQL hashes live inside the program so they can never expire?

**Comment by DevilXD** [comment] 2023-02-19 21:20
It's not that easy. Twitch does accept raw GQL queries with no hashes, but since none of the Twitch's official apps uses those, it'd be really easy to see someone doing custom queries on the system. One way I could think of is parsing the web client to extract hashes out of (since they're hardcoded there), but the GQL operations don't change that often (this is like the 2nd breaking change ever since this project started existing) so it was never smth to really worry about.

**Comment by ZeorymerX** [comment] 2023-02-22 14:48
22:46:32: Fatal error encountered:
22:46:32: 
22:46:32: Traceback (most recent call last):
22:46:32:   File "main.py", line 175, in <module>
22:46:32:   File "asyncio\base_events.py", line 616, in run_until_complete
22:46:32:   File "twitch.py", line 759, in run
22:46:32:   File "twitch.py", line 801, in _run
22:46:32:   File "twitch.py", line 1594, in fetch_inventory
22:46:32:   File "twitch.py", line 1534, in gql_request
22:46:32: exceptions.MinerException: GQL error: [{'message': 'PersistedQueryNotFound'}]
22:46:32: 
22:46:32: 正在退出...
22:46:33: 
22:46:33: 应用程序已终止，请关闭窗口以退出应用程序。

**Comment by Jokerverse** [comment] 2023-02-22 19:17
I rebuilt the application from the latest dev files and it works fine, you can do this as a temporarily option till @DevilXD releases the official release.
The tutorial is super easy just follow the steps
https://github.com/DevilXD/TwitchDropsMiner/wiki/Setting-up-the-environment,-building-and-running

**Comment by skupfer** [comment] 2023-02-23 18:39
```19:37:16: Traceback (most recent call last):
19:37:16:   File "main.py", line 175, in <module>
19:37:16:   File "asyncio\base_events.py", line 642, in run_until_complete
19:37:16:   File "twitch.py", line 759, in run
19:37:16:   File "twitch.py", line 812, in _run
19:37:16:   File "inventory.py", line 202, in claim
19:37:16:   File "inventory.py", line 120, in claim
19:37:16:   File "inventory.py", line 136, in _claim
19:37:16:   File "twitch.py", line 1534, in gql_request
19:37:16: exceptions.MinerException: GQL error: [{'message': 'PersistedQueryNotFound'}]```

Happened due to having an Unclaimed Item (from NMS).

**Comment by EmiMathesi** [comment] 2023-02-24 08:58
@DevilXD Hi, I have the same problem in the new version even after replacing the files, but much less often with a 1/15 chance every drop change

**Comment by DevilXD** [comment] 2023-02-24 12:05
I may need to dig deeper into the cause of this. It could be that Twitch is actually juggling these together with raw queries now, meaning it sends the hashed version, and if it fails with this error, it sends the actual query. Ever since v15 release, I've had pretty much no available time to do much with this project, but I'll try once I can find some.

**Comment by Luckz** [comment] 2023-02-24 18:10
Here it's more of a 90%+ chance to crash in the startup phase ( https://github.com/DevilXD/TwitchDropsMiner/issues/138#issuecomment-1442253508 those exact lines) if a drop has not been claimed. After manually claiming the drop TDM can be started.

**Comment by notNSANE** [comment] 2023-02-24 18:21
I claim the drops automatically via an extension and the app still randomly crashes half of the time

**Comment by EffortlessFury** [comment] 2023-02-24 19:22
As an aside, would you see any value in the implementation of a platform agnostic notification library to let users know if there's a crash?

**Comment by connorgallopo** [comment] 2023-02-24 21:10
For the time being I just wrote a script that kills and restarts the application every hour. And that runs on my server for 100% uptime

**Comment by DevilXD** [comment] 2023-02-24 21:11
It sounds like the drop claim GQL operation hash changed again. I actually had 4 unclaimed drops in my own inventory, so getting my hands on the new hash was quite simple: https://github.com/DevilXD/TwitchDropsMiner/commit/466a3aa8f2982eca2e4c441cd254aa01941d17e6

It should work again. I'd like to consider parsing these out of the Twitch js source code, but it's yet another complex thing to implement, with too little free time on my hands, so for now this will have to do.

**Comment by connorgallopo** [comment] 2023-02-24 21:11
But maybe a good bandaid would be to have a restart threshold with a setting to enable/disable. Like if an error is raised we can reload the app and try to reconnect.

**Comment by DevilXD** [comment] 2023-02-24 21:16
The problem is that, this crash involved failed to claim a drop. Unclaimed drops are attempted to be claimed shortly after the application starts, as a finishing part of refreshing / fetching the current inventory. Adding anything related to "auto restart" would just put it into a loop, where it loads in, tries to claim, breaks and restarts. Adding any form of automatic error handling by restarting is thus completely pointless from my perspective, and I won't be adding any, probably ever.

**Comment by EffortlessFury** [comment] 2023-02-24 21:34
> The problem is that, this crash involved failed to claim a drop. Unclaimed drops are attempted to be claimed shortly after the application starts, as a finishing part of refreshing / fetching the current inventory. Adding anything related to "auto restart" would just put it into a loop, where it loads in, tries to claim, breaks and restarts. Adding any form of automatic error handling by restarting is thus completely pointless from my perspective, and I won't be adding any, probably ever.

What's strange is that this is true..._sometimes_. Sometimes I'll restart it and it'll claim no problem. But you're right, if at any point it gets stuck and can't be unstuck without manual claiming on the site, auto-restart won't help.

**Comment by EmiMathesi** [comment] 2023-02-24 22:08
Is it possible to make a limit on the number of unsatisfactory attempts? For example, 3 requests with different time intervals so that a single request does not break the entire program, but also endless loops do not happen?

**Comment by DevilXD** [comment] 2023-02-25 09:32
> Sometimes I'll restart it and it'll claim no problem.

This does not facilitate adding an auto restart system either, because it's not supposed to break - ever. If the application exits in a fatal error, it needs to be worked on more and fixed, not mindlessly restarted, as that doesn't fix the root cause of the crash.

> Is it possible to make a limit on the number of unsatisfactory attempts? For example, 3 requests with different time intervals so that a single request does not break the entire program, but also endless loops do not happen?

The thing is, this is already a thing. All web requests have an endless loop handler that suspends the execution in case of network problems, such as Twitch responding with a 5XX or simply timing out the response. This crash isn't related to any of that, it's related to Twitch intentionally changing things on their end, and this application not being ready to adjust accordingly. For now, as I said, each GQL request uses a hard-coded operation hash, that needs to be manually updated (like I did so in https://github.com/DevilXD/TwitchDropsMiner/commit/466a3aa8f2982eca2e4c441cd254aa01941d17e6) if Twitch would ever decide to change the operation (which they did recently, which caused this error). A better system than that might be put into place to avoid breakages in cases like that, but this is out of the scope of this issue, and I'd need to have the time to design and implement it too, which I don't currently have. If anyone would like to help the project, I'm open to discussion and giving pointers on how smth like that would likely need to look like.

**Comment by Luckz** [comment] 2023-02-25 22:00
> If the application exits in a fatal error, it needs to be worked on more and fixed, not mindlessly restarted, as that doesn't fix the root cause of the crash.

As you know (and this is sure off-topic here) there's little resilience to interweb interruptions, or other occasions where TDM fails without it being a 'proper bug'. For the end user experience it would be very much preferable if one didn't have to check in on it every few hours to make sure it's not on Terminated.

**Comment by DevilXD** [comment] 2023-02-26 09:36
> there's little resilience to interweb interruptions

The application already has the code to handle all of the cases. If not all of them are handled yet, the goal is for it to be able to do so.

> other occasions where TDM fails without it being a 'proper bug'

Like? Please show me an issue where restarting the application would miraculously not lead to you running into it again? This sounds like a straight up false claim and wishful thinking here. All "proper bugs" are either the fault of existing code not accounting for a condition I missed (my fault), or Twitch changing around the data they provide (Twitch's fault), and both of these cases are to be fixed to maintain this program in a working condition. Where's your "fails without proper bug"?

**Comment by allanf181** [comment] 2023-02-28 01:00
> The thing is, this is already a thing. All web requests have an endless loop handler that suspends the execution in case of network problems, such as Twitch responding with a 5XX or simply timing out the response. This crash isn't related to any of that, it's related to Twitch intentionally changing things on their end, and this application not being ready to adjust accordingly. For now, as I said, each GQL request uses a hard-coded operation hash, that needs to be manually updated (like I did so in https://github.com/DevilXD/TwitchDropsMiner/commit/466a3aa8f2982eca2e4c441cd254aa01941d17e6) if Twitch would ever decide to change the operation (which they did recently, which caused this error). A better system than that might be put into place to avoid breakages in cases like that, but this is out of the scope of this issue, and I'd need to have the time to design and implement it too, which I don't currently have. If anyone would like to help the project, I'm open to discussion and giving pointers on how smth like that would likely need to look like.

apparently this hash change was not recent, almost 1 year ago there were already people using this hash

https://github.com/search?q=a455deea71bdc9015b78eb49f4acfbce8baa7ccbedd28e549bb025bd0f751930&type=code

**Comment by DevilXD** [comment] 2023-02-28 06:21
I don't track changes of these in any way right now, so that's possible. The approach is that if the hash works, there's no reason to touch it. If it doesn't, it's just a matter of replacing it with a new one. The absolute best solution would be parsing the twitch core JS files for any changes to the commands and their hashes, but that again, requires research, design and implementation, and time of course, which I don't really have in large quantities right now.

**Comment by PreLiquid** [comment] 2023-03-03 17:04
> Im facing the same problem here and temporarily fixing it by restarting the app after every claim

me too. But recently the way couldn't work...

**Comment by TeKno200** [comment] 2023-03-03 21:34
Hello, good afternoon, someone who can help me to have an updated build of the application, I don't have any kind of programming knowledge, I tried to make one but I get stuck in setup_env.bat with requierements.txt and I don't know what to do, I don't understand anything.

**Comment by EffortlessFury** [comment] 2023-03-03 23:34
@TeKno200 At the very bottom of the Readme (the main page of this project) is a link to the Wiki with instructions on how to setup the development environment. Hopefully that'll help.

**Comment by TeKno200** [comment] 2023-03-04 00:34
I tried to do everything I could but I always get stuck here, I read [requirements.txt](https://github.com/DevilXD/TwitchDropsMiner/files/10887085/requirements.txt) and it makes everything even more confusing

![Captura de pantalla_20230303_212623](https://user-images.githubusercontent.com/126040284/222860503-05ea5437-ed3f-4f7d-92b1-04307e0db250.png)

I don't have the slightest idea of ​​what I have to do or how I have to do it, as I already said I don't have the slightest idea of ​​programming and at most I'm capable of editing a .txt

**Comment by DevilXD** [comment] 2023-03-04 07:41
@TeKno200 Please verify that the `env` folder is created properly after running that script, and then there's a `scripts` folder inside, with `pip.exe` file in there. If so, you should be getting no such errors. If not, the venv folder isn't getting created properly, and you'll most likely need to run it with administrative access, or consider temporarily disabling the AV in case it'd interfere with the venv creation.

**Comment by TeKno200** [comment] 2023-03-04 20:55
> @TeKno200 Please verify that the `env` folder is created properly after running that script, and then there's a `scripts` folder inside, with `pip.exe` file in there. If so, you should be getting no such errors. If not, the venv folder isn't getting created properly, and you'll most likely need to run it with administrative access, or consider temporarily disabling the AV in case it'd interfere with the venv creation.

I just reinstalled Python with the wiki guide and everything worked correctly, I think the wrong option was that the files didn't open with cmd.exe and so far the build works perfectly

**Comment by matarife123** [comment] 2023-03-07 06:36
> > @TeKno200 Please verify that the `env` folder is created properly after running that script, and then there's a `scripts` folder inside, with `pip.exe` file in there. If so, you should be getting no such errors. If not, the venv folder isn't getting created properly, and you'll most likely need to run it with administrative access, or consider temporarily disabling the AV in case it'd interfere with the venv creation.
> 
> I just reinstalled Python with the wiki guide and everything worked correctly, I think the wrong option was that the files didn't open with cmd.exe and so far the build works perfectly

send V16 xD

**Comment by matarife123** [comment] 2023-03-10 14:15
> I tried to do everything I could but I always get stuck here, I read [requirements.txt](https://github.com/DevilXD/TwitchDropsMiner/files/10887085/requirements.txt) and it makes everything even more confusing
> 
> ![Captura de pantalla_20230303_212623](https://user-images.githubusercontent.com/126040284/222860503-05ea5437-ed3f-4f7d-92b1-04307e0db250.png)
> 
> I don't have the slightest idea of ​​what I have to do or how I have to do it, as I already said I don't have the slightest idea of ​​programming and at most I'm capable of editing a .txt

how did you solve it? and installed python and the problem persists

**Comment by TeKno200** [comment] 2023-03-10 18:54
> ![Sin título](https://user-images.githubusercontent.com/110930030/224352075-b5a8cf38-4a9f-43ea-a440-8033233b4a08.png)
> 
> > @matarife123 Make sure that you are following the guide closely. Every misstep like not checking a particular option, or not restarting your PC at the end, will result in that error. The guide should already cover everything needed for the building to work, so if you're getting a similar error, you didn't follow the guide properly.
> > Alternatively, you can try reaching out to me on Discord and I could try helping your directly.
> 
> I do everything exactly as in the guide and it gives me an error when executing setup_env, I use python 3.11

https://drive.google.com/file/d/1bMHz5e2OAy6IpvxQRHPvDaBKrkWkaXNx/view?usp=sharing
Here I leave the link of the application that I made. (I don't know if I can pass a link with an .exe any problem delete the link or notify)

**Comment by matarife123** [comment] 2023-03-10 18:56
> > ![Sin título](https://user-images.githubusercontent.com/110930030/224352075-b5a8cf38-4a9f-43ea-a440-8033233b4a08.png)
> > > @matarife123 Make sure that you are following the guide closely. Every misstep like not checking a particular option, or not restarting your PC at the end, will result in that error. The guide should already cover everything needed for the building to work, so if you're getting a similar error, you didn't follow the guide properly.
> > > Alternatively, you can try reaching out to me on Discord and I could try helping your directly.
> > 
> > 
> > I do everything exactly as in the guide and it gives me an error when executing setup_env, I use python 3.11
> 
> https://drive.google.com/file/d/1bMHz5e2OAy6IpvxQRHPvDaBKrkWkaXNx/view?usp=sharing Here I leave the link of the application that I made. (I don't know if I can pass a link with an .exe any problem delete the link or notify)

very thanks :D

**Comment by lls8475** [comment] 2023-03-11 05:07
i got it ！
1、[Git Installation](https://git-scm.com/downloads)
2、[Python Installation](https://www.python.org/downloads/https://www.python.org/downloads/)
all done
run bat
1、setup_env.bat
2、build.bat
all done
open folder dist  exe inside

**Comment by DevilXD** [comment] 2023-03-11 09:58
Yeah, I really don't know why some users can't get it to work, the guide already covers the entire process.

**Comment by zansbang** [comment] 2023-03-11 14:04
@DevilXD i got this error~

22:01:55: Fatal error encountered:
22:01:55: 
22:01:55: Traceback (most recent call last):
22:01:55:   File "main.py", line 175, in <module>
22:01:55:   File "asyncio\base_events.py", line 616, in run_until_complete
22:01:55:   File "twitch.py", line 759, in run
22:01:55:   File "twitch.py", line 778, in _run
22:01:55:   File "twitch.py", line 1449, in get_auth
22:01:55:   File "twitch.py", line 512, in validate
22:01:55:   File "twitch.py", line 521, in _validate
22:01:55:   File "contextlib.py", line 171, in __aenter__
22:01:55:   File "twitch.py", line 1474, in request
22:01:55:   File "gui.py", line 1963, in coro_unless_closed
22:01:55:   File "aiohttp\client.py", line 1125, in send
22:01:55:   File "aiohttp\client.py", line 536, in _request
22:01:55:   File "aiohttp\connector.py", line 540, in connect
22:01:55:   File "aiohttp\connector.py", line 901, in _create_connection
22:01:55:   File "aiohttp\connector.py", line 1175, in _create_direct_connection
22:01:55:   File "aiohttp\connector.py", line 980, in _wrap_create_connection
22:01:55:   File "asyncio\base_events.py", line 1010, in create_connection
22:01:55:   File "asyncio\base_events.py", line 924, in _connect_sock
22:01:55:   File "asyncio\proactor_events.py", line 702, in sock_connect
22:01:55: RuntimeError: await wasn't used with future
22:01:55: 
22:01:55: Exiting...
22:01:55: 
22:01:55: Application Terminated.
22:01:55: Close the window to exit the application.

**Comment by DevilXD** [comment] 2023-03-11 21:23
@zansbang A gentle reminder that you're supposed to search through existing issues first, before reporting anything: #80

**Comment by lls8475** [comment] 2023-03-12 05:37
> @DevilXD i got this error~
> 
> 22:01:55: Fatal error encountered: 22:01:55: 22:01:55: Traceback (most recent call last): 22:01:55: File "main.py", line 175, in 22:01:55: File "asyncio\base_events.py", line 616, in run_until_complete 22:01:55: File "twitch.py", line 759, in run 22:01:55: File "twitch.py", line 778, in _run 22:01:55: File "twitch.py", line 1449, in get_auth 22:01:55: File "twitch.py", line 512, in validate 22:01:55: File "twitch.py", line 521, in _validate 22:01:55: File "contextlib.py", line 171, in **aenter** 22:01:55: File "twitch.py", line 1474, in request 22:01:55: File "gui.py", line 1963, in coro_unless_closed 22:01:55: File "aiohttp\client.py", line 1125, in send 22:01:55: File "aiohttp\client.py", line 536, in _request 22:01:55: File "aiohttp\connector.py", line 540, in connect 22:01:55: File "aiohttp\connector.py", line 901, in _create_connection 22:01:55: File "aiohttp\connector.py", line 1175, in _create_direct_connection 22:01:55: File "aiohttp\connector.py", line 980, in _wrap_create_connection 22:01:55: File "asyncio\base_events.py", line 1010, in create_connection 22:01:55: File "asyncio\base_events.py", line 924, in _connect_sock 22:01:55: File "asyncio\proactor_events.py", line 702, in sock_connect 22:01:55: RuntimeError: await wasn't used with future 22:01:55: 22:01:55: Exiting... 22:01:55: 22:01:55: Application Terminated. 22:01:55: Close the window to exit the application.


system environment
win10  21H1  19043.1645
Git-2.39.2-64-bit
python-3.10.8-amd64

run *.bat  Use administrator privileges

you try

**Comment by notNSANE** [comment] 2023-03-15 20:05
> > ![Sin título](https://user-images.githubusercontent.com/110930030/224352075-b5a8cf38-4a9f-43ea-a440-8033233b4a08.png)
> > > @matarife123 Make sure that you are following the guide closely. Every misstep like not checking a particular option, or not restarting your PC at the end, will result in that error. The guide should already cover everything needed for the building to work, so if you're getting a similar error, you didn't follow the guide properly.
> > > Alternatively, you can try reaching out to me on Discord and I could try helping your directly.
> > 
> > 
> > I do everything exactly as in the guide and it gives me an error when executing setup_env, I use python 3.11
> 
> https://drive.google.com/file/d/1bMHz5e2OAy6IpvxQRHPvDaBKrkWkaXNx/view?usp=sharing Here I leave the link of the application that I made. (I don't know if I can pass a link with an .exe any problem delete the link or notify)

just a heads up, crashes at start

**Comment by scarabhub** [comment] 2023-03-25 13:05
![image](https://user-images.githubusercontent.com/126503486/227718886-543d13b0-02b8-4e2b-a964-2d49e7f94095.png)

**Comment by lls8475** [comment] 2023-03-26 04:51
> ![image](https://user-images.githubusercontent.com/126503486/227718886-543d13b0-02b8-4e2b-a964-2d49e7f94095.png)

this is BUG repaired
you need repackaging files to exe

**Comment by BjornGrylls** [comment] 2023-04-28 18:34
Same
```
19:50:27: Fatal error encountered:
19:50:27: 
19:50:27: Traceback (most recent call last):
19:50:27:   File "main.py", line 175, in <module>
19:50:27:   File "asyncio\base_events.py", line 616, in run_until_complete
19:50:27:   File "twitch.py", line 759, in run
19:50:27:   File "twitch.py", line 812, in _run
19:50:27:   File "inventory.py", line 202, in claim
19:50:27:   File "inventory.py", line 120, in claim
19:50:27:   File "inventory.py", line 136, in _claim
19:50:27:   File "twitch.py", line 1534, in gql_request
19:50:27: exceptions.MinerException: GQL error: [{'message': 'PersistedQueryNotFound'}]
19:50:27: 
19:50:27: Exiting...
19:50:27: 
19:50:27: Application Terminated.
19:50:27: Close the window to exit the application.
```

**Closed** 2024-07-03 15:18 UTC
Labels: Bug, Solved

**Comment by hifocus** [comment] 2024-07-22 18:18
Hi, I am still encountering this issue with the lastest master:

and also with the latest dev build in release - which I used originally

```
19:17:15: Fatal error encountered:
19:17:15: 
19:17:15: Traceback (most recent call last):
19:17:15:   File "main.py", line 153, in main
19:17:15:   File "twitch.py", line 570, in run
19:17:15:   File "twitch.py", line 620, in _run
19:17:15:   File "twitch.py", line 1428, in fetch_inventory
19:17:15:   File "asyncio\tasks.py", line 615, in _wait_for_one
19:17:15:   File "twitch.py", line 1383, in fetch_campaigns
19:17:15:   File "twitch.py", line 1350, in gql_request
19:17:15: exceptions.MinerException: GQL error: [{'message': 'PersistedQueryNotFound'}]
19:17:15: 
19:17:15: Exiting...
19:17:16: 
19:17:16: Application Terminated.
19:17:16: Close the window to exit the application.
```

Attaching the file I built through the script in the repository, on Windows 10

[Twitch Drops Miner (by DevilXD).zip](https://github.com/user-attachments/files/16338227/Twitch.Drops.Miner.by.DevilXD.zip)

**Comment by DevilXD** [comment] 2024-07-22 18:47
@hifocus It's already fixed in the latest master.
