### ISSUE TITLE
GQLException: [{'message': 'service error', 'path': ['channel', 'viewerDropCampaigns']}]

### ISSUE THREAD

**Issue by dogodogowoof** [DevilXD/TwitchDropsMiner#577] opened 2024-10-11 19:55 UTC
Encountering new issue when launching the app, deleting cookies.jar did not help. 

> 15:51:57: Fatal error encountered:
> 15:51:57: 
> 15:51:57: Traceback (most recent call last):
> 15:51:57:   File "main.py", line 155, in main
> 15:51:57:   File "twitch.py", line 587, in run
> 15:51:57:   File "twitch.py", line 747, in _run
> 15:51:57:   File "twitch.py", line 1656, in bulk_check_online
> 15:51:57:   File "asyncio\tasks.py", line 571, in _wait_for_one
> 15:51:57:   File "twitch.py", line 1387, in gql_request
> 15:51:57: exceptions.GQLException: [{'message': 'service error', 'path': ['channel', 'viewerDropCampaigns']}]
> 15:51:57: 
> 15:51:57: Exiting...
> 15:51:57: 
> 15:51:57: Application Terminated.
> 15:51:57: Close the window to exit the application.

![image](https://github.com/user-attachments/assets/aa0a5e67-c7a8-4245-85bb-c32cf6b1f440)

**Comment by xr1rx** [comment] 2024-10-11 20:03
Getting the exact same error message.

**Comment by DevilXD** [comment] 2024-10-11 20:42
Duplicate of #415.

This is the third one I'm closing today. Please really do use the search feature before posting.

**Closed by DevilXD** 2024-10-11 20:42 UTC
Labels: Bug, Duplicate
