### ISSUE TITLE
Waiting time to check for new drops is too much

### ISSUE THREAD

**Issue by St3ph32** [DevilXD/TwitchDropsMiner#101] opened 2022-12-18 13:28 UTC
A game started releasing new drops very frequently for Christmas and this software takes too much time to look for new ones. I don't know if it's implemented a simple wait of 1 hour or there are multiple checks but it doesn't seem to work well. If you are not going to fix this for various reasons like Twitch blocking too many connections, can it be done in another way?

**Comment by DevilXD** [comment] 2022-12-18 13:54
This is a duplicate of an already open issue: #90

**Closed by DevilXD** 2022-12-18 13:54 UTC
Labels: Bug, Duplicate
