### ISSUE TITLE
Latest version of Twitch Drops Miner convert to exe format request.

### ISSUE THREAD

**Issue by DogancanYr** [DevilXD/TwitchDropsMiner#152] opened 2023-03-01 15:55 UTC
Today i got the error message every time and I want to use it in Turkish.

18:50:20: Fatal error encountered:
18:50:20: 
18:50:20: Traceback (most recent call last):
18:50:20:   File "main.py", line 175, in <module>
18:50:20:   File "asyncio\base_events.py", line 616, in run_until_complete
18:50:20:   File "twitch.py", line 759, in run
18:50:20:   File "twitch.py", line 812, in _run
18:50:20:   File "inventory.py", line 202, in claim
18:50:20:   File "inventory.py", line 120, in claim
18:50:20:   File "inventory.py", line 136, in _claim
18:50:20:   File "twitch.py", line 1534, in gql_request
18:50:20: exceptions.MinerException: GQL error: [{'message': 'PersistedQueryNotFound'}]
18:50:20: 
18:50:20: Exiting...
18:50:20: 
18:50:20: Application Terminated.
18:50:20: Close the window to exit the application.

**Comment by Exdena** [comment] 2023-03-01 19:33
You can manually claim the reward to continue farming points as a work around.

**Comment by connorgallopo** [comment] 2023-03-01 19:47
That has nothing to do with using it in Turkish and is a duplicate of https://github.com/DevilXD/TwitchDropsMiner/issues/138

**Closed** 2023-03-01 20:01 UTC
