### ISSUE TITLE
Feature requet: Prioritize by campaign that takes the least time to complete

### ISSUE THREAD

**Issue by DealsBeam** [DevilXD/TwitchDropsMiner#516] opened 2024-07-14 12:06 UTC
Some campaigns take 30 minutes to complete, some campaigns take 1 hour and others 2

It would be great to have an option to prioritize a campaign that takes the least amount of 'watch' time to complete

**Comment by DevilXD** [comment] 2024-07-14 20:05
This is a duplicate of #330.

**Closed by DevilXD** 2024-07-14 20:05 UTC
Labels: Duplicate, Enhancement
