### ISSUE TITLE
Time Data error

### ISSUE THREAD

**Issue by Mousenkey** [DevilXD/TwitchDropsMiner#329] opened 2023-10-20 04:43 UTC
21:38:35: Fatal error encountered:
21:38:35: 
21:38:35: Traceback (most recent call last):
21:38:35:   File "main.py", line 175, in main
21:38:35:   File "twitch.py", line 765, in run
21:38:35:   File "twitch.py", line 807, in _run
21:38:35:   File "twitch.py", line 1604, in fetch_inventory
21:38:35:   File "twitch.py", line 1605, in <dictcomp>
21:38:35:   File "utils.py", line 88, in timestamp
21:38:35:   File "_strptime.py", line 568, in _strptime_datetime
21:38:35:   File "_strptime.py", line 349, in _strptime
21:38:35: ValueError: time data '2023-10-20T00:32:23.39Z' does not match format '%Y-%m-%dT%H:%M:%SZ'
21:38:35: 
21:38:35: Exiting...
21:38:36: 
21:38:36: Application Terminated.
21:38:36: Close the window to exit the application.

**Comment by DevilXD** [comment] 2023-10-20 17:35
Duplicate of #325.

**Closed by DevilXD** 2023-10-20 17:35 UTC
Labels: Bug, Duplicate
