### ISSUE TITLE
Program stops when a drop is ready to claim 

### ISSUE THREAD

**Issue by Brunitoezz** [DevilXD/TwitchDropsMiner#154] opened 2023-03-02 23:10 UTC
17:03:48: Fatal error encountered:
17:03:48: 
17:03:48: Traceback (most recent call last):
17:03:48:   File "main.py", line 175, in <module>
17:03:48:   File "asyncio\base_events.py", line 616, in run_until_complete
17:03:48:   File "twitch.py", line 759, in run
17:03:48:   File "twitch.py", line 812, in _run
17:03:48:   File "inventory.py", line 202, in claim
17:03:48:   File "inventory.py", line 120, in claim
17:03:48:   File "inventory.py", line 136, in _claim
17:03:48:   File "twitch.py", line 1534, in gql_request
17:03:48: exceptions.MinerException: GQL error: [{'message': 'PersistedQueryNotFound'}]
17:03:48: 
17:03:48: Exiting...
17:03:48: 
17:03:48: Application Terminated.
17:03:48: Close the window to exit the application.

**Comment by sahuidhsu** [comment] 2023-03-03 00:05
Got into the same problem for several times.
Looks like Twitch is preventing bots from claiming?

**Comment by DevilXD** [comment] 2023-03-03 06:43
Hello o/

This is a duplicate of #138 and is already fixed in the latest master, please see discussion there.

**Closed by DevilXD** 2023-03-03 06:43 UTC
Labels: Bug, Duplicate
