### ISSUE TITLE
Fatal error encountered

### ISSUE THREAD

**Issue by qzrsa** [DevilXD/TwitchDropsMiner#222] opened 2023-06-14 03:34 UTC
11:33:15: Fatal error encountered:
11:33:15: 
11:33:15: Traceback (most recent call last):
11:33:15:   File "main.py", line 174, in <module>
11:33:15:   File "asyncio\base_events.py", line 647, in run_until_complete
11:33:15:   File "twitch.py", line 769, in run
11:33:15:   File "twitch.py", line 788, in _run
11:33:15:   File "twitch.py", line 1459, in get_auth
11:33:15:   File "twitch.py", line 517, in validate
11:33:15:   File "twitch.py", line 526, in _validate
11:33:15:   File "contextlib.py", line 181, in __aenter__
11:33:15:   File "twitch.py", line 1484, in request
11:33:15:   File "gui.py", line 2054, in coro_unless_closed
11:33:15:   File "aiohttp\client.py", line 1125, in send
11:33:15:   File "aiohttp\client.py", line 536, in _request
11:33:15:   File "aiohttp\connector.py", line 540, in connect
11:33:15:   File "aiohttp\connector.py", line 901, in _create_connection
11:33:15:   File "aiohttp\connector.py", line 1175, in _create_direct_connection
11:33:15:   File "aiohttp\connector.py", line 980, in _wrap_create_connection
11:33:15:   File "asyncio\base_events.py", line 1050, in create_connection
11:33:15:   File "asyncio\base_events.py", line 961, in _connect_sock
11:33:15:   File "asyncio\proactor_events.py", line 703, in sock_connect
11:33:15: RuntimeError: await wasn't used with future
11:33:15: 
11:33:15: Exiting...
11:33:16: 
11:33:16: Application Terminated.
11:33:16: Close the window to exit the application.

How can I solve it?

**Comment by DevilXD** [comment] 2023-06-14 17:27
This is a duplicate of #80.

**Closed by DevilXD** 2023-06-14 17:27 UTC
Labels: Bug, Wont Fix
