### ISSUE TITLE
Channel viewing when idle

### ISSUE THREAD

**Issue by DaCrazyRaccoon** [DevilXD/TwitchDropsMiner#210] opened 2023-06-02 05:19 UTC
Would it be possible to be able to add channels to watch if there are no drops to get? It could go automatically go back to watching drops when one is available and vice versa. Once again, I'm not a coding genius so I'm sorry if that's asking for too much.

**Comment by DevilXD** [comment] 2023-06-02 15:04
This is a duplicate of #128 and #70. The current stance remains the same - right now, there's no point to watch any channels if said watching does not result in progressing a drop.

**Closed by DevilXD** 2023-06-02 15:04 UTC
Labels: Duplicate, Enhancement
