### ISSUE TITLE
Is this safe to use?

### ISSUE THREAD

**Issue by Meredith666** [DevilXD/TwitchDropsMiner#521] opened 2024-07-24 22:22 UTC
Is this safe to use? My malwarebytes is marking as malicious

**Comment by BrentMifsud** [comment] 2024-07-25 01:16
I've been using it for quite a while without any issues.

Its become increasingly unreliable though (drops not progressing, app dying etc....)

**Comment by DevilXD** [comment] 2024-07-25 05:18
This is more or less a duplicate of #517, #508, #503, #420, #384, #335, #333, #315, #284, #270, #249, #217, #209, #137 and #13.

Please always search existing issues before creating new ones. In case you'd like an actual explanation, check out the responses under some of the earlier issues linked above. Nothing much has really changed since then.

**Closed by DevilXD** 2024-07-25 05:18 UTC
Labels: Duplicate, Question
