### ISSUE TITLE
Add an exception/ignore "Not Linked" to farm drops for special games (HELLDIVERS 2)

### ISSUE THREAD

**Issue by JonJaded** [DevilXD/TwitchDropsMiner#439] opened 2024-02-17 00:11 UTC
Hey there, I'd like to farm HELLDIVERS 2 drops, but their drops work is accountless.

This is what you're presented with when trying to link accounts:
![image](https://github.com/DevilXD/TwitchDropsMiner/assets/35312501/fe20590a-be7b-4ac3-93ab-18429380eabb)

Once you log in, you're then shown the following, which doesn't link your account:
![image](https://github.com/DevilXD/TwitchDropsMiner/assets/35312501/b458ea9a-6c22-4f5d-971c-235c3eabb3a8)

So this game presents a Catch-22 where you need to watch the streamer to get a drop, but you can't link because you haven't watched the streamer. Also from how I understand it, there won't be a way to "Link" accounts because the site just spits out a redeemable code, rather than an account based system like all other games. 

With all that said, is it possible to ignore non linked for to farm drops for this game?

**Comment by DevilXD** [comment] 2024-02-17 10:36
This is a duplicate of #432. If the game developer doesn't want to use the Twitch system of linking accounts, then this makes the Helldivers 2 game unsupported by this miner.

**Closed by DevilXD** 2024-02-17 10:36 UTC
Labels: Bug, Duplicate

**Comment by JonJaded** [comment] 2024-02-17 10:58
Fair! I should've just searched for HD2 before I created the issue; sorry, my mistake!
