### ISSUE TITLE
Twitch points AFK with this app?

### ISSUE THREAD

**Issue by PauRussy502** [DevilXD/TwitchDropsMiner#227] opened 2023-06-15 19:35 UTC
This app could include an option to farm afk points from streamers, I see potential.

**Comment by DevilXD** [comment] 2023-06-16 17:47
This is a duplicate of #70.

Also check out the project goals: https://github.com/DevilXD/TwitchDropsMiner#project-goals

**Closed by DevilXD** 2023-06-16 17:47 UTC
Labels: Bug, Duplicate
