### ISSUE TITLE
not starting 

### ISSUE THREAD

**Issue by MehmetCanWT** [DevilXD/TwitchDropsMiner#358] opened 2023-11-07 11:02 UTC
![Screenshot_20231107-140056_Microsoft Remote Desktop](https://github.com/DevilXD/TwitchDropsMiner/assets/52177084/d5a1c6e4-b50a-485e-8dbf-ca375a8db6b9)

**Comment by DevilXD** [comment] 2023-11-07 20:05
This is a duplicate of #80.

**Closed by DevilXD** 2023-11-07 20:05 UTC
Labels: Bug, Duplicate
