### ISSUE TITLE
Destiny 2 Emblem Drop throwing fatal error

### ISSUE THREAD

**Issue by SumitSh7** [DevilXD/TwitchDropsMiner#576] opened 2024-10-11 18:50 UTC
This was during the dungeon race that had 2hr watchtime for a drop. 

20:47:14: Fatal error encountered:
20:47:14: 
20:47:14: Traceback (most recent call last):
20:47:14:   File "main.py", line 155, in main
20:47:14:   File "twitch.py", line 587, in run
20:47:14:   File "twitch.py", line 747, in _run
20:47:14:   File "twitch.py", line 1656, in bulk_check_online
20:47:14:   File "asyncio\tasks.py", line 571, in _wait_for_one
20:47:14:   File "twitch.py", line 1387, in gql_request
20:47:14: exceptions.GQLException: [{'message': 'service error', 'path': ['channel', 'viewerDropCampaigns']}]
20:47:14: 
20:47:14: Exiting...
20:47:14: 
20:47:14: Application Terminated.
20:47:14: Close the window to exit the application.

![image](https://github.com/user-attachments/assets/14679b4f-a4bb-4830-a009-20314bd935b5)

![image](https://github.com/user-attachments/assets/fd121fa5-6e75-4e75-8301-ff75afb2b0e4)

**Comment by DevilXD** [comment] 2024-10-11 19:06
Hello,

"service error" means an internal server error on Twitch side. There's nothing I can do about it. It'll go away on it's own eventually, once Twitch fixes the issue on their side. You can try again tomorrow, or a day after that. Usually it doesn't even last that long.

This is also a duplicate of #415. I've closed a similar issue less than an hour ago - please use the search feature before reporting next time.

**Closed by DevilXD** 2024-10-11 19:06 UTC
Labels: Bug, Duplicate
