### ISSUE TITLE
Invalid timestamp format

### ISSUE THREAD

**Issue by BrentMifsud** [DevilXD/TwitchDropsMiner#365] opened 2023-11-16 15:27 UTC
Application is terminating on launch with the following error:

```
10:26:11: Fatal error encountered:
10:26:11: 
10:26:11: Traceback (most recent call last):
10:26:11:   File "main.py", line 175, in main
10:26:11:   File "twitch.py", line 765, in run
10:26:11:   File "twitch.py", line 807, in _run
10:26:11:   File "twitch.py", line 1604, in fetch_inventory
10:26:11:   File "twitch.py", line 1605, in <dictcomp>
10:26:11:   File "utils.py", line 88, in timestamp
10:26:11:   File "_strptime.py", line 568, in _strptime_datetime
10:26:11:   File "_strptime.py", line 349, in _strptime
10:26:11: ValueError: time data '2023-11-16T07:16:21.049Z' does not match format '%Y-%m-%dT%H:%M:%SZ'
10:26:11: 
10:26:11: Exiting...
10:26:11: 
10:26:11: Application Terminated.
10:26:11: Close the window to exit the application.
```

**Comment by DevilXD** [comment] 2023-11-16 19:35
Duplicate of #345.

**Closed by DevilXD** 2023-11-16 19:35 UTC
Labels: Bug, Duplicate
