### ISSUE TITLE
Trojan:Win32/Wacatac.B!ml process

### ISSUE THREAD

**Issue by Hyrius** [DevilXD/TwitchDropsMiner#291] opened 2023-09-03 05:48 UTC
Windows Defender is detecting the executable as a Trojan:Win32/Wacatac.B!ml process. 
Most likely a false positive, but thought you should know. 

![trojjj](https://github.com/DevilXD/TwitchDropsMiner/assets/757963/cd36f67f-568c-4c49-8269-e850cac0ec60)

It updated its definition files today. 
I am on Windows 10.

**Comment by DevilXD** [comment] 2023-09-03 08:06
This is a duplicate of #284, #270, #249, #217, #209 and #13. Please do some minimum research before reporting anything next time. And I should really put out a note in the README for this.

**Closed by DevilXD** 2023-09-03 08:06 UTC
Labels: Duplicate, Help / Issue
