### ISSUE TITLE
Dev Build Windows 2023-06-16 Blocked by windows defender

### ISSUE THREAD

**Issue by DavidRainearJr** [DevilXD/TwitchDropsMiner#231] opened 2023-06-16 21:03 UTC
The latest dev build is being blocked by windows defender, version 2023-06-16 18:05:02+00:00. Had to switch to v15. Letting you know so you can fix it before v16.

**Comment by DevilXD** [comment] 2023-06-17 15:37
This is a duplicate of #217.

**Closed by DevilXD** 2023-06-17 15:37 UTC
Labels: Bug, Duplicate
