### ISSUE TITLE
Auto reload at crash (feature request / bug)

### ISSUE THREAD

**Issue by Mega349** [DevilXD/TwitchDropsMiner#147] opened 2023-02-25 00:21 UTC
# Crash at claiming (sometimes)
This error appears while claiming drops, its catched and the application wont crash but the progress bar is frozen.

## Stack trace:
```
01:01:31: ERROR: Exception in task
01:01:31: Traceback (most recent call last):
01:01:31:   File "utils.py", line 96, in wrapper
01:01:31:   File "twitch.py", line 1332, in process_drops
01:01:31:   File "inventory.py", line 202, in claim
01:01:31:   File "inventory.py", line 120, in claim
01:01:31:   File "inventory.py", line 136, in _claim
01:01:31:   File "twitch.py", line 1534, in gql_request
01:01:31: exceptions.MinerException: GQL error: [{'message': 'PersistedQueryNotFound'}]
```

In some cases while claiming drops, ill got an error (without crash).
Could you soft restart the application or just trigger the reload function?

---

## some other crashs, i dont know the reason:

In some cases (no stacktrace atm) the application will crash (but not the gui) could you catch all errors and restart the application?
Maybe as an optional flag.

I know if twitch break some thinks it could end in a endless loop, so you could add a crash counter.
Currently your application runs well with some crashes but watching and claiming works in the most cases.

**Comment by xb2377** [comment] 2023-02-25 04:44
Many people have this error. Is the author not updated?

**Comment by Suz1e** [comment] 2023-02-25 08:21
This issue has been fixed, but there is no guarantee how long it will be available, a new fix has been released to Git
https://github.com/DevilXD/TwitchDropsMiner/commit/466a3aa8f2982eca2e4c441cd254aa01941d17e6

**Comment by DevilXD** [comment] 2023-02-25 09:11
This is a duplicate of #138. Also, I'm not interested in automatic restart as a feature, for reasons explained here: https://github.com/DevilXD/TwitchDropsMiner/issues/138#issuecomment-1444507304  This is this a NoFix as well.

**Closed by DevilXD** 2023-02-25 09:11 UTC
Labels: Duplicate, Enhancement, Wont Fix
