### ISSUE TITLE
account linked no mining

### ISSUE THREAD

**Issue by matarife123** [DevilXD/TwitchDropsMiner#77] opened 2022-11-20 18:18 UTC
![Sin título](https://user-images.githubusercontent.com/110930030/202918915-a820beb9-6343-4ef2-830e-f9b06d6ac333.png)

does not detect some channels to mine drops

**Comment by DevilXD** [comment] 2022-11-20 18:54
Hello o/

Have you added that game to the Priority list and reloaded? Can you show me your Settings tab setup?

**Comment by matarife123** [comment] 2022-11-20 18:56
i add the game and nothing
![Sin título](https://user-images.githubusercontent.com/110930030/202920521-7b0cec47-7a8a-4152-a5e1-c250f14b7be3.png)

**Comment by DevilXD** [comment] 2022-11-20 19:08
You're running into #69 then, as this particular campaign as a disabled ACL:
![obraz](https://user-images.githubusercontent.com/4180725/202920901-e9cf0000-6939-4394-92eb-4ca663ed93ee.png)

There's no channels in the actual ACL, so essentially the campaign ends up as one where there's no channels the miner can use to be able to mine this campaign, and it skips it. This is already fixed in the current master and thus this makes this issue a duplicate of #69. You'll need to either wait for the next release, or build a new executable from the current master branch per READM instuctions.

**Closed by DevilXD** 2022-11-20 19:08 UTC
Labels: Bug, Duplicate

**Comment by matarife123** [comment] 2022-11-20 19:14
thanks you for all

**Comment by DevilXD** [comment] 2022-11-20 21:27
I've actually looked into this matter a little bit more, because I've noticed that the code will actually treat an empty ACL as no ACL, and should proceed correctly from there anyway. The thing is, this particular campaign is really weird with it's drops, and the miner is still working as intended.

These are the time intervals between which each drop from that campaign can be earned:
![obraz](https://user-images.githubusercontent.com/4180725/202926815-e8aa66a1-dfe1-4d7c-95bb-392a2a210b30.png)

Disregarding the time, the first drop can be earned only between 18-20th, further two: 26-27th, and final four: 2-3rd of the next month. This means that between 20th and 26th, and 27th and 2nd of the next month, the campaign remains active, but none of it's drops can be earned - this should be signified by the drops displaying just "X minutes" instead of "0.0% of X minutes" on the inventory tab. If no percentage is displayed, the `can_earn` condition for that drop remains `False` and that in turn instructs the miner that it cannot be mined.

Are you able to progress the campaign when watching "manually"? Besides that "you can earn this drop" message that's displayed, does it actually increase the percentage or not?
