### ISSUE TITLE
Switching stream manually results in "twitch offline" messages

### ISSUE THREAD

**Issue by Serray** [DevilXD/TwitchDropsMiner#498] opened 2024-06-14 06:30 UTC
Hallo,

If i choose any other stream than the one the program selects on startup, im getting the message that twitch is offline.
It does not recover from it. However, I sometimes do get channel points.

Also i do not make any progress in drops, whether i select a stream manual, or with the automatically selected one.

**Comment by DevilXD** [comment] 2024-06-15 11:36
Duplicate of #497.

**Closed by DevilXD** 2024-06-15 11:36 UTC
