### ISSUE TITLE
Miner not mining overwatch

### ISSUE THREAD

**Issue by MuffinzCat** [DevilXD/TwitchDropsMiner#474] opened 2024-05-19 20:05 UTC
I don't have many technical details, but currently an overwatch campaign is running, and it only progresses by physically watching the game.
I'm on the latest commit of the master branch and I've used the setup_dev batch file already.

**Comment by cryyin** [comment] 2024-05-19 20:25
same issue

**Comment by Smallinger** [comment] 2024-05-20 04:09
i use this version: https://github.com/Windows200000/TwitchDropsMiner-updated/releases/tag/v15.2.0

its not "Overwatch" its "Overwatch 2" you can try this in your settings.json

![image](https://github.com/DevilXD/TwitchDropsMiner/assets/8080568/a522b9fa-ed4b-4d57-9763-1ec05ffc9b44)


`
{
    "autostart": true,
    "autostart_tray": false,
    "connection_quality": 1,
    "exclude": {
        "__type": "set",
        "data": []
    },
    "language": "English",
    "priority": [
    	"Overwatch 2"
    ],
    "priority_only": false,
    "proxy": {
        "__type": "URL",
        "data": ""
    },
    "tray_notifications": true
}

`
or

`
{
    "autostart": true,
    "autostart_tray": false,
    "connection_quality": 1,
    "exclude": {
        "__type": "set",
        "data": []
    },
    "language": "English",
    "priority": [
    	"Overwatch 2"
    ],
    "priority_only": true,
    "proxy": {
        "__type": "URL",
        "data": ""
    },
    "tray_notifications": true
}

`

**Comment by cryyin** [comment] 2024-05-20 05:13
I am using overwatch2 it shows the time is growing but when I go to twitch there's no progress for it. after restart the miner rate back to 0%

**Comment by Smallinger** [comment] 2024-05-20 05:25
> I am using overwatch2 it shows the time is growing but when I go to twitch there's no progress for it. after restart the miner rate back to 0%

hmm ok for me its working, try the fork that i posted above there is a "fix for 2024/5 API Change" in it

![image](https://github.com/DevilXD/TwitchDropsMiner/assets/8080568/9faa7152-1920-4bc8-bcd1-d0021522868d)

**Comment by MuffinzCat** [comment] 2024-05-20 10:03
> I am using overwatch2 it shows the time is growing but when I go to twitch there's no progress for it. after restart the miner rate back to 0%

Seems to be happening with all games

**Comment by MuffinzCat** [comment] 2024-05-20 10:04
> > I am using overwatch2 it shows the time is growing but when I go to twitch there's no progress for it. after restart the miner rate back to 0%
> 
> hmm ok for me its working, try the fork that i posted above there is a "fix for 2024/5 API Change" in it
> 
> > i use this fork: https://github.com/Windows200000/TwitchDropsMiner-updated/releases/tag/v15.2.0
> 
> ![image](https://private-user-images.githubusercontent.com/8080568/331952121-9faa7152-1920-4bc8-bcd1-d0021522868d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxOTk0MDUsIm5iZiI6MTcxNjE5OTEwNSwicGF0aCI6Ii84MDgwNTY4LzMzMTk1MjEyMS05ZmFhNzE1Mi0xOTIwLTRiYzgtYmNkMS1kMDAyMTUyMjg2OGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjBUMDk1ODI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWEzODRlZmNkNTJlZTY4ZWE2OWUwMThiYTBmMWY0MjY3MzdlNmNmMTg5MjM3ZGFmNGZiZWZlOThmNTFkM2M2MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.3TKkG7sNn6Y20OQHhXV4aZ5nVaq3PAFwh41zSXsMKQE)

Tried downloading it, but windows flags it as a virus and stops the download

**Comment by matarife123** [comment] 2024-05-20 21:26
> i use this fork: https://github.com/Windows200000/TwitchDropsMiner-updated/releases/tag/v15.2.0
> 
> its not "Overwatch" its "Overwatch 2" you can try this in your settings.json
> 
> ![image](https://private-user-images.githubusercontent.com/8080568/331939830-a522b9fa-ed4b-4d57-9763-1ec05ffc9b44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyNDA2MzEsIm5iZiI6MTcxNjI0MDMzMSwicGF0aCI6Ii84MDgwNTY4LzMzMTkzOTgzMC1hNTIyYjlmYS1lZDRiLTRkNTctOTc2My0xZWMwNWZmYzliNDQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjBUMjEyNTMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDE5NjIyNzE5YjUxNDZkZTNlYjU5NmE1MGNkZTM5OTJhZTI0OTJhMDA1MTg1NmFiOGYxMjM0MGQ5Mjc3NDg0OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.lBeDstixzNIvPQuaV6uaBLzxoRtoeWB7WNlcXD8FGIg)
> 
> ```
> {
>     "autostart": true,
>     "autostart_tray": false,
>     "connection_quality": 1,
>     "exclude": {
>         "__type": "set",
>         "data": []
>     },
>     "language": "English",
>     "priority": [
>     	"Overwatch 2"
>     ],
>     "priority_only": false,
>     "proxy": {
>         "__type": "URL",
>         "data": ""
>     },
>     "tray_notifications": true
> }
> ```
> 
> or with "priority_only: true"
> 
> ```
> {
>     "autostart": true,
>     "autostart_tray": false,
>     "connection_quality": 1,
>     "exclude": {
>         "__type": "set",
>         "data": []
>     },
>     "language": "English",
>     "priority": [
>     	"Overwatch 2"
>     ],
>     "priority_only": true,
>     "proxy": {
>         "__type": "URL",
>         "data": ""
>     },
>     "tray_notifications": true
> }
> ```

very thanks you ^^

**Comment by DevilXD** [comment] 2024-05-21 21:20
Duplicate of #462.

**Closed by DevilXD** 2024-05-21 21:20 UTC
Labels: Bug, Duplicate
