### ISSUE TITLE
Unknown problem

### ISSUE THREAD

**Issue by HinaMai** [DevilXD/TwitchDropsMiner#305] opened 2023-09-21 14:49 UTC
22:46:27: Fatal error encountered:
22:46:27: 
22:46:27: Traceback (most recent call last):
22:46:27:   File "main.py", line 158, in main
22:46:27:   File "twitch.py", line 765, in run
22:46:27:   File "twitch.py", line 784, in _run
22:46:27:   File "twitch.py", line 1455, in get_auth
22:46:27:   File "twitch.py", line 516, in validate
22:46:27:   File "twitch.py", line 525, in _validate
22:46:27:   File "contextlib.py", line 204, in __aenter__
22:46:27:   File "twitch.py", line 1480, in request
22:46:27:   File "gui.py", line 2050, in coro_unless_closed
22:46:27:   File "aiohttp\client.py", line 1125, in send
22:46:27:   File "aiohttp\client.py", line 536, in _request
22:46:27:   File "aiohttp\connector.py", line 540, in connect
22:46:27:   File "aiohttp\connector.py", line 901, in _create_connection
22:46:27:   File "aiohttp\connector.py", line 1178, in _create_direct_connection
22:46:27:   File "aiohttp\connector.py", line 980, in _wrap_create_connection
22:46:27:   File "asyncio\base_events.py", line 1069, in create_connection
22:46:27:   File "asyncio\base_events.py", line 973, in _connect_sock
22:46:27:   File "asyncio\proactor_events.py", line 726, in sock_connect
22:46:27: RuntimeError: await wasn't used with future
22:46:27: 
22:46:27: 正在退出...
22:46:28: 
22:46:28: 应用程序已终止，请关闭窗口以退出应用程序。

**Comment by guihkx** [comment] 2023-09-21 16:04
- https://github.com/DevilXD/TwitchDropsMiner/issues/80

**Comment by DevilXD** [comment] 2023-09-22 09:02
This is a duplicate of #80.

**Closed by DevilXD** 2023-09-22 09:02 UTC
Labels: Bug, Duplicate
