### ISSUE TITLE
Feature Request: Ability to skip current drop

### ISSUE THREAD

**Issue by avdichiara** [DevilXD/TwitchDropsMiner#338] opened 2023-10-28 06:52 UTC
Given some of the issues that people are having (including me) with the miner farming already mined drops, it would be nice to have some sort of manual override that allows users to skip to the next drop without finishing the current one. In theory, this could be done by modifying the priority order, but I still think a skip button would be nice (especially if/when future issues occur) so that the priority order isn't constantly changing. I have a set order for my drops, and it would be a pain to have to manually reset it after every drop.

Thanks for making such a useful app!

**Comment by DevilXD** [comment] 2023-10-28 08:19
Hello o/

Given my very limited personal time, I'd rather fix the miner so that it actually does what it's supposed to, instead of spending time to work around an issue that shouldn't be a thing in the first place. There actually is an already open issue about pretty much the same thing, so this is a duplicate of #170.

**Closed by DevilXD** 2023-10-28 08:19 UTC
Labels: Duplicate, Enhancement
