### ISSUE TITLE
im new to this plz help

### ISSUE THREAD

**Issue by Bad-Biene** [DevilXD/TwitchDropsMiner#179] opened 2023-04-24 16:20 UTC
18:15:59: Fatal error encountered:
18:15:59: 
18:15:59: Traceback (most recent call last):
18:15:59:   File "main.py", line 175, in <module>
18:15:59:   File "asyncio\base_events.py", line 616, in run_until_complete
18:15:59:   File "twitch.py", line 759, in run
18:15:59:   File "twitch.py", line 778, in _run
18:15:59:   File "twitch.py", line 1449, in get_auth
18:15:59:   File "twitch.py", line 512, in validate
18:15:59:   File "twitch.py", line 540, in _validate
18:15:59:   File "twitch.py", line 295, in _oauth_login
18:15:59:   File "contextlib.py", line 171, in __aenter__
18:15:59:   File "twitch.py", line 1474, in request
18:15:59:   File "gui.py", line 1946, in coro_unless_closed
18:15:59:   File "aiohttp\client.py", line 1125, in send
18:15:59:   File "aiohttp\client.py", line 536, in _request
18:15:59:   File "aiohttp\connector.py", line 540, in connect
18:15:59:   File "aiohttp\connector.py", line 901, in _create_connection
18:15:59:   File "aiohttp\connector.py", line 1175, in _create_direct_connection
18:15:59:   File "aiohttp\connector.py", line 980, in _wrap_create_connection
18:15:59:   File "asyncio\base_events.py", line 1010, in create_connection
18:15:59:   File "asyncio\base_events.py", line 924, in _connect_sock
18:15:59:   File "asyncio\proactor_events.py", line 702, in sock_connect
18:15:59: RuntimeError: await wasn't used with future
18:15:59: 
18:15:59: Exiting...
18:15:59: 
18:15:59: Application Terminated.
18:15:59: Close the window to exit the application.

**Comment by DevilXD** [comment] 2023-04-25 05:12
Hello o/

This is a duplicate of #80.

**Closed by DevilXD** 2023-04-25 05:12 UTC
