### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by kalakoa** [DevilXD/TwitchDropsMiner#218] opened 2023-06-11 12:36 UTC
12:32:22: Fatal error encountered:
12:32:22: 
12:32:22: Traceback (most recent call last):
12:32:22:   File "main.py", line 170, in <module>
12:32:22:   File "asyncio\base_events.py", line 653, in run_until_complete
12:32:22:   File "twitch.py", line 764, in run
12:32:22:   File "twitch.py", line 783, in _run
12:32:22:   File "twitch.py", line 1454, in get_auth
12:32:22:   File "twitch.py", line 517, in validate
12:32:22:   File "twitch.py", line 526, in _validate
12:32:22:   File "contextlib.py", line 204, in __aenter__
12:32:22:   File "twitch.py", line 1479, in request
12:32:22:   File "gui.py", line 1955, in coro_unless_closed
12:32:22:   File "aiohttp\client.py", line 1125, in send
12:32:22:   File "aiohttp\client.py", line 536, in _request
12:32:22:   File "aiohttp\connector.py", line 540, in connect
12:32:22:   File "aiohttp\connector.py", line 901, in _create_connection
12:32:22:   File "aiohttp\connector.py", line 1175, in _create_direct_connection
12:32:22:   File "aiohttp\connector.py", line 980, in _wrap_create_connection
12:32:22:   File "asyncio\base_events.py", line 1069, in create_connection
12:32:22:   File "asyncio\base_events.py", line 973, in _connect_sock
12:32:22:   File "asyncio\proactor_events.py", line 726, in sock_connect
12:32:22: RuntimeError: await wasn't used with future
12:32:22: 
12:32:22: Exiting...
12:32:23: 
12:32:23: Application Terminated.
12:32:23: Close the window to exit the application.

**Comment by DevilXD** [comment] 2023-06-11 13:14
This is a duplicate of #80.

**Closed by DevilXD** 2023-06-11 13:14 UTC
Labels: Bug, Duplicate
