### ISSUE TITLE
Unhandled exception in script

### ISSUE THREAD

**Issue by WyWlf** [DevilXD/TwitchDropsMiner#243] opened 2023-07-02 00:31 UTC
Just recently got this error from the build i've been using since last month

Hadn't done any changes other than the temp fix #189 provided here but i already did this last month so i dont think it has anything to do with this error 

![image](https://github.com/DevilXD/TwitchDropsMiner/assets/117328165/c0a0299d-7b63-46f4-8544-81881d27569a)

**Comment by noahnao** [comment] 2023-07-02 13:44
I've been having the same issue, tried to an older version still same problem. Please Fix

![Skærmbillede 2023-07-02 154029](https://github.com/DevilXD/TwitchDropsMiner/assets/81416193/1700e8b3-3964-4d56-904a-3dfeb8c96343)

**Comment by DevilXD** [comment] 2023-07-02 16:52
@WyWlf This is a duplicate of #187. The error may not be the exact same, but the cause and solution provided there is identical.

@noahnao Your issue is related to 3rd party libraries being installed incorrectly, Pillow specifically. You seem to be running the miner from source. Rebuilding the `env` folder should solve the issue for you. Also make sure you're actually running the miner from the `env` folder, not directly from Python. In case of any trouble, refer to https://github.com/DevilXD/TwitchDropsMiner/wiki/Setting-up-the-environment,-building-and-running, or open a separate issue, please.

**Closed by DevilXD** 2023-07-02 16:52 UTC
Labels: Bug, Duplicate
