### ISSUE TITLE
Drop progress keeps resetting

### ISSUE THREAD

**Issue by thatOWguy** [DevilXD/TwitchDropsMiner#343] opened 2023-10-31 02:43 UTC
Hi, so I was farming for drops on Saturday and left it on overnight because the drops were gonna expire the next day, but when I woke up I saw I didn't get any. I thought it was weird because I left it on overnight, more than enough time to get the drops. It was a bummer, but I moved on to the next set of drops. Well, once again I left it on for a few hours, came back and the progress had barely moved past 7%. Again, I knew for sure it had been two hours minimum and my progress should have been more than halfway done. 

I decided I would just leave it on and not even minimize it, but it didn't work. I finally just closed out of the whole application, but decided to try again a few minutes later. That's when I noticed it had reset the progress. So the problem wasn't it being slow and not tracking time watched, it was just resetting every time it switched to a new streamer (I'm assuming, as I never had exited the application until then). I manually switched and it didn't reset, so I think maybe it's when the current streamer goes offline and it resets when searching for a new one? 

I'm using V16 (I tried running previous versions and they wouldn't even open).

**Comment by DevilXD** [comment] 2023-10-31 08:31
Please check the existing issues before making new ones. This is a duplicate of #301.

**Closed by DevilXD** 2023-10-31 08:31 UTC
Labels: Bug, Duplicate
